SCADARPI API (work_modulator): Main Class Reference
Main Class Reference
Static Public Member Functions
static void main (String[] args) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Program Test Main Entry Point.
Static Private Attributes
static final int CONTROLLINO_ADDR = 0x10
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 36 of file Main.java.
Member Function Documentation
main()
static void Main.main (String[] args) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException static
Program Test Main Entry Point.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 51 of file Main.java.
References CONTROLLINO_ADDR, Device.doStart(), ModbusSlaveThread.doStart(), GlgGui.exitProgram(), and logger.
Member Data Documentation
CONTROLLINO_ADDR
final int Main.CONTROLLINO_ADDR = 0x10 static private
Definition at line 41 of file Main.java.
Referenced by main().
logger
final Logger Main.logger = Logger.getLogger("Main") static private
Definition at line 38 of file Main.java.
Referenced by main().
The documentation for this class was generated from the following file:
work_modulator/Main.java