var annotated_dup =
[
    [ "ChannelList", "interfaceChannelList.html", "interfaceChannelList" ],
    [ "Controllino", "classControllino.html", "classControllino" ],
    [ "DataElement", "classDataElement.html", "classDataElement" ],
    [ "DataManager", "classDataManager.html", "classDataManager" ],
    [ "DataTypes", "interfaceDataTypes.html", [
      [ "DataType", "enumDataTypes_1_1DataType.html", "enumDataTypes_1_1DataType" ],
      [ "RegisterType", "enumDataTypes_1_1RegisterType.html", "enumDataTypes_1_1RegisterType" ]
    ] ],
    [ "Device", "classDevice.html", "classDevice" ],
    [ "DeviceManager", "classDeviceManager.html", "classDeviceManager" ],
    [ "DialogSetPoint", "classDialogSetPoint.html", "classDialogSetPoint" ],
    [ "GlgChildGui", "classGlgChildGui.html", "classGlgChildGui" ],
    [ "GlgDryGui", "classGlgDryGui.html", "classGlgDryGui" ],
    [ "GlgGaugeGui", "classGlgGaugeGui.html", "classGlgGaugeGui" ],
    [ "GlgGui", "classGlgGui.html", "classGlgGui" ],
    [ "GlgIonicGui", "classGlgIonicGui.html", "classGlgIonicGui" ],
    [ "GlgRGAGui", "classGlgRGAGui.html", "classGlgRGAGui" ],
    [ "GlgTitane_22Gui", "classGlgTitane__22Gui.html", "classGlgTitane__22Gui" ],
    [ "GlgTitane_32Gui", "classGlgTitane__32Gui.html", "classGlgTitane__32Gui" ],
    [ "GlgTubeStatusDetailsGui", "classGlgTubeStatusDetailsGui.html", "classGlgTubeStatusDetailsGui" ],
    [ "GlgTurboGui", "classGlgTurboGui.html", "classGlgTurboGui" ],
    [ "GlgValveGui", "classGlgValveGui.html", "classGlgValveGui" ],
    [ "GlgXGSGaugeGui", "classGlgXGSGaugeGui.html", "classGlgXGSGaugeGui" ],
    [ "I2C_Comm", "classI2C__Comm.html", "classI2C__Comm" ],
    [ "IonicAgilentDual", "classIonicAgilentDual.html", "classIonicAgilentDual" ],
    [ "Main", "classMain.html", "classMain" ],
    [ "MaxiGauge", "classMaxiGauge.html", "classMaxiGauge" ],
    [ "ModbusSlaveThread", "classModbusSlaveThread.html", "classModbusSlaveThread" ],
    [ "RgaPfeifferQms200", "classRgaPfeifferQms200.html", "classRgaPfeifferQms200" ],
    [ "RoundedBorder", "classRoundedBorder.html", "classRoundedBorder" ],
    [ "RoundJTextField", "classRoundJTextField.html", "classRoundJTextField" ],
    [ "Serial_Comm", "classSerial__Comm.html", "classSerial__Comm" ],
    [ "TitaneVarianTSP_22", "classTitaneVarianTSP__22.html", "classTitaneVarianTSP__22" ],
    [ "TitaneVarianTSP_32", "classTitaneVarianTSP__32.html", "classTitaneVarianTSP__32" ],
    [ "TurboPfeifferDCU", "classTurboPfeifferDCU.html", "classTurboPfeifferDCU" ],
    [ "TurboVarianV81AG", "classTurboVarianV81AG.html", "classTurboVarianV81AG" ],
    [ "XGSGauge", "classXGSGauge.html", "classXGSGauge" ]
];