SCADARPI API (work_pump_rack): ModbusSlaveThread.ModbusSlaveDataHolder Class Reference
ModbusSlaveThread.ModbusSlaveDataHolder Class Reference
Public Member Functions
void addEventListener (ModbusEventListener listener)
ModbusSlaveDataHolder ()
boolean removeEventListener (ModbusEventListener listener)
void writeCoil (int offset, boolean value) throws IllegalDataAddressException, IllegalDataValueException
void writeCoilRange (int offset, boolean[] range) throws IllegalDataAddressException, IllegalDataValueException
void writeHoldingRegister (int offset, int value) throws IllegalDataAddressException, IllegalDataValueException
void writeHoldingRegisterRange (int offset, int[] range) throws IllegalDataAddressException, IllegalDataValueException
Detailed Description
Definition at line 194 of file ModbusSlaveThread.java.
Constructor & Destructor Documentation
ModbusSlaveDataHolder()
ModbusSlaveThread.ModbusSlaveDataHolder.ModbusSlaveDataHolder ()
Definition at line 198 of file ModbusSlaveThread.java.
References ModbusSlaveThread.configureRegistersFromAllDevice(), DeviceManager.deviceList, ModbusSlaveThread.deviceManager, and ModbusSlaveThread.logger.
Member Function Documentation
addEventListener()
void ModbusSlaveThread.ModbusSlaveDataHolder.addEventListener (ModbusEventListener listener)
Definition at line 211 of file ModbusSlaveThread.java.
Referenced by ModbusSlaveThread.ModbusSlaveThread().
removeEventListener()
boolean ModbusSlaveThread.ModbusSlaveDataHolder.removeEventListener (ModbusEventListener listener)
Definition at line 215 of file ModbusSlaveThread.java.
writeCoil()
void ModbusSlaveThread.ModbusSlaveDataHolder.writeCoil (int offset, boolean value) throws IllegalDataAddressException, IllegalDataValueException
Definition at line 250 of file ModbusSlaveThread.java.
writeCoilRange()
void ModbusSlaveThread.ModbusSlaveDataHolder.writeCoilRange (int offset, boolean[] range) throws IllegalDataAddressException, IllegalDataValueException
Definition at line 259 of file ModbusSlaveThread.java.
writeHoldingRegister()
void ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegister (int offset, int value) throws IllegalDataAddressException, IllegalDataValueException
Definition at line 220 of file ModbusSlaveThread.java.
References Device.addModbusCommand(), DeviceManager.deviceList, ModbusSlaveThread.deviceManager, DataManager.getDataElement(), Device.modbusmutex, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.TRIGGER, and DataElement.type.
writeHoldingRegisterRange()
void ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegisterRange (int offset, int[] range) throws IllegalDataAddressException, IllegalDataValueException
Definition at line 241 of file ModbusSlaveThread.java.
The documentation for this class was generated from the following file:
work_pump_rack/ModbusSlaveThread.java