SCADARPI API (work_clim): GlgPropsGui Class Reference
GlgPropsGui Class Reference
Classes
class InputListener
Public Member Functions
GlgPropsGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
void updateGuiFeatures (String glgName, DataElement dataElement)
Public Member Functions inherited from GlgChildGui
void doStart ()
void doStop ()
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
void run ()
Protected Member Functions
void createAndShowGui ()
void createStatusMap (Hashtable< String, String > _STATUS)
Protected Member Functions inherited from GlgChildGui
void createCommandMap (Hashtable< String, String > CMD)
void updateGui ()
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
static final long serialVersionUID = 354054054075L
Additional Inherited Members
Public Attributes inherited from GlgChildGui
GlgChildGui child
boolean isSuspended = false
GlgGui parent
Public Attributes inherited from ChannelList
String mainDrawing = "Station.g"
Hashtable< String, String > STATIONCMD
Hashtable< String, String > STATIONSTATUS
Protected Attributes inherited from GlgChildGui
Hashtable< String, String > CMD = new Hashtable < String, String > ()
Container content
DeviceManager deviceManager
GlgJLWBean glg_bean
String glgdrawing
String origin
Hashtable< String, String > STATUS = new Hashtable < String, String > ()
String title
Detailed Description
Definition at line 17 of file GlgPropsGui.java.
Constructor & Destructor Documentation
GlgPropsGui()
GlgPropsGui.GlgPropsGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
Definition at line 22 of file GlgPropsGui.java.
Member Function Documentation
createAndShowGui()
void GlgPropsGui.createAndShowGui () protected
Reimplemented from GlgChildGui.
Definition at line 26 of file GlgPropsGui.java.
References GlgChildGui.content, createStatusMap(), GlgChildGui.glg_bean, logger, GlgChildGui.STATUS, and GlgChildGui.title.
createStatusMap()
void GlgPropsGui.createStatusMap (Hashtable< String, String > _STATUS) protected
Reimplemented from GlgChildGui.
Definition at line 45 of file GlgPropsGui.java.
References logger, ChannelList.STATIONSTATUS, and GlgChildGui.STATUS.
Referenced by createAndShowGui().
updateGuiFeatures()
void GlgPropsGui.updateGuiFeatures (String glgName, DataElement dataElement)
Reimplemented from GlgChildGui.
Definition at line 56 of file GlgPropsGui.java.
References GlgChildGui.glg_bean, logger, DataElement.name, and DataElement.value.
Member Data Documentation
logger
final Logger GlgPropsGui.logger = Logger.getLogger("Main") static private
Definition at line 20 of file GlgPropsGui.java.
Referenced by createAndShowGui(), createStatusMap(), GlgPropsGui.InputListener.InputCallback(), and updateGuiFeatures().
serialVersionUID
final long GlgPropsGui.serialVersionUID = 354054054075L static private
Definition at line 19 of file GlgPropsGui.java.
The documentation for this class was generated from the following file:
work_clim/GlgPropsGui.java