SCADARPI API (work_pcounter): GlgPCounter2Gui Class Reference
GlgPCounter2Gui Class Reference
Classes
class InputListener
Public Member Functions
void createCommandMap (Hashtable< String, String > CMD)
void createStatusMap (Hashtable< String, String > STATUS)
GlgPCounter2Gui (GlgGui _parent, Operation _op, String _title, String _origin)
Public Member Functions inherited from GlgChildGui
void doStart ()
void doStop ()
GlgChildGui (GlgGui _parent, Operation _op, String _title, String _origin)
void run ()
Protected Member Functions
void createAndShowGui ()
void updateGuiFeatures (String glgName, DataElement dataElement)
Protected Member Functions inherited from GlgChildGui
void updateGui ()
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
static final long serialVersionUID = 354054054072L
Additional Inherited Members
Public Attributes inherited from GlgChildGui
GlgChildGui child
boolean isSuspended = false
GlgGui parent
Public Attributes inherited from ChannelList
Hashtable< Integer, GlgPoint > ACColorSTATUS
Hashtable< Integer, String > ACSTATUS
Hashtable< Integer, GlgPoint > BypassColorSTATUS
Hashtable< Integer, String > BypassSTATUS
Hashtable< Integer, GlgPoint > FailOkColorSTATUS
Hashtable< Integer, String > FailOkSTATUS
Hashtable< Integer, GlgPoint > FanColorSTATUS
Hashtable< Integer, GlgPoint > FanSpeedColorSTATUS
Hashtable< Integer, String > FanSpeedSTATUS
Hashtable< Integer, String > FanSTATUS
Hashtable< Integer, GlgPoint > IonicONOFFColorSTATUS
Hashtable< Integer, String > IonicONOFFSTATUS
Hashtable< Integer, GlgPoint > IonicOperatingModeColorSTATUS
Hashtable< Integer, String > IonicOperatingModeSTATUS
Hashtable< Integer, GlgPoint > IonicRemoteColorSTATUS
Hashtable< Integer, String > IonicRemoteSTATUS
Hashtable< Integer, GlgPoint > IonicVoltageModeColorSTATUS
Hashtable< Integer, String > IonicVoltageModeSTATUS
Hashtable< Integer, GlgPoint > IPSColorSTATUS
Hashtable< Integer, String > IPSSTATUS
String mainDrawing = "PCOUNTER.g"
Hashtable< Integer, GlgPoint > OkFailColorSTATUS
Hashtable< Integer, String > OkFailSTATUS
Hashtable< String, String > PCOUNTER2CMD
Hashtable< String, String > PCOUNTER2STATUS
Hashtable< String, String > PCOUNTERCMD
Hashtable< Integer, GlgPoint > PCounterColorINSTRSTATUS
Hashtable< Integer, GlgPoint > PCounterColorSTATUS
Hashtable< Integer, String > PCounterINSTRSTATUS
Hashtable< String, String > PCOUNTERSTATUS
Hashtable< Integer, String > PCounterSTATUS
Hashtable< String, String > PCounterStatusDetails
Hashtable< String, String > PCounterTemp
Hashtable< Integer, GlgPoint > PumpColorSTATUS
Hashtable< Integer, String > PumpSTATUS
Hashtable< Integer, GlgPoint > RearmColorSTATUS
Hashtable< Integer, String > RearmSTATUS
Hashtable< Integer, GlgPoint > RelayGeneralColorSTATUS
Hashtable< Integer, String > RelayGeneralSTATUS
Hashtable< Integer, String > RGADegasONOFFSTATUS
Hashtable< Integer, String > RGAEmissionONOFFSTATUS
Hashtable< Integer, GlgPoint > RGAFilamentColorSTATUS
Hashtable< Integer, String > RGAFilamentSTATUS
Hashtable< Integer, String > RGAMODESTATUS
Hashtable< Integer, GlgPoint > RGAONOFFColorSTATUS
Hashtable< Integer, String > RGAOperationONOFFSTATUS
Hashtable< Integer, String > RGARunningONOFFSTATUS
Hashtable< Integer, GlgPoint > TitaneAutoStartModeColorSTATUS
Hashtable< Integer, String > TitaneAutoStartModeSTATUS
Hashtable< Integer, GlgPoint > TitaneControllerColorSTATUS
Hashtable< Integer, GlgPoint > TitaneControllerOperatingModeColorSTATUS
Hashtable< Integer, String > TitaneControllerOperatingModeSTATUS
Hashtable< Integer, String > TitaneControllerSTATUS
Hashtable< Integer, GlgPoint > TitaneErrorColorSTATUS
Hashtable< Integer, String > TitaneErrorSTATUS
Hashtable< Integer, GlgPoint > TitaneFilamentColorSTATUS
Hashtable< Integer, String > TitaneFilamentSTATUS
Hashtable< Integer, GlgPoint > TitaneOperatingModeColorSTATUS
Hashtable< Integer, String > TitaneOperatingModeSTATUS
Hashtable< Integer, GlgPoint > TitaneRecoverModeColorSTATUS
Hashtable< Integer, String > TitaneRecoverModeSTATUS
Hashtable< Integer, GlgPoint > TitaneRemoteColorSTATUS
Hashtable< Integer, String > TitaneRemoteSTATUS
Hashtable< Integer, GlgPoint > TitaneStartColorSTATUS
Hashtable< Integer, String > TitaneStartSTATUS
Hashtable< Integer, GlgPoint > Turbo1ErrorColorSTATUS
Hashtable< Integer, String > Turbo1ErrorSTATUS
Hashtable< Integer, GlgPoint > Turbo2ErrorColorSTATUS
Hashtable< Integer, String > Turbo2ErrorSTATUS
Hashtable< Integer, GlgPoint > TurboONOFFColorSTATUS
Hashtable< Integer, String > TurboONOFFSTATUS
Hashtable< Integer, GlgPoint > TurboStandbyColorSTATUS
Hashtable< Integer, String > TurboStandbySTATUS
Hashtable< Integer, GlgPoint > TurboTemperatureBoxColorSTATUS
Hashtable< Integer, String > TurboTemperatureBoxSTATUS
Hashtable< Integer, GlgPoint > TurboTemperatureColorSTATUS
Hashtable< Integer, String > TurboTemperatureSTATUS
Hashtable< Integer, GlgPoint > ValveColorSTATUS
Hashtable< Integer, String > ValveSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeDegasColorSTATUS
Hashtable< Integer, String > XGSGaugeDegasSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeEmissionColorSTATUS
Hashtable< Integer, String > XGSGaugeEmissionSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeFilamentColorSTATUS
Hashtable< Integer, String > XGSGaugeFilamentSTATUS
Protected Attributes inherited from GlgChildGui
Hashtable< String, String > CMD = new Hashtable < String, String > ()
Container content
DeviceManager deviceManager
GlgJLWBean glg_bean
String glgdrawing
Operation op
String origin
boolean showParent = false
Hashtable< String, String > STATUS = new Hashtable < String, String > ()
String title
Detailed Description
Definition at line 17 of file GlgPCounter2Gui.java.
Constructor & Destructor Documentation
GlgPCounter2Gui()
GlgPCounter2Gui.GlgPCounter2Gui (GlgGui _parent, Operation _op, String _title, String _origin)
Definition at line 22 of file GlgPCounter2Gui.java.
Member Function Documentation
createAndShowGui()
void GlgPCounter2Gui.createAndShowGui () protected
Reimplemented from GlgChildGui.
Definition at line 26 of file GlgPCounter2Gui.java.
References Device.aliasName, GlgChildGui.CMD, GlgChildGui.content, createCommandMap(), createStatusMap(), GlgChildGui.deviceManager, GlgChildGui.glg_bean, logger, GlgChildGui.STATUS, and GlgChildGui.title.
createCommandMap()
void GlgPCounter2Gui.createCommandMap (Hashtable< String, String > CMD)
Reimplemented from GlgChildGui.
Definition at line 51 of file GlgPCounter2Gui.java.
References GlgChildGui.CMD, and ChannelList.PCOUNTER2CMD.
Referenced by createAndShowGui().
createStatusMap()
void GlgPCounter2Gui.createStatusMap (Hashtable< String, String > STATUS)
Reimplemented from GlgChildGui.
Definition at line 57 of file GlgPCounter2Gui.java.
References ChannelList.PCOUNTER2STATUS, and GlgChildGui.STATUS.
Referenced by createAndShowGui().
updateGuiFeatures()
void GlgPCounter2Gui.updateGuiFeatures (String glgName, DataElement dataElement) protected
Reimplemented from GlgChildGui.
Definition at line 64 of file GlgPCounter2Gui.java.
References GlgChildGui.glg_bean, logger, DataElement.name, ChannelList.OkFailColorSTATUS, ChannelList.OkFailSTATUS, ChannelList.PCounterColorINSTRSTATUS, ChannelList.PCounterColorSTATUS, ChannelList.PCounterINSTRSTATUS, ChannelList.PCounterSTATUS, DataElement.type, and DataElement.value.
Member Data Documentation
logger
final Logger GlgPCounter2Gui.logger = Logger.getLogger("Main") static private
Definition at line 20 of file GlgPCounter2Gui.java.
Referenced by createAndShowGui(), GlgPCounter2Gui.InputListener.InputCallback(), and updateGuiFeatures().
serialVersionUID
final long GlgPCounter2Gui.serialVersionUID = 354054054072L static private
Definition at line 19 of file GlgPCounter2Gui.java.
The documentation for this class was generated from the following file:
work_pcounter/GlgPCounter2Gui.java