SCADARPI API (work_pcounter): PCounterMasterRTU Class Reference
PCounterMasterRTU Class Reference
Public Member Functions
void executeCommand (DataElement e)
PCounterMasterRTU (String _name, String _aliasName, int _mbRegisterStart, String _serial_port, SerialPort.BaudRate _baudrate, int _databits, SerialPort.Parity _parity, int _stopbits)
void setErrorComStatus ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void doStart ()
void doStop ()
void popCommand ()
void run ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
Private Member Functions
String getConfigFilePath ()
Private Attributes
SerialPort.BaudRate baudrate
int databits
ModbusMaster master
SerialPort.Parity parity
String serial_port
int slaveId = 247
int stopbits
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
final Lock modbusmutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int sleep_period = 1000
boolean use_i2c_out = false
Detailed Description
Definition at line 23 of file PCounterMasterRTU.java.
Constructor & Destructor Documentation
PCounterMasterRTU()
PCounterMasterRTU.PCounterMasterRTU (String _name, String _aliasName, int _mbRegisterStart, String _serial_port, SerialPort.BaudRate _baudrate, int _databits, SerialPort.Parity _parity, int _stopbits)
Definition at line 44 of file PCounterMasterRTU.java.
References DataManager.addDataElement(), Device.aliasName, baudrate, DataTypes.DataType.COM_STATUS, Device.comm_max_failure, databits, DataTypes.RegisterType.FLOAT32, getConfigFilePath(), DataManager.getDataElement(), Device.hasWarned, DataTypes.RegisterType.INT16, DataTypes.RegisterType.INT32, logger, master, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, DataElement.name, Device.name, parity, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, serial_port, Device.sleep_period, stopbits, DataTypes.DataType.TRIGGER, and DataElement.value.
Member Function Documentation
executeCommand()
void PCounterMasterRTU.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 351 of file PCounterMasterRTU.java.
References getConfigFilePath(), DataManager.holdingRegisters, logger, master, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, slaveId, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
getConfigFilePath()
String PCounterMasterRTU.getConfigFilePath () private
Definition at line 34 of file PCounterMasterRTU.java.
References Device.name.
Referenced by executeCommand(), and PCounterMasterRTU().
setErrorComStatus()
void PCounterMasterRTU.setErrorComStatus ()
Reimplemented from Device.
Definition at line 189 of file PCounterMasterRTU.java.
References DataTypes.DataType.COM_STATUS, Device.hasWarned, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
Referenced by updateDeviceData().
updateDeviceData()
void PCounterMasterRTU.updateDeviceData ()
Reimplemented from Device.
Definition at line 208 of file PCounterMasterRTU.java.
References Device.comm_cnt_failure, Device.comm_max_failure, DataManager.getDataElement(), Device.hasWarned, logger, master, Device.name, Device.popCommand(), setErrorComStatus(), slaveId, and DataElement.value.
Member Data Documentation
baudrate
SerialPort.BaudRate PCounterMasterRTU.baudrate private
Definition at line 28 of file PCounterMasterRTU.java.
Referenced by PCounterMasterRTU().
databits
int PCounterMasterRTU.databits private
Definition at line 29 of file PCounterMasterRTU.java.
Referenced by PCounterMasterRTU().
logger
final Logger PCounterMasterRTU.logger = Logger.getLogger("Main") static private
Definition at line 25 of file PCounterMasterRTU.java.
Referenced by executeCommand(), PCounterMasterRTU(), and updateDeviceData().
master
ModbusMaster PCounterMasterRTU.master private
Definition at line 26 of file PCounterMasterRTU.java.
Referenced by executeCommand(), PCounterMasterRTU(), and updateDeviceData().
parity
SerialPort.Parity PCounterMasterRTU.parity private
Definition at line 30 of file PCounterMasterRTU.java.
Referenced by PCounterMasterRTU().
serial_port
String PCounterMasterRTU.serial_port private
Definition at line 32 of file PCounterMasterRTU.java.
Referenced by PCounterMasterRTU().
slaveId
int PCounterMasterRTU.slaveId = 247 private
Definition at line 27 of file PCounterMasterRTU.java.
Referenced by executeCommand(), and updateDeviceData().
stopbits
int PCounterMasterRTU.stopbits private
Definition at line 31 of file PCounterMasterRTU.java.
Referenced by PCounterMasterRTU().
The documentation for this class was generated from the following file:
work_pcounter/PCounterMasterRTU.java