SCADARPI API (work_rga): RgaHidenHal201RC Class Reference
RgaHidenHal201RC Class Reference
Public Member Functions
void executeCommand (DataElement e)
RgaHidenHal201RC (String _name, int _amuMax, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void doStart ()
void doStop ()
void popCommand ()
void run ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
Public Attributes
int amuMax
Public Attributes inherited from Device
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
final Lock modbusmutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Private Member Functions
void GetAllParamsFromDevice () throws Exception
String getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException
void initDevice () throws Exception
void InitScanDevice () throws Exception
void resetDevice ()
void StartDegasDevice () throws Exception
void StopDegasDevice () throws Exception
void StopScanDevice () throws Exception
void UseFaraday () throws Exception
void UseFilament1 () throws Exception
void UseFilament2 () throws Exception
void UseSEM () throws Exception
Private Attributes
Baud baudrate
int channelPos = 0
DataBits databits
FlowControl flowcontrol
boolean isStarted = false
Parity parity
Serial_Comm rs232 = null
String serial_port
StopBits stopbits
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Additional Inherited Members
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int sleepPeriod = 1000
boolean use_i2c_out = false
Detailed Description
Definition at line 14 of file RgaHidenHal201RC.java.
Constructor & Destructor Documentation
RgaHidenHal201RC()
RgaHidenHal201RC.RgaHidenHal201RC (String _name, int _amuMax, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
Definition at line 28 of file RgaHidenHal201RC.java.
References DataManager.addDataElement(), amuMax, baudrate, DataTypes.DataType.COM_STATUS, databits, DataTypes.RegisterType.FLOAT32, flowcontrol, initDevice(), DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, parity, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, serial_port, Device.sleepPeriod, stopbits, and DataTypes.DataType.TRIGGER.
Member Function Documentation
executeCommand()
void RgaHidenHal201RC.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 214 of file RgaHidenHal201RC.java.
References GetAllParamsFromDevice(), getAnswerFromDevice(), DataManager.getDataElement(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, DataElement.setvalue, StartDegasDevice(), StopDegasDevice(), StopScanDevice(), DataTypes.DataType.TRIGGER, DataElement.type, UseFaraday(), UseFilament1(), UseFilament2(), UseSEM(), and DataElement.value.
Referenced by resetDevice().
GetAllParamsFromDevice()
void RgaHidenHal201RC.GetAllParamsFromDevice () throws Exception private
Definition at line 485 of file RgaHidenHal201RC.java.
References getAnswerFromDevice(), DataManager.getDataElement(), logger, and DataElement.value.
Referenced by executeCommand(), initDevice(), StartDegasDevice(), and StopScanDevice().
getAnswerFromDevice()
String RgaHidenHal201RC.getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException private
Definition at line 436 of file RgaHidenHal201RC.java.
References Serial_Comm.BytesAvailable(), logger, Serial_Comm.Read(), rs232, and Serial_Comm.Write().
Referenced by executeCommand(), GetAllParamsFromDevice(), InitScanDevice(), StartDegasDevice(), StopDegasDevice(), StopScanDevice(), updateDeviceData(), UseFaraday(), UseFilament1(), UseFilament2(), and UseSEM().
initDevice()
void RgaHidenHal201RC.initDevice () throws Exception private
Definition at line 455 of file RgaHidenHal201RC.java.
References baudrate, databits, flowcontrol, GetAllParamsFromDevice(), logger, Serial_Comm.Open(), parity, rs232, serial_port, and stopbits.
Referenced by RgaHidenHal201RC().
InitScanDevice()
void RgaHidenHal201RC.InitScanDevice () throws Exception private
Definition at line 560 of file RgaHidenHal201RC.java.
References amuMax, getAnswerFromDevice(), and logger.
Referenced by updateDeviceData().
resetDevice()
void RgaHidenHal201RC.resetDevice () private
Definition at line 476 of file RgaHidenHal201RC.java.
References executeCommand(), DataManager.getDataElement(), and DataElement.value.
Referenced by updateDeviceData().
StartDegasDevice()
void RgaHidenHal201RC.StartDegasDevice () throws Exception private
Definition at line 631 of file RgaHidenHal201RC.java.
References GetAllParamsFromDevice(), getAnswerFromDevice(), and StopScanDevice().
Referenced by executeCommand().
StopDegasDevice()
void RgaHidenHal201RC.StopDegasDevice () throws Exception private
Definition at line 645 of file RgaHidenHal201RC.java.
References getAnswerFromDevice().
Referenced by executeCommand().
StopScanDevice()
void RgaHidenHal201RC.StopScanDevice () throws Exception private
Definition at line 603 of file RgaHidenHal201RC.java.
References amuMax, GetAllParamsFromDevice(), getAnswerFromDevice(), DataManager.getDataElement(), logger, and DataElement.value.
Referenced by executeCommand(), and StartDegasDevice().
updateDeviceData()
void RgaHidenHal201RC.updateDeviceData ()
Reimplemented from Device.
Definition at line 102 of file RgaHidenHal201RC.java.
References channelPos, getAnswerFromDevice(), DataManager.getDataElement(), Device.hasWarned, InitScanDevice(), isStarted, logger, Device.name, Device.popCommand(), resetDevice(), Device.setErrorComStatus(), and DataElement.value.
UseFaraday()
void RgaHidenHal201RC.UseFaraday () throws Exception private
Definition at line 664 of file RgaHidenHal201RC.java.
References getAnswerFromDevice().
Referenced by executeCommand().
UseFilament1()
void RgaHidenHal201RC.UseFilament1 () throws Exception private
Definition at line 652 of file RgaHidenHal201RC.java.
References getAnswerFromDevice().
Referenced by executeCommand().
UseFilament2()
void RgaHidenHal201RC.UseFilament2 () throws Exception private
Definition at line 658 of file RgaHidenHal201RC.java.
References getAnswerFromDevice().
Referenced by executeCommand().
UseSEM()
void RgaHidenHal201RC.UseSEM () throws Exception private
Definition at line 669 of file RgaHidenHal201RC.java.
References getAnswerFromDevice().
Referenced by executeCommand().
Member Data Documentation
amuMax
int RgaHidenHal201RC.amuMax
Definition at line 26 of file RgaHidenHal201RC.java.
Referenced by GlgRGA3Gui.createAndShowGui(), InitScanDevice(), RgaHidenHal201RC(), and StopScanDevice().
baudrate
Baud RgaHidenHal201RC.baudrate private
Definition at line 21 of file RgaHidenHal201RC.java.
Referenced by initDevice(), and RgaHidenHal201RC().
channelPos
int RgaHidenHal201RC.channelPos = 0 private
Definition at line 19 of file RgaHidenHal201RC.java.
Referenced by updateDeviceData().
databits
DataBits RgaHidenHal201RC.databits private
Definition at line 22 of file RgaHidenHal201RC.java.
Referenced by initDevice(), and RgaHidenHal201RC().
flowcontrol
FlowControl RgaHidenHal201RC.flowcontrol private
Definition at line 25 of file RgaHidenHal201RC.java.
Referenced by initDevice(), and RgaHidenHal201RC().
isStarted
boolean RgaHidenHal201RC.isStarted = false private
Definition at line 18 of file RgaHidenHal201RC.java.
Referenced by updateDeviceData().
logger
final Logger RgaHidenHal201RC.logger = Logger.getLogger("Main") static private
Definition at line 17 of file RgaHidenHal201RC.java.
Referenced by executeCommand(), GetAllParamsFromDevice(), getAnswerFromDevice(), initDevice(), InitScanDevice(), RgaHidenHal201RC(), StopScanDevice(), and updateDeviceData().
parity
Parity RgaHidenHal201RC.parity private
Definition at line 23 of file RgaHidenHal201RC.java.
Referenced by initDevice(), and RgaHidenHal201RC().
rs232
Serial_Comm RgaHidenHal201RC.rs232 = null private
Definition at line 16 of file RgaHidenHal201RC.java.
Referenced by getAnswerFromDevice(), and initDevice().
serial_port
String RgaHidenHal201RC.serial_port private
Definition at line 20 of file RgaHidenHal201RC.java.
Referenced by initDevice(), and RgaHidenHal201RC().
stopbits
StopBits RgaHidenHal201RC.stopbits private
Definition at line 24 of file RgaHidenHal201RC.java.
Referenced by initDevice(), and RgaHidenHal201RC().
The documentation for this class was generated from the following file:
work_rga/RgaHidenHal201RC.java