var annotated_dup =
[
    [ "ChannelList", "interfaceChannelList.html", "interfaceChannelList" ],
    [ "Controllino_1", "classControllino__1.html", "classControllino__1" ],
    [ "Controllino_2", "classControllino__2.html", "classControllino__2" ],
    [ "DataElement", "classDataElement.html", "classDataElement" ],
    [ "DataManager", "classDataManager.html", "classDataManager" ],
    [ "DataTypes", "interfaceDataTypes.html", [
      [ "DataType", "enumDataTypes_1_1DataType.html", "enumDataTypes_1_1DataType" ],
      [ "OpMode", "enumDataTypes_1_1OpMode.html", "enumDataTypes_1_1OpMode" ],
      [ "RegisterType", "enumDataTypes_1_1RegisterType.html", "enumDataTypes_1_1RegisterType" ]
    ] ],
    [ "Device", "classDevice.html", "classDevice" ],
    [ "DeviceManager", "classDeviceManager.html", "classDeviceManager" ],
    [ "DialogOp", "classDialogOp.html", "classDialogOp" ],
    [ "DialogSetPoint", "classDialogSetPoint.html", "classDialogSetPoint" ],
    [ "DialogStart", "classDialogStart.html", "classDialogStart" ],
    [ "DialogStop", "classDialogStop.html", "classDialogStop" ],
    [ "GlgChildGui", "classGlgChildGui.html", "classGlgChildGui" ],
    [ "GlgDryGui", "classGlgDryGui.html", "classGlgDryGui" ],
    [ "GlgGaugeGui", "classGlgGaugeGui.html", "classGlgGaugeGui" ],
    [ "GlgGui", "classGlgGui.html", "classGlgGui" ],
    [ "GlgIonicGui", "classGlgIonicGui.html", "classGlgIonicGui" ],
    [ "GlgRGA3Gui", "classGlgRGA3Gui.html", "classGlgRGA3Gui" ],
    [ "GlgTCMuxTempGui", "classGlgTCMuxTempGui.html", "classGlgTCMuxTempGui" ],
    [ "GlgTitane_22Gui", "classGlgTitane__22Gui.html", "classGlgTitane__22Gui" ],
    [ "GlgTitane_32Gui", "classGlgTitane__32Gui.html", "classGlgTitane__32Gui" ],
    [ "GlgTube1500wStatusDetailsGui", "classGlgTube1500wStatusDetailsGui.html", "classGlgTube1500wStatusDetailsGui" ],
    [ "GlgTurboGui", "classGlgTurboGui.html", "classGlgTurboGui" ],
    [ "GlgValveGui", "classGlgValveGui.html", "classGlgValveGui" ],
    [ "GlgXGSGaugeGui", "classGlgXGSGaugeGui.html", "classGlgXGSGaugeGui" ],
    [ "I2C_Comm", "classI2C__Comm.html", "classI2C__Comm" ],
    [ "Main", "classMain.html", "classMain" ],
    [ "MaxiGauge", "classMaxiGauge.html", "classMaxiGauge" ],
    [ "MksRotor", "classMksRotor.html", "classMksRotor" ],
    [ "ModbusSlaveThread", "classModbusSlaveThread.html", "classModbusSlaveThread" ],
    [ "Operation", "classOperation.html", "classOperation" ],
    [ "RoundedBorder", "classRoundedBorder.html", "classRoundedBorder" ],
    [ "RoundJTextField", "classRoundJTextField.html", "classRoundJTextField" ],
    [ "Serial_Comm", "classSerial__Comm.html", "classSerial__Comm" ],
    [ "Sicem", "classSicem.html", "classSicem" ],
    [ "TCMuxShield", "classTCMuxShield.html", "classTCMuxShield" ],
    [ "TurboPfeifferDCU", "classTurboPfeifferDCU.html", "classTurboPfeifferDCU" ],
    [ "XGSGauge", "classXGSGauge.html", "classXGSGauge" ]
];