SCADARPI API (work_tube1500w): DialogStop Class Reference
DialogStop Class Reference
Public Member Functions
DialogStop (JFrame _parent, String _title, boolean _modal)
void doStart ()
void doStop ()
void run ()
Protected Member Functions
URLConnection getServerConnection (String url) throws MalformedURLException, IOException
A connection method called every time a connection to the servlet is needed.
void processWindowEvent (WindowEvent e)
Private Member Functions
void SendCommandToSupervisor (String command)
void StopScan ()
Private Attributes
JLabel jLabelText = new JLabel()
JPanel panel
JFrame parent
Thread thread
String title
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 46 of file DialogStop.java.
Constructor & Destructor Documentation
DialogStop()
DialogStop.DialogStop (JFrame _parent, String _title, boolean _modal)
Definition at line 54 of file DialogStop.java.
References doStart(), parent, and title.
Member Function Documentation
doStart()
void DialogStop.doStart ()
Definition at line 69 of file DialogStop.java.
References thread.
Referenced by DialogStop().
doStop()
void DialogStop.doStop ()
Definition at line 74 of file DialogStop.java.
References thread.
getServerConnection()
URLConnection DialogStop.getServerConnection (String url) throws MalformedURLException, IOException protected
A connection method called every time a connection to the servlet is needed.
The servlet path points to "jchv" which contains the main servlet for channel visualization.
Definition at line 136 of file DialogStop.java.
Referenced by SendCommandToSupervisor().
processWindowEvent()
void DialogStop.processWindowEvent (WindowEvent e) protected
Definition at line 150 of file DialogStop.java.
run()
void DialogStop.run ()
Definition at line 105 of file DialogStop.java.
References logger, and StopScan().
SendCommandToSupervisor()
void DialogStop.SendCommandToSupervisor (String command) private
Definition at line 164 of file DialogStop.java.
References getServerConnection(), and logger.
Referenced by StopScan().
StopScan()
void DialogStop.StopScan () private
Definition at line 116 of file DialogStop.java.
References SendCommandToSupervisor().
Referenced by run().
Member Data Documentation
jLabelText
JLabel DialogStop.jLabelText = new JLabel() private
Definition at line 49 of file DialogStop.java.
logger
final Logger DialogStop.logger = Logger.getLogger("Main") static private
Definition at line 47 of file DialogStop.java.
Referenced by run(), and SendCommandToSupervisor().
panel
JPanel DialogStop.panel private
Definition at line 48 of file DialogStop.java.
parent
JFrame DialogStop.parent private
Definition at line 50 of file DialogStop.java.
Referenced by DialogStop().
thread
Thread DialogStop.thread private
Definition at line 52 of file DialogStop.java.
Referenced by doStart(), and doStop().
title
String DialogStop.title private
Definition at line 51 of file DialogStop.java.
Referenced by DialogStop().
The documentation for this class was generated from the following file:
work_tube1500w/DialogStop.java