SCADARPI API (work_tube1500w): DialogStart Class Reference
DialogStart Class Reference
Public Member Functions
DialogStart (JFrame _parent, String _title, boolean _modal)
void doStart ()
void doStop ()
void run ()
Protected Member Functions
URLConnection getServerConnection (String url) throws MalformedURLException, IOException
A connection method called every time a connection to the servlet is needed.
void processWindowEvent (WindowEvent e)
Private Member Functions
void SendCommandToSupervisor (String command)
void StartScan ()
Private Attributes
JLabel jLabelText = new JLabel()
JPanel panel
JFrame parent
Thread thread
String title
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 46 of file DialogStart.java.
Constructor & Destructor Documentation
DialogStart()
DialogStart.DialogStart (JFrame _parent, String _title, boolean _modal)
Definition at line 54 of file DialogStart.java.
References doStart(), parent, and title.
Member Function Documentation
doStart()
void DialogStart.doStart ()
Definition at line 69 of file DialogStart.java.
References thread.
Referenced by DialogStart().
doStop()
void DialogStart.doStop ()
Definition at line 74 of file DialogStart.java.
References thread.
getServerConnection()
URLConnection DialogStart.getServerConnection (String url) throws MalformedURLException, IOException protected
A connection method called every time a connection to the servlet is needed.
The servlet path points to "jchv" which contains the main servlet for channel visualization.
Definition at line 136 of file DialogStart.java.
Referenced by SendCommandToSupervisor().
processWindowEvent()
void DialogStart.processWindowEvent (WindowEvent e) protected
Definition at line 150 of file DialogStart.java.
run()
void DialogStart.run ()
Definition at line 106 of file DialogStart.java.
References logger, and StartScan().
SendCommandToSupervisor()
void DialogStart.SendCommandToSupervisor (String command) private
Definition at line 164 of file DialogStart.java.
References getServerConnection(), and logger.
Referenced by StartScan().
StartScan()
void DialogStart.StartScan () private
Definition at line 117 of file DialogStart.java.
References SendCommandToSupervisor().
Referenced by run().
Member Data Documentation
jLabelText
JLabel DialogStart.jLabelText = new JLabel() private
Definition at line 49 of file DialogStart.java.
logger
final Logger DialogStart.logger = Logger.getLogger("Main") static private
Definition at line 47 of file DialogStart.java.
Referenced by run(), and SendCommandToSupervisor().
panel
JPanel DialogStart.panel private
Definition at line 48 of file DialogStart.java.
parent
JFrame DialogStart.parent private
Definition at line 50 of file DialogStart.java.
Referenced by DialogStart().
thread
Thread DialogStart.thread private
Definition at line 52 of file DialogStart.java.
Referenced by doStart(), and doStop().
title
String DialogStart.title private
Definition at line 51 of file DialogStart.java.
Referenced by DialogStart().
The documentation for this class was generated from the following file:
work_tube1500w/DialogStart.java