SCADARPI API (work_link): ModbusSlaveThread Class Reference
ModbusSlaveThread Class Reference
Classes
interface ModbusEventListener
class ModbusSlaveDataHolder
Public Member Functions
void configureRegistersFromAllDevice (ModbusHoldingRegisters holdingRegisters)
void doStart ()
void doStop ()
ModbusSlaveThread (DeviceManager _deviceManager)
void run ()
Private Attributes
DeviceManager deviceManager
ModbusSlaveTCP slave
Thread thread
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 36 of file ModbusSlaveThread.java.
Constructor & Destructor Documentation
ModbusSlaveThread()
ModbusSlaveThread.ModbusSlaveThread (DeviceManager _deviceManager)
Definition at line 43 of file ModbusSlaveThread.java.
References ModbusSlaveThread.ModbusSlaveDataHolder.addEventListener(), deviceManager, logger, and slave.
Member Function Documentation
configureRegistersFromAllDevice()
void ModbusSlaveThread.configureRegistersFromAllDevice (ModbusHoldingRegisters holdingRegisters)
Definition at line 133 of file ModbusSlaveThread.java.
References DeviceManager.deviceList, deviceManager, logger, DataElement.mbRegisterLength, DataElement.mbRegisterOffset, DataElement.mbRegisterType, and DataElement.name.
Referenced by ModbusSlaveThread.ModbusSlaveDataHolder.ModbusSlaveDataHolder().
doStart()
void ModbusSlaveThread.doStart ()
Definition at line 122 of file ModbusSlaveThread.java.
References thread.
Referenced by Main.main().
doStop()
void ModbusSlaveThread.doStop ()
Definition at line 127 of file ModbusSlaveThread.java.
References thread.
run()
void ModbusSlaveThread.run ()
Definition at line 173 of file ModbusSlaveThread.java.
References logger, and slave.
Member Data Documentation
deviceManager
DeviceManager ModbusSlaveThread.deviceManager private
Definition at line 39 of file ModbusSlaveThread.java.
Referenced by configureRegistersFromAllDevice(), ModbusSlaveThread.ModbusSlaveDataHolder.ModbusSlaveDataHolder(), ModbusSlaveThread(), and ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegister().
logger
final Logger ModbusSlaveThread.logger = Logger.getLogger("Main") static private
Definition at line 38 of file ModbusSlaveThread.java.
Referenced by configureRegistersFromAllDevice(), ModbusSlaveThread.ModbusSlaveDataHolder.ModbusSlaveDataHolder(), ModbusSlaveThread(), run(), and ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegister().
slave
ModbusSlaveTCP ModbusSlaveThread.slave private
Definition at line 40 of file ModbusSlaveThread.java.
Referenced by ModbusSlaveThread(), and run().
thread
Thread ModbusSlaveThread.thread private
Definition at line 41 of file ModbusSlaveThread.java.
Referenced by doStart(), and doStop().
The documentation for this class was generated from the following file:
work_link/ModbusSlaveThread.java