var annotated_dup =
[
    [ "ChannelList", "interfaceChannelList.html", "interfaceChannelList" ],
    [ "Controllino_1", "classControllino__1.html", "classControllino__1" ],
    [ "Controllino_2", "classControllino__2.html", "classControllino__2" ],
    [ "Controllino_3", "classControllino__3.html", "classControllino__3" ],
    [ "DataElement", "classDataElement.html", "classDataElement" ],
    [ "DataManager", "classDataManager.html", "classDataManager" ],
    [ "DataTypes", "interfaceDataTypes.html", [
      [ "DataType", "enumDataTypes_1_1DataType.html", "enumDataTypes_1_1DataType" ],
      [ "RegisterType", "enumDataTypes_1_1RegisterType.html", "enumDataTypes_1_1RegisterType" ]
    ] ],
    [ "Device", "classDevice.html", "classDevice" ],
    [ "DeviceManager", "classDeviceManager.html", "classDeviceManager" ],
    [ "DialogSetPoint", "classDialogSetPoint.html", "classDialogSetPoint" ],
    [ "GlgChildGui", "classGlgChildGui.html", "classGlgChildGui" ],
    [ "GlgDryGui", "classGlgDryGui.html", "classGlgDryGui" ],
    [ "GlgGaugeGui", "classGlgGaugeGui.html", "classGlgGaugeGui" ],
    [ "GlgGui", "classGlgGui.html", "classGlgGui" ],
    [ "GlgIonicGui", "classGlgIonicGui.html", "classGlgIonicGui" ],
    [ "GlgRGAGui", "classGlgRGAGui.html", "classGlgRGAGui" ],
    [ "GlgSqzStatusDetailsGui", "classGlgSqzStatusDetailsGui.html", "classGlgSqzStatusDetailsGui" ],
    [ "GlgSqzTempGui", "classGlgSqzTempGui.html", "classGlgSqzTempGui" ],
    [ "GlgTitane_22Gui", "classGlgTitane__22Gui.html", "classGlgTitane__22Gui" ],
    [ "GlgTitane_32Gui", "classGlgTitane__32Gui.html", "classGlgTitane__32Gui" ],
    [ "GlgTurboGui", "classGlgTurboGui.html", "classGlgTurboGui" ],
    [ "GlgValveGui", "classGlgValveGui.html", "classGlgValveGui" ],
    [ "GlgXGSGaugeGui", "classGlgXGSGaugeGui.html", "classGlgXGSGaugeGui" ],
    [ "I2C_Comm", "classI2C__Comm.html", "classI2C__Comm" ],
    [ "Main", "classMain.html", "classMain" ],
    [ "MaxiGauge", "classMaxiGauge.html", "classMaxiGauge" ],
    [ "ModbusSlaveThread", "classModbusSlaveThread.html", "classModbusSlaveThread" ],
    [ "RgaPfeifferQms200", "classRgaPfeifferQms200.html", "classRgaPfeifferQms200" ],
    [ "RoundedBorder", "classRoundedBorder.html", "classRoundedBorder" ],
    [ "RoundJTextField", "classRoundJTextField.html", "classRoundJTextField" ],
    [ "Serial_Comm", "classSerial__Comm.html", "classSerial__Comm" ],
    [ "TCMuxShield", "classTCMuxShield.html", "classTCMuxShield" ],
    [ "TurboPfeifferDCU", "classTurboPfeifferDCU.html", "classTurboPfeifferDCU" ]
];