var annotated_dup =
[
    [ "ChannelList", "interfaceChannelList.html", "interfaceChannelList" ],
    [ "Controllino_1", "classControllino__1.html", "classControllino__1" ],
    [ "DataElement", "classDataElement.html", "classDataElement" ],
    [ "DataManager", "classDataManager.html", "classDataManager" ],
    [ "DataTypes", "interfaceDataTypes.html", [
      [ "DataType", "enumDataTypes_1_1DataType.html", "enumDataTypes_1_1DataType" ],
      [ "OpMode", "enumDataTypes_1_1OpMode.html", "enumDataTypes_1_1OpMode" ],
      [ "RegisterType", "enumDataTypes_1_1RegisterType.html", "enumDataTypes_1_1RegisterType" ]
    ] ],
    [ "Device", "classDevice.html", "classDevice" ],
    [ "DeviceManager", "classDeviceManager.html", "classDeviceManager" ],
    [ "DialogOp", "classDialogOp.html", "classDialogOp" ],
    [ "DialogSetPoint", "classDialogSetPoint.html", "classDialogSetPoint" ],
    [ "FlowMeterModbusMaster", "classFlowMeterModbusMaster.html", "classFlowMeterModbusMaster" ],
    [ "GlgChildGui", "classGlgChildGui.html", "classGlgChildGui" ],
    [ "GlgDryGui", "classGlgDryGui.html", "classGlgDryGui" ],
    [ "GlgFlowMeterGui", "classGlgFlowMeterGui.html", "classGlgFlowMeterGui" ],
    [ "GlgGaugeGui", "classGlgGaugeGui.html", "classGlgGaugeGui" ],
    [ "GlgGui", "classGlgGui.html", "classGlgGui" ],
    [ "GlgValveGui", "classGlgValveGui.html", "classGlgValveGui" ],
    [ "I2C_Comm", "classI2C__Comm.html", "classI2C__Comm" ],
    [ "Main", "classMain.html", "classMain" ],
    [ "MaxiGauge", "classMaxiGauge.html", "classMaxiGauge" ],
    [ "ModbusSlaveThread", "classModbusSlaveThread.html", "classModbusSlaveThread" ],
    [ "Operation", "classOperation.html", "classOperation" ],
    [ "RoundedBorder", "classRoundedBorder.html", "classRoundedBorder" ],
    [ "RoundJTextField", "classRoundJTextField.html", "classRoundJTextField" ],
    [ "Serial_Comm", "classSerial__Comm.html", "classSerial__Comm" ],
    [ "VentingLookAndFeel", "classVentingLookAndFeel.html", "classVentingLookAndFeel" ],
    [ "VentingOperationController", "classVentingOperationController.html", "classVentingOperationController" ],
    [ "VentingOperations", "classVentingOperations.html", "classVentingOperations" ],
    [ "VentingTableView", "classVentingTableView.html", "classVentingTableView" ]
];