SCADARPI API (work_venting): VentingLookAndFeel Class Reference
VentingLookAndFeel Class Reference
Centralizes all cosmetic / look & feel aspects of the venting table: fonts, borders, highlight, combo editor, frame colors, etc.
Classes
class HighlightRenderer
Renderer that colors the active step row based on table client property.
class ScientificRenderer
class TouchComboEditor
Touch-friendly combo editor (moved out of GlgGui).
Static Public Member Functions
static void applyTableBackground (JTable table)
static void clearActiveRow (JTable table)
static JPanel createFramedPanel (JComponent inner)
static JLabel createTitleLabel (String text)
static void installEditors (JTable table)
Install touch-friendly combo editors for pump/valves.
static void packTableColumns (JTable table)
Simple column auto-pack (for initial layout).
static void setActiveRow (JTable table, int rowIndex)
static void setFrameIdle (JPanel frame)
static void setFrameRunning (JPanel frame)
static void setFrameRunningPhase (JPanel frame, boolean strongPhase)
Used by the pulse timer to alternate between strong and soft states.
static void setFrameStopped (JPanel frame)
static void styleOperationsTable (JTable table)
Static Public Attributes
static final Color RUNNING_ORANGE_SOFT = new Color(255, 200, 120)
static final Color RUNNING_ORANGE_STRONG = new Color(255, 150, 0)
static final Color TABLE_BACKGROUND = new Color(140, 198, 198)
Private Member Functions
VentingLookAndFeel ()
Static Private Attributes
static final String ACTIVE_ROW_PROPERTY = "activeStepRow"
static final Color HIGHLIGHT_COLOR = new Color(255, 150, 0)
Detailed Description
Centralizes all cosmetic / look & feel aspects of the venting table: fonts, borders, highlight, combo editor, frame colors, etc.
Definition at line 13 of file VentingLookAndFeel.java.
Constructor & Destructor Documentation
VentingLookAndFeel()
VentingLookAndFeel.VentingLookAndFeel () private
Definition at line 21 of file VentingLookAndFeel.java.
Member Function Documentation
applyTableBackground()
static void VentingLookAndFeel.applyTableBackground (JTable table) static
Definition at line 204 of file VentingLookAndFeel.java.
References TABLE_BACKGROUND.
Referenced by VentingTableView.loadDbFromFile(), and VentingTableView.VentingTableView().
clearActiveRow()
static void VentingLookAndFeel.clearActiveRow (JTable table) static
Definition at line 168 of file VentingLookAndFeel.java.
References ACTIVE_ROW_PROPERTY.
Referenced by VentingTableView.startVentingSequence(), and VentingTableView.stopVentingSequence().
createFramedPanel()
static JPanel VentingLookAndFeel.createFramedPanel (JComponent inner) static
Definition at line 118 of file VentingLookAndFeel.java.
References setFrameIdle().
Referenced by VentingTableView.VentingTableView().
createTitleLabel()
static JLabel VentingLookAndFeel.createTitleLabel (String text) static
Definition at line 107 of file VentingLookAndFeel.java.
Referenced by VentingTableView.VentingTableView().
installEditors()
static void VentingLookAndFeel.installEditors (JTable table) static
Install touch-friendly combo editors for pump/valves.
Definition at line 79 of file VentingLookAndFeel.java.
Referenced by VentingTableView.loadDbFromFile(), and VentingTableView.VentingTableView().
packTableColumns()
static void VentingLookAndFeel.packTableColumns (JTable table) static
Simple column auto-pack (for initial layout).
Definition at line 55 of file VentingLookAndFeel.java.
Referenced by VentingTableView.loadDbFromFile(), and VentingTableView.VentingTableView().
setActiveRow()
static void VentingLookAndFeel.setActiveRow (JTable table, int rowIndex) static
Definition at line 162 of file VentingLookAndFeel.java.
References ACTIVE_ROW_PROPERTY.
Referenced by VentingOperations.highlightRow().
setFrameIdle()
static void VentingLookAndFeel.setFrameIdle (JPanel frame) static
Definition at line 125 of file VentingLookAndFeel.java.
Referenced by createFramedPanel(), setFrameStopped(), and VentingTableView.stopFramePulseAndReset().
setFrameRunning()
static void VentingLookAndFeel.setFrameRunning (JPanel frame) static
Definition at line 150 of file VentingLookAndFeel.java.
References setFrameRunningPhase().
setFrameRunningPhase()
static void VentingLookAndFeel.setFrameRunningPhase (JPanel frame, boolean strongPhase) static
Used by the pulse timer to alternate between strong and soft states.
Definition at line 136 of file VentingLookAndFeel.java.
References RUNNING_ORANGE_SOFT, and RUNNING_ORANGE_STRONG.
Referenced by setFrameRunning(), and VentingTableView.startFramePulse().
setFrameStopped()
static void VentingLookAndFeel.setFrameStopped (JPanel frame) static
Definition at line 155 of file VentingLookAndFeel.java.
References setFrameIdle().
Referenced by VentingTableView.stopVentingSequence().
styleOperationsTable()
static void VentingLookAndFeel.styleOperationsTable (JTable table) static
Definition at line 27 of file VentingLookAndFeel.java.
Referenced by VentingTableView.loadDbFromFile(), and VentingTableView.VentingTableView().
Member Data Documentation
ACTIVE_ROW_PROPERTY
final String VentingLookAndFeel.ACTIVE_ROW_PROPERTY = "activeStepRow" static private
Definition at line 16 of file VentingLookAndFeel.java.
Referenced by clearActiveRow(), VentingLookAndFeel.HighlightRenderer.getTableCellRendererComponent(), and setActiveRow().
HIGHLIGHT_COLOR
final Color VentingLookAndFeel.HIGHLIGHT_COLOR = new Color(255, 150, 0) static private
Definition at line 15 of file VentingLookAndFeel.java.
Referenced by VentingLookAndFeel.HighlightRenderer.getTableCellRendererComponent().
RUNNING_ORANGE_SOFT
final Color VentingLookAndFeel.RUNNING_ORANGE_SOFT = new Color(255, 200, 120) static
Definition at line 19 of file VentingLookAndFeel.java.
Referenced by setFrameRunningPhase().
RUNNING_ORANGE_STRONG
final Color VentingLookAndFeel.RUNNING_ORANGE_STRONG = new Color(255, 150, 0) static
Definition at line 18 of file VentingLookAndFeel.java.
Referenced by setFrameRunningPhase().
TABLE_BACKGROUND
final Color VentingLookAndFeel.TABLE_BACKGROUND = new Color(140, 198, 198) static
Definition at line 17 of file VentingLookAndFeel.java.
Referenced by applyTableBackground(), VentingLookAndFeel.HighlightRenderer.getTableCellRendererComponent(), and VentingTableView.VentingTableView().
The documentation for this class was generated from the following file:
work_venting/VentingLookAndFeel.java