SCADARPI API: VentingTableView Class Reference
VentingTableView Class Reference
Encapsulates the venting operations table, DB interactions, and control buttons (add/remove/update/load/execute/stop).
Public Member Functions
DefaultTableModel getModel ()
JPanel getPanel ()
JTable getTable ()
VentingTableView (JFrame ownerForDialogs, DeviceManager deviceManager, Hashtable< String, String > cmdMap, Hashtable< String, String > viewStatusMap, String dbUrl, String g2StatusKey, String mks2000StatusKey, String mks50000StatusKey)
Static Public Member Functions
static TableModel buildTableModel (int columnCount, ResultSet resultSet) throws SQLException
Private Member Functions
void addRow ()
void applyScientificRendererToG2 ()
void attachModelListener ()
void createDbIfNeeded ()
DefaultTableModel createEmptyModel ()
Object[] defaultRow (int step)
void deleteRowFromDb (int step)
void editNumericCellWithKeypad (int row, int col)
int findNextStep ()
double getValidatedDouble (int row, int col, String name)
int getValidatedInt (int row, int col, int min, int max, String name)
boolean hasDbDriver ()
DefaultTableModel initializeModel ()
void insertDefaultRowIfNeeded ()
void insertRowInDb (Object[] row)
void installNumericEditorHook ()
boolean isCommandActive (DataElement command)
void loadDbFromFile ()
DefaultTableModel loadOperationsFromDb ()
void pollOperationCommands ()
void pulseOperationCommand (String commandKey)
void removeSelectedRow ()
void renumberStepsAndSyncDb ()
After removing a row, renumber STEP so that it runs from 1..N in table order and update the DB accordingly.
DataElement resolveDataElementFromMap (String mapping)
void startFramePulse ()
void startOperationCommandPolling ()
void startVentingSequence ()
void startVentingSequence (boolean showDialogs)
void startVentingSequence (boolean showDialogs, boolean emitCommandPulse)
void stopFramePulseAndReset ()
void stopVentingSequence ()
void stopVentingSequence (boolean askConfirmation)
void stopVentingSequence (boolean askConfirmation, boolean emitCommandPulse)
void updateRowInDb (int rowIndex)
void updateSelectedRow ()
Static Private Member Functions
static void configureButton (JButton btn, Dimension size, Insets margin)
Private Attributes
final JButton addButton
final Hashtable< String, String > cmdMap
VentingOperations currentVentingOp
boolean dbEnabled = true
String dbUrl
boolean dbWarningLogged = false
final DeviceManager deviceManager
final JButton executeButton
boolean executeCommandArmed = false
boolean framePulseOn = false
Timer framePulseTimer
final String g2StatusKey
final JButton loadDbButton
final String mks2000StatusKey
final String mks50000StatusKey
Timer opCommandTimer
DefaultTableModel operationsModel
final JTable operationsTable
final JFrame ownerForDialogs
final JButton removeButton
final JPanel rootPanel
final JButton stopButton
boolean stopCommandArmed = false
volatile boolean stoppedByUser = false
boolean suppressModelEvents = false
final JPanel tableFrame
final JButton updateButton
volatile boolean ventingRunning = false
Thread ventingThread
final Hashtable< String, String > viewStatusMap
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Encapsulates the venting operations table, DB interactions, and control buttons (add/remove/update/load/execute/stop).
GlgGui now just embeds this panel on the left side.
Definition at line 23 of file VentingTableView.java.
Constructor & Destructor Documentation
VentingTableView()
VentingTableView.VentingTableView (JFrame ownerForDialogs, DeviceManager deviceManager, Hashtable< String, String > cmdMap, Hashtable< String, String > viewStatusMap, String dbUrl, String g2StatusKey, String mks2000StatusKey, String mks50000StatusKey)
Definition at line 70 of file VentingTableView.java.
References addButton, addRow(), applyScientificRendererToG2(), VentingLookAndFeel.applyTableBackground(), attachModelListener(), cmdMap, configureButton(), VentingLookAndFeel.createFramedPanel(), VentingLookAndFeel.createTitleLabel(), dbUrl, deviceManager, executeButton, g2StatusKey, initializeModel(), VentingLookAndFeel.installEditors(), installNumericEditorHook(), loadDbButton, loadDbFromFile(), mks2000StatusKey, mks50000StatusKey, operationsModel, operationsTable, ownerForDialogs, VentingLookAndFeel.packTableColumns(), removeButton, removeSelectedRow(), rootPanel, startOperationCommandPolling(), startVentingSequence(), stopButton, stopVentingSequence(), VentingLookAndFeel.styleOperationsTable(), VentingLookAndFeel.TABLE_BACKGROUND, tableFrame, updateButton, updateSelectedRow(), and viewStatusMap.
Member Function Documentation
addRow()
void VentingTableView.addRow () private
Definition at line 595 of file VentingTableView.java.
Referenced by VentingTableView().
applyScientificRendererToG2()
void VentingTableView.applyScientificRendererToG2 () private
Definition at line 159 of file VentingTableView.java.
References operationsTable.
Referenced by VentingTableView().
attachModelListener()
void VentingTableView.attachModelListener () private
Definition at line 292 of file VentingTableView.java.
Referenced by VentingTableView().
buildTableModel()
static TableModel VentingTableView.buildTableModel (int columnCount, ResultSet resultSet) throws SQLException static
Definition at line 387 of file VentingTableView.java.
configureButton()
static void VentingTableView.configureButton (JButton btn, Dimension size, Insets margin) static private
Definition at line 834 of file VentingTableView.java.
Referenced by VentingTableView().
createDbIfNeeded()
void VentingTableView.createDbIfNeeded () private
Definition at line 311 of file VentingTableView.java.
Referenced by initializeModel().
createEmptyModel()
DefaultTableModel VentingTableView.createEmptyModel () private
Definition at line 182 of file VentingTableView.java.
Referenced by initializeModel().
defaultRow()
Object [] VentingTableView.defaultRow (int step) private
Definition at line 202 of file VentingTableView.java.
Referenced by initializeModel().
deleteRowFromDb()
void VentingTableView.deleteRowFromDb (int step) private
Definition at line 496 of file VentingTableView.java.
editNumericCellWithKeypad()
void VentingTableView.editNumericCellWithKeypad (int row, int col) private
Definition at line 732 of file VentingTableView.java.
References DialogSetPoint.getResultValue(), and DialogSetPoint.isOk().
findNextStep()
int VentingTableView.findNextStep () private
Definition at line 614 of file VentingTableView.java.
getModel()
DefaultTableModel VentingTableView.getModel ()
Definition at line 176 of file VentingTableView.java.
References operationsModel.
getPanel()
JPanel VentingTableView.getPanel ()
Definition at line 168 of file VentingTableView.java.
References rootPanel.
Referenced by GlgGui.createAndShowGui().
getTable()
JTable VentingTableView.getTable ()
Definition at line 172 of file VentingTableView.java.
References operationsTable.
getValidatedDouble()
double VentingTableView.getValidatedDouble (int row, int col, String name) private
Definition at line 810 of file VentingTableView.java.
getValidatedInt()
int VentingTableView.getValidatedInt (int row, int col, int min, int max, String name) private
Definition at line 776 of file VentingTableView.java.
hasDbDriver()
boolean VentingTableView.hasDbDriver () private
Definition at line 217 of file VentingTableView.java.
References dbEnabled, dbUrl, dbWarningLogged, and logger.
Referenced by initializeModel().
initializeModel()
DefaultTableModel VentingTableView.initializeModel () private
Definition at line 235 of file VentingTableView.java.
References createDbIfNeeded(), createEmptyModel(), defaultRow(), hasDbDriver(), insertDefaultRowIfNeeded(), and loadOperationsFromDb().
Referenced by VentingTableView().
insertDefaultRowIfNeeded()
void VentingTableView.insertDefaultRowIfNeeded () private
Definition at line 337 of file VentingTableView.java.
Referenced by initializeModel().
insertRowInDb()
void VentingTableView.insertRowInDb (Object[] row) private
Definition at line 413 of file VentingTableView.java.
installNumericEditorHook()
void VentingTableView.installNumericEditorHook () private
Definition at line 250 of file VentingTableView.java.
References operationsTable.
Referenced by VentingTableView().
isCommandActive()
boolean VentingTableView.isCommandActive (DataElement command) private
Definition at line 888 of file VentingTableView.java.
References DataElement.setvalue, and DataElement.value.
loadDbFromFile()
void VentingTableView.loadDbFromFile () private
Definition at line 668 of file VentingTableView.java.
References VentingLookAndFeel.applyTableBackground(), VentingLookAndFeel.installEditors(), VentingLookAndFeel.packTableColumns(), and VentingLookAndFeel.styleOperationsTable().
Referenced by VentingTableView().
loadOperationsFromDb()
DefaultTableModel VentingTableView.loadOperationsFromDb () private
Definition at line 365 of file VentingTableView.java.
Referenced by initializeModel().
pollOperationCommands()
void VentingTableView.pollOperationCommands () private
Definition at line 844 of file VentingTableView.java.
pulseOperationCommand()
void VentingTableView.pulseOperationCommand (String commandKey) private
Definition at line 892 of file VentingTableView.java.
References Device.commandSetQueue, DataElement.deviceName, DataManager.holdingRegisters, DataElement.mbRegisterOffset, DataElement.setvalue, and DataElement.value.
removeSelectedRow()
void VentingTableView.removeSelectedRow () private
Definition at line 625 of file VentingTableView.java.
Referenced by VentingTableView().
renumberStepsAndSyncDb()
void VentingTableView.renumberStepsAndSyncDb () private
After removing a row, renumber STEP so that it runs from 1..N in table order and update the DB accordingly.
Definition at line 517 of file VentingTableView.java.
resolveDataElementFromMap()
DataElement VentingTableView.resolveDataElementFromMap (String mapping) private
Definition at line 870 of file VentingTableView.java.
References DataManager.getDataElement().
startFramePulse()
void VentingTableView.startFramePulse () private
Definition at line 266 of file VentingTableView.java.
References VentingLookAndFeel.setFrameRunningPhase().
startOperationCommandPolling()
void VentingTableView.startOperationCommandPolling () private
Definition at line 839 of file VentingTableView.java.
Referenced by VentingTableView().
startVentingSequence() [1/3]
void VentingTableView.startVentingSequence () private
Definition at line 936 of file VentingTableView.java.
Referenced by VentingTableView().
startVentingSequence() [2/3]
void VentingTableView.startVentingSequence (boolean showDialogs) private
Definition at line 940 of file VentingTableView.java.
startVentingSequence() [3/3]
void VentingTableView.startVentingSequence (boolean showDialogs, boolean emitCommandPulse) private
Definition at line 944 of file VentingTableView.java.
References VentingLookAndFeel.clearActiveRow(), and VentingOperations.run().
stopFramePulseAndReset()
void VentingTableView.stopFramePulseAndReset () private
Definition at line 283 of file VentingTableView.java.
References VentingLookAndFeel.setFrameIdle().
stopVentingSequence() [1/3]
void VentingTableView.stopVentingSequence () private
Definition at line 1018 of file VentingTableView.java.
Referenced by VentingTableView().
stopVentingSequence() [2/3]
void VentingTableView.stopVentingSequence (boolean askConfirmation) private
Definition at line 1022 of file VentingTableView.java.
stopVentingSequence() [3/3]
void VentingTableView.stopVentingSequence (boolean askConfirmation, boolean emitCommandPulse) private
Definition at line 1026 of file VentingTableView.java.
References VentingLookAndFeel.clearActiveRow(), and VentingLookAndFeel.setFrameStopped().
updateRowInDb()
void VentingTableView.updateRowInDb (int rowIndex) private
Definition at line 441 of file VentingTableView.java.
updateSelectedRow()
void VentingTableView.updateSelectedRow () private
Definition at line 649 of file VentingTableView.java.
Referenced by VentingTableView().
Member Data Documentation
addButton
final JButton VentingTableView.addButton private
Definition at line 42 of file VentingTableView.java.
Referenced by VentingTableView().
cmdMap
final Hashtable<String,String> VentingTableView.cmdMap private
Definition at line 28 of file VentingTableView.java.
Referenced by VentingTableView().
currentVentingOp
VentingOperations VentingTableView.currentVentingOp private
Definition at line 50 of file VentingTableView.java.
dbEnabled
boolean VentingTableView.dbEnabled = true private
Definition at line 53 of file VentingTableView.java.
Referenced by hasDbDriver().
dbUrl
String VentingTableView.dbUrl private
Definition at line 35 of file VentingTableView.java.
Referenced by hasDbDriver(), and VentingTableView().
dbWarningLogged
boolean VentingTableView.dbWarningLogged = false private
Definition at line 54 of file VentingTableView.java.
Referenced by hasDbDriver().
deviceManager
final DeviceManager VentingTableView.deviceManager private
Definition at line 27 of file VentingTableView.java.
Referenced by VentingTableView().
executeButton
final JButton VentingTableView.executeButton private
Definition at line 46 of file VentingTableView.java.
Referenced by VentingTableView().
executeCommandArmed
boolean VentingTableView.executeCommandArmed = false private
Definition at line 59 of file VentingTableView.java.
framePulseOn
boolean VentingTableView.framePulseOn = false private
Definition at line 57 of file VentingTableView.java.
framePulseTimer
Timer VentingTableView.framePulseTimer private
Definition at line 56 of file VentingTableView.java.
g2StatusKey
final String VentingTableView.g2StatusKey private
Definition at line 31 of file VentingTableView.java.
Referenced by VentingTableView().
loadDbButton
final JButton VentingTableView.loadDbButton private
Definition at line 45 of file VentingTableView.java.
Referenced by VentingTableView().
logger
final Logger VentingTableView.logger = Logger.getLogger("Main") static private
Definition at line 25 of file VentingTableView.java.
Referenced by hasDbDriver().
mks2000StatusKey
final String VentingTableView.mks2000StatusKey private
Definition at line 32 of file VentingTableView.java.
Referenced by VentingTableView().
mks50000StatusKey
final String VentingTableView.mks50000StatusKey private
Definition at line 33 of file VentingTableView.java.
Referenced by VentingTableView().
opCommandTimer
Timer VentingTableView.opCommandTimer private
Definition at line 58 of file VentingTableView.java.
operationsModel
DefaultTableModel VentingTableView.operationsModel private
Definition at line 39 of file VentingTableView.java.
Referenced by getModel(), and VentingTableView().
operationsTable
final JTable VentingTableView.operationsTable private
Definition at line 38 of file VentingTableView.java.
Referenced by applyScientificRendererToG2(), getTable(), installNumericEditorHook(), and VentingTableView().
ownerForDialogs
final JFrame VentingTableView.ownerForDialogs private
Definition at line 68 of file VentingTableView.java.
Referenced by VentingTableView().
removeButton
final JButton VentingTableView.removeButton private
Definition at line 43 of file VentingTableView.java.
Referenced by VentingTableView().
rootPanel
final JPanel VentingTableView.rootPanel private
Definition at line 37 of file VentingTableView.java.
Referenced by getPanel(), and VentingTableView().
stopButton
final JButton VentingTableView.stopButton private
Definition at line 47 of file VentingTableView.java.
Referenced by VentingTableView().
stopCommandArmed
boolean VentingTableView.stopCommandArmed = false private
Definition at line 60 of file VentingTableView.java.
stoppedByUser
volatile boolean VentingTableView.stoppedByUser = false private
Definition at line 52 of file VentingTableView.java.
suppressModelEvents
boolean VentingTableView.suppressModelEvents = false private
Definition at line 62 of file VentingTableView.java.
tableFrame
final JPanel VentingTableView.tableFrame private
Definition at line 40 of file VentingTableView.java.
Referenced by VentingTableView().
updateButton
final JButton VentingTableView.updateButton private
Definition at line 44 of file VentingTableView.java.
Referenced by VentingTableView().
ventingRunning
volatile boolean VentingTableView.ventingRunning = false private
Definition at line 49 of file VentingTableView.java.
ventingThread
Thread VentingTableView.ventingThread private
Definition at line 51 of file VentingTableView.java.
viewStatusMap
final Hashtable<String,String> VentingTableView.viewStatusMap private
Definition at line 29 of file VentingTableView.java.
Referenced by VentingTableView().
The documentation for this class was generated from the following file:
work_venting/VentingTableView.java