SCADARPI API: Controllino_3 Class Reference
Controllino_3 Class Reference
Public Member Functions
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Private Attributes
I2C_Comm i2c
Static Private Attributes
static final int AC_HIGH_OFF_STATUS_BIT = 7
static final int AC_HIGH_ON_STATUS_BIT = 6
static final int AC_HIGH_START_CMD_BIT = 4
static final int AC_HIGH_STOP_CMD_BIT = 5
static final int AC_LOW_OFF_STATUS_BIT = 3
static final int AC_LOW_ON_STATUS_BIT = 2
static final int AC_LOW_START_CMD_BIT = 0
static final int AC_LOW_STOP_CMD_BIT = 1
static final int AC_NET_STATUS_BIT = 8
static final int AC_REARM_CMD_BIT = 12
static final int AC_REARM_STATUS_BIT = 13
static final int ARD_RESET_BIT = 8
static final int FAN_START_CMD_BIT = 4
static final int FAN_START_STATUS_BIT = 6
static final int FAN_STOP_CMD_BIT = 5
static final int FAN_STOP_STATUS_BIT = 7
static final Logger logger = Logger.getLogger("Main")
static final int LOW_NOISE_CLOSE_CMD_BIT = 3
static final int LOW_NOISE_OPEN_CMD_BIT = 2
static final int NORMAL_SPEED_CLOSE_CMD_BIT = 1
static final int NORMAL_SPEED_OPEN_CMD_BIT = 0
static final int PUMP_START_CMD_BIT = 9
static final int PUMP_STATUS_BIT = 11
static final int PUMP_STOP_CMD_BIT = 10
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 14 of file Controllino_3.java.
Constructor & Destructor Documentation
Controllino_3() [1/8]
Controllino_3.Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 29 of file Controllino_3.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_3() [2/8]
Controllino_3.Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 29 of file Controllino_3.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_3() [3/8]
Controllino_3.Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 36 of file Controllino_3.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_3() [4/8]
Controllino_3.Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 29 of file Controllino_3.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_3() [5/8]
Controllino_3.Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 29 of file Controllino_3.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_3() [6/8]
Controllino_3.Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 29 of file Controllino_3.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_3() [7/8]
Controllino_3.Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 30 of file Controllino_3.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataTypes.DataType.TRIGGER, and Device.use_i2c_out.
Controllino_3() [8/8]
Controllino_3.Controllino_3 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 29 of file Controllino_3.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Member Function Documentation
bitRead() [1/8]
int Controllino_3.bitRead (int target, int bit)
Definition at line 215 of file Controllino_3.java.
Referenced by updateDeviceData().
bitRead() [2/8]
int Controllino_3.bitRead (int target, int bit)
Definition at line 215 of file Controllino_3.java.
bitRead() [3/8]
int Controllino_3.bitRead (int target, int bit)
Definition at line 261 of file Controllino_3.java.
bitRead() [4/8]
int Controllino_3.bitRead (int target, int bit)
Definition at line 214 of file Controllino_3.java.
bitRead() [5/8]
int Controllino_3.bitRead (int target, int bit)
Definition at line 214 of file Controllino_3.java.
bitRead() [6/8]
int Controllino_3.bitRead (int target, int bit)
Definition at line 216 of file Controllino_3.java.
bitRead() [7/8]
int Controllino_3.bitRead (int target, int bit)
Definition at line 211 of file Controllino_3.java.
bitRead() [8/8]
int Controllino_3.bitRead (int target, int bit)
Definition at line 215 of file Controllino_3.java.
clearBit() [1/8]
int Controllino_3.clearBit (int target, int bit)
Definition at line 223 of file Controllino_3.java.
Referenced by executeCommand().
clearBit() [2/8]
int Controllino_3.clearBit (int target, int bit)
Definition at line 223 of file Controllino_3.java.
clearBit() [3/8]
int Controllino_3.clearBit (int target, int bit)
Definition at line 269 of file Controllino_3.java.
clearBit() [4/8]
int Controllino_3.clearBit (int target, int bit)
Definition at line 222 of file Controllino_3.java.
clearBit() [5/8]
int Controllino_3.clearBit (int target, int bit)
Definition at line 222 of file Controllino_3.java.
clearBit() [6/8]
int Controllino_3.clearBit (int target, int bit)
Definition at line 224 of file Controllino_3.java.
clearBit() [7/8]
int Controllino_3.clearBit (int target, int bit)
Definition at line 219 of file Controllino_3.java.
clearBit() [8/8]
int Controllino_3.clearBit (int target, int bit)
Definition at line 223 of file Controllino_3.java.
executeCommand() [1/8]
void Controllino_3.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 154 of file Controllino_3.java.
References ARD_RESET_BIT, clearBit(), FAN_START_CMD_BIT, FAN_STOP_CMD_BIT, DataManager.holdingRegisters, i2c, logger, LOW_NOISE_OPEN_CMD_BIT, DataElement.mbRegisterOffset, DataElement.name, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, I2C_Comm.Read8bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [2/8]
void Controllino_3.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 154 of file Controllino_3.java.
References ARD_RESET_BIT, clearBit(), FAN_START_CMD_BIT, FAN_STOP_CMD_BIT, DataManager.holdingRegisters, i2c, logger, LOW_NOISE_OPEN_CMD_BIT, DataElement.mbRegisterOffset, DataElement.name, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, I2C_Comm.Read8bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [3/8]
void Controllino_3.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 189 of file Controllino_3.java.
References AC_HIGH_START_CMD_BIT, AC_HIGH_STOP_CMD_BIT, AC_LOW_START_CMD_BIT, AC_LOW_STOP_CMD_BIT, AC_REARM_CMD_BIT, ARD_RESET_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, PUMP_START_CMD_BIT, PUMP_STOP_CMD_BIT, I2C_Comm.Read8bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [4/8]
void Controllino_3.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 153 of file Controllino_3.java.
References ARD_RESET_BIT, clearBit(), FAN_START_CMD_BIT, FAN_STOP_CMD_BIT, DataManager.holdingRegisters, i2c, logger, LOW_NOISE_OPEN_CMD_BIT, DataElement.mbRegisterOffset, DataElement.name, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, I2C_Comm.Read8bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [5/8]
void Controllino_3.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 153 of file Controllino_3.java.
References ARD_RESET_BIT, clearBit(), FAN_START_CMD_BIT, FAN_STOP_CMD_BIT, DataManager.holdingRegisters, i2c, logger, LOW_NOISE_OPEN_CMD_BIT, DataElement.mbRegisterOffset, DataElement.name, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, I2C_Comm.Read8bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [6/8]
void Controllino_3.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 155 of file Controllino_3.java.
References ARD_RESET_BIT, clearBit(), FAN_START_CMD_BIT, FAN_STOP_CMD_BIT, DataManager.holdingRegisters, i2c, logger, LOW_NOISE_OPEN_CMD_BIT, DataElement.mbRegisterOffset, DataElement.name, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, I2C_Comm.Read8bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [7/8]
void Controllino_3.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 161 of file Controllino_3.java.
References ARD_RESET_BIT, clearBit(), FAN_START_CMD_BIT, FAN_STOP_CMD_BIT, DataManager.holdingRegisters, i2c, logger, LOW_NOISE_OPEN_CMD_BIT, DataElement.mbRegisterOffset, DataElement.name, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, I2C_Comm.Read8bytes(), setBit(), Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.Write().
executeCommand() [8/8]
void Controllino_3.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 154 of file Controllino_3.java.
References ARD_RESET_BIT, clearBit(), FAN_START_CMD_BIT, FAN_STOP_CMD_BIT, DataManager.holdingRegisters, i2c, logger, LOW_NOISE_OPEN_CMD_BIT, DataElement.mbRegisterOffset, DataElement.name, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, I2C_Comm.Read8bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
setBit() [1/8]
int Controllino_3.setBit (int target, int bit)
Definition at line 219 of file Controllino_3.java.
Referenced by executeCommand().
setBit() [2/8]
int Controllino_3.setBit (int target, int bit)
Definition at line 219 of file Controllino_3.java.
setBit() [3/8]
int Controllino_3.setBit (int target, int bit)
Definition at line 265 of file Controllino_3.java.
setBit() [4/8]
int Controllino_3.setBit (int target, int bit)
Definition at line 218 of file Controllino_3.java.
setBit() [5/8]
int Controllino_3.setBit (int target, int bit)
Definition at line 218 of file Controllino_3.java.
setBit() [6/8]
int Controllino_3.setBit (int target, int bit)
Definition at line 220 of file Controllino_3.java.
setBit() [7/8]
int Controllino_3.setBit (int target, int bit)
Definition at line 215 of file Controllino_3.java.
setBit() [8/8]
int Controllino_3.setBit (int target, int bit)
Definition at line 219 of file Controllino_3.java.
updateDeviceData() [1/8]
void Controllino_3.updateDeviceData ()
Reimplemented from Device.
Definition at line 67 of file Controllino_3.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, FAN_START_STATUS_BIT, FAN_STOP_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, LOW_NOISE_CLOSE_CMD_BIT, LOW_NOISE_OPEN_CMD_BIT, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, NORMAL_SPEED_OPEN_CMD_BIT, Device.popCommand(), I2C_Comm.Read8bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [2/8]
void Controllino_3.updateDeviceData ()
Reimplemented from Device.
Definition at line 67 of file Controllino_3.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, FAN_START_STATUS_BIT, FAN_STOP_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, LOW_NOISE_CLOSE_CMD_BIT, LOW_NOISE_OPEN_CMD_BIT, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, NORMAL_SPEED_OPEN_CMD_BIT, Device.popCommand(), I2C_Comm.Read8bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [3/8]
void Controllino_3.updateDeviceData ()
Reimplemented from Device.
Definition at line 83 of file Controllino_3.java.
References AC_HIGH_OFF_STATUS_BIT, AC_HIGH_ON_STATUS_BIT, AC_LOW_OFF_STATUS_BIT, AC_LOW_ON_STATUS_BIT, AC_NET_STATUS_BIT, AC_REARM_STATUS_BIT, bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, Device.popCommand(), PUMP_STATUS_BIT, I2C_Comm.Read8bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [4/8]
void Controllino_3.updateDeviceData ()
Reimplemented from Device.
Definition at line 67 of file Controllino_3.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, FAN_START_STATUS_BIT, FAN_STOP_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, LOW_NOISE_CLOSE_CMD_BIT, LOW_NOISE_OPEN_CMD_BIT, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, NORMAL_SPEED_OPEN_CMD_BIT, Device.popCommand(), I2C_Comm.Read8bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [5/8]
void Controllino_3.updateDeviceData ()
Reimplemented from Device.
Definition at line 67 of file Controllino_3.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, FAN_START_STATUS_BIT, FAN_STOP_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, LOW_NOISE_CLOSE_CMD_BIT, LOW_NOISE_OPEN_CMD_BIT, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, NORMAL_SPEED_OPEN_CMD_BIT, Device.popCommand(), I2C_Comm.Read8bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [6/8]
void Controllino_3.updateDeviceData ()
Reimplemented from Device.
Definition at line 67 of file Controllino_3.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, FAN_START_STATUS_BIT, FAN_STOP_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, LOW_NOISE_CLOSE_CMD_BIT, LOW_NOISE_OPEN_CMD_BIT, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, NORMAL_SPEED_OPEN_CMD_BIT, Device.popCommand(), I2C_Comm.Read8bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [7/8]
void Controllino_3.updateDeviceData ()
Reimplemented from Device.
Definition at line 70 of file Controllino_3.java.
References bitRead(), Device.busmutex, FAN_START_STATUS_BIT, FAN_STOP_STATUS_BIT, DataManager.getDataElement(), Device.gpio, Device.hasWarned, i2c, Device.i2c_in, Device.i2c_out, logger, LOW_NOISE_CLOSE_CMD_BIT, LOW_NOISE_OPEN_CMD_BIT, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, NORMAL_SPEED_OPEN_CMD_BIT, Device.popCommand(), I2C_Comm.Read8bytes(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [8/8]
void Controllino_3.updateDeviceData ()
Reimplemented from Device.
Definition at line 67 of file Controllino_3.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, FAN_START_STATUS_BIT, FAN_STOP_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, LOW_NOISE_CLOSE_CMD_BIT, LOW_NOISE_OPEN_CMD_BIT, Device.name, NORMAL_SPEED_CLOSE_CMD_BIT, NORMAL_SPEED_OPEN_CMD_BIT, Device.popCommand(), I2C_Comm.Read8bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
Member Data Documentation
AC_HIGH_OFF_STATUS_BIT
final int Controllino_3.AC_HIGH_OFF_STATUS_BIT = 7 static private
Definition at line 26 of file Controllino_3.java.
Referenced by updateDeviceData().
AC_HIGH_ON_STATUS_BIT
final int Controllino_3.AC_HIGH_ON_STATUS_BIT = 6 static private
Definition at line 25 of file Controllino_3.java.
Referenced by updateDeviceData().
AC_HIGH_START_CMD_BIT
final int Controllino_3.AC_HIGH_START_CMD_BIT = 4 static private
Definition at line 23 of file Controllino_3.java.
Referenced by executeCommand().
AC_HIGH_STOP_CMD_BIT
final int Controllino_3.AC_HIGH_STOP_CMD_BIT = 5 static private
Definition at line 24 of file Controllino_3.java.
Referenced by executeCommand().
AC_LOW_OFF_STATUS_BIT
final int Controllino_3.AC_LOW_OFF_STATUS_BIT = 3 static private
Definition at line 22 of file Controllino_3.java.
Referenced by updateDeviceData().
AC_LOW_ON_STATUS_BIT
final int Controllino_3.AC_LOW_ON_STATUS_BIT = 2 static private
Definition at line 21 of file Controllino_3.java.
Referenced by updateDeviceData().
AC_LOW_START_CMD_BIT
final int Controllino_3.AC_LOW_START_CMD_BIT = 0 static private
Definition at line 19 of file Controllino_3.java.
Referenced by executeCommand().
AC_LOW_STOP_CMD_BIT
final int Controllino_3.AC_LOW_STOP_CMD_BIT = 1 static private
Definition at line 20 of file Controllino_3.java.
Referenced by executeCommand().
AC_NET_STATUS_BIT
final int Controllino_3.AC_NET_STATUS_BIT = 8 static private
Definition at line 27 of file Controllino_3.java.
Referenced by updateDeviceData().
AC_REARM_CMD_BIT
final int Controllino_3.AC_REARM_CMD_BIT = 12 static private
Definition at line 31 of file Controllino_3.java.
Referenced by executeCommand().
AC_REARM_STATUS_BIT
final int Controllino_3.AC_REARM_STATUS_BIT = 13 static private
Definition at line 32 of file Controllino_3.java.
Referenced by updateDeviceData().
ARD_RESET_BIT
static final int Controllino_3.ARD_RESET_BIT = 8 static private
Definition at line 27 of file Controllino_3.java.
Referenced by executeCommand().
FAN_START_CMD_BIT
static final int Controllino_3.FAN_START_CMD_BIT = 4 static private
Definition at line 23 of file Controllino_3.java.
Referenced by executeCommand().
FAN_START_STATUS_BIT
static final int Controllino_3.FAN_START_STATUS_BIT = 6 static private
Definition at line 25 of file Controllino_3.java.
Referenced by updateDeviceData().
FAN_STOP_CMD_BIT
static final int Controllino_3.FAN_STOP_CMD_BIT = 5 static private
Definition at line 24 of file Controllino_3.java.
Referenced by executeCommand().
FAN_STOP_STATUS_BIT
static final int Controllino_3.FAN_STOP_STATUS_BIT = 7 static private
Definition at line 26 of file Controllino_3.java.
Referenced by updateDeviceData().
i2c
I2C_Comm Controllino_3.i2c private
Definition at line 16 of file Controllino_3.java.
Referenced by Controllino_3(), executeCommand(), and updateDeviceData().
logger
static final Logger Controllino_3.logger = Logger.getLogger("Main") static private
Definition at line 17 of file Controllino_3.java.
Referenced by Controllino_3(), executeCommand(), and updateDeviceData().
LOW_NOISE_CLOSE_CMD_BIT
static final int Controllino_3.LOW_NOISE_CLOSE_CMD_BIT = 3 static private
Definition at line 22 of file Controllino_3.java.
Referenced by updateDeviceData().
LOW_NOISE_OPEN_CMD_BIT
static final int Controllino_3.LOW_NOISE_OPEN_CMD_BIT = 2 static private
Definition at line 21 of file Controllino_3.java.
Referenced by executeCommand(), and updateDeviceData().
NORMAL_SPEED_CLOSE_CMD_BIT
static final int Controllino_3.NORMAL_SPEED_CLOSE_CMD_BIT = 1 static private
Definition at line 20 of file Controllino_3.java.
Referenced by executeCommand(), and updateDeviceData().
NORMAL_SPEED_OPEN_CMD_BIT
static final int Controllino_3.NORMAL_SPEED_OPEN_CMD_BIT = 0 static private
Definition at line 19 of file Controllino_3.java.
Referenced by updateDeviceData().
PUMP_START_CMD_BIT
final int Controllino_3.PUMP_START_CMD_BIT = 9 static private
Definition at line 28 of file Controllino_3.java.
Referenced by executeCommand().
PUMP_STATUS_BIT
final int Controllino_3.PUMP_STATUS_BIT = 11 static private
Definition at line 30 of file Controllino_3.java.
Referenced by updateDeviceData().
PUMP_STOP_CMD_BIT
final int Controllino_3.PUMP_STOP_CMD_BIT = 10 static private
Definition at line 29 of file Controllino_3.java.
Referenced by executeCommand().
The documentation for this class was generated from the following file:
work_link/Controllino_3.java