SCADARPI API: Serial_Comm Class Reference
Serial_Comm Class Reference
Public Member Functions
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
int BytesAvailable () throws IllegalStateException, IOException
Available Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
void Close () throws InterruptedException, IOException
Close Method.
boolean isOpen () throws InterruptedException, IOException
isOpen Method
boolean isOpen () throws InterruptedException, IOException
isOpen Method
boolean isOpen () throws InterruptedException, IOException
isOpen Method
boolean isOpen () throws InterruptedException, IOException
isOpen Method
boolean isOpen () throws InterruptedException, IOException
isOpen Method
boolean isOpen () throws InterruptedException, IOException
isOpen Method
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
void Open () throws InterruptedException, IOException
Open Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
byte[] Read () throws InterruptedException, IOException
Read Method.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
Private Attributes
Baud baudrate
SerialConfig config
DataBits databits
FlowControl flowcontrol
Parity parity
final Serial serial = SerialFactory.createInstance()
String serial_port
StopBits stopbits
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 15 of file Serial_Comm.java.
Constructor & Destructor Documentation
Serial_Comm() [1/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [2/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [3/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [4/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [5/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [6/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [7/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [8/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [9/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [10/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [11/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Serial_Comm() [12/12]
Serial_Comm.Serial_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 38 of file Serial_Comm.java.
References baudrate, config, databits, flowcontrol, logger, parity, serial_port, and stopbits.
Member Function Documentation
BytesAvailable() [1/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 131 of file Serial_Comm.java.
References serial.
Referenced by MaxiGauge.executeCommand(), TurboVarianV81AG.executeCommand(), IonicAgilentDual.executeCommand(), TitaneVarianTSP_22.executeCommand(), TitaneVarianTSP_32.executeCommand(), XGSGauge.executeCommand(), MksRotor.executeCommand(), RgaHidenHal201RC.getAnswerFromDevice(), RgaPfeifferQms200.getAnswerFromDevice(), MaxiGauge.updateDeviceData(), TurboVarianV81AG.updateDeviceData(), Chiller.updateDeviceData(), LakeShore.updateDeviceData(), TurboPfeifferDCU.updateDeviceData(), IonicAgilentDual.updateDeviceData(), TitaneVarianTSP_22.updateDeviceData(), TitaneVarianTSP_32.updateDeviceData(), XGSGauge.updateDeviceData(), MksRotor.updateDeviceData(), and Sicem.updateDeviceData().
BytesAvailable() [2/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 139 of file Serial_Comm.java.
References serial.
BytesAvailable() [3/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 139 of file Serial_Comm.java.
References serial.
BytesAvailable() [4/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 131 of file Serial_Comm.java.
References serial.
BytesAvailable() [5/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 131 of file Serial_Comm.java.
References serial.
BytesAvailable() [6/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 139 of file Serial_Comm.java.
References serial.
BytesAvailable() [7/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 139 of file Serial_Comm.java.
References serial.
BytesAvailable() [8/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 131 of file Serial_Comm.java.
References serial.
BytesAvailable() [9/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 131 of file Serial_Comm.java.
References serial.
BytesAvailable() [10/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 131 of file Serial_Comm.java.
References serial.
BytesAvailable() [11/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 139 of file Serial_Comm.java.
References serial.
BytesAvailable() [12/12]
int Serial_Comm.BytesAvailable () throws IllegalStateException, IOException
Available Method.
Definition at line 139 of file Serial_Comm.java.
References serial.
Close() [1/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Referenced by RgaHidenHal201RC.resetDevice(), and RgaPfeifferQms200.updateDeviceData().
Close() [2/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [3/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [4/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [5/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [6/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [7/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [8/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [9/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [10/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [11/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
Close() [12/12]
void Serial_Comm.Close () throws InterruptedException, IOException
Close Method.
Definition at line 86 of file Serial_Comm.java.
References serial.
isOpen() [1/6]
boolean Serial_Comm.isOpen () throws InterruptedException, IOException
isOpen Method
Definition at line 98 of file Serial_Comm.java.
References serial.
Referenced by RgaHidenHal201RC.resetDevice().
isOpen() [2/6]
boolean Serial_Comm.isOpen () throws InterruptedException, IOException
isOpen Method
Definition at line 98 of file Serial_Comm.java.
References serial.
isOpen() [3/6]
boolean Serial_Comm.isOpen () throws InterruptedException, IOException
isOpen Method
Definition at line 98 of file Serial_Comm.java.
References serial.
isOpen() [4/6]
boolean Serial_Comm.isOpen () throws InterruptedException, IOException
isOpen Method
Definition at line 98 of file Serial_Comm.java.
References serial.
isOpen() [5/6]
boolean Serial_Comm.isOpen () throws InterruptedException, IOException
isOpen Method
Definition at line 98 of file Serial_Comm.java.
References serial.
isOpen() [6/6]
boolean Serial_Comm.isOpen () throws InterruptedException, IOException
isOpen Method
Definition at line 98 of file Serial_Comm.java.
References serial.
Open() [1/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Referenced by Chiller.Chiller(), RgaHidenHal201RC.initDevice(), IonicAgilentDual.IonicAgilentDual(), LakeShore.LakeShore(), MaxiGauge.MaxiGauge(), MksRotor.MksRotor(), RgaHidenHal201RC.resetDevice(), RgaPfeifferQms200.RgaPfeifferQms200(), Sicem.Sicem(), TitaneVarianTSP_22.TitaneVarianTSP_22(), TitaneVarianTSP_32.TitaneVarianTSP_32(), TurboPfeifferDCU.TurboPfeifferDCU(), TurboVarianV81AG.TurboVarianV81AG(), RgaPfeifferQms200.updateDeviceData(), and XGSGauge.XGSGauge().
Open() [2/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [3/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [4/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [5/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [6/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [7/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [8/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [9/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [10/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [11/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Open() [12/12]
void Serial_Comm.Open () throws InterruptedException, IOException
Open Method.
Definition at line 74 of file Serial_Comm.java.
References config, and serial.
Read() [1/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 98 of file Serial_Comm.java.
References serial.
Referenced by MaxiGauge.executeCommand(), TurboVarianV81AG.executeCommand(), IonicAgilentDual.executeCommand(), TitaneVarianTSP_22.executeCommand(), TitaneVarianTSP_32.executeCommand(), XGSGauge.executeCommand(), MksRotor.executeCommand(), RgaHidenHal201RC.getAnswerFromDevice(), RgaPfeifferQms200.getAnswerFromDevice(), MaxiGauge.updateDeviceData(), TurboVarianV81AG.updateDeviceData(), Chiller.updateDeviceData(), LakeShore.updateDeviceData(), TurboPfeifferDCU.updateDeviceData(), IonicAgilentDual.updateDeviceData(), TitaneVarianTSP_22.updateDeviceData(), TitaneVarianTSP_32.updateDeviceData(), XGSGauge.updateDeviceData(), MksRotor.updateDeviceData(), and Sicem.updateDeviceData().
Read() [2/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 106 of file Serial_Comm.java.
References serial.
Read() [3/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 106 of file Serial_Comm.java.
References serial.
Read() [4/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 98 of file Serial_Comm.java.
References serial.
Read() [5/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 98 of file Serial_Comm.java.
References serial.
Read() [6/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 106 of file Serial_Comm.java.
References serial.
Read() [7/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 106 of file Serial_Comm.java.
References serial.
Read() [8/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 98 of file Serial_Comm.java.
References serial.
Read() [9/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 98 of file Serial_Comm.java.
References serial.
Read() [10/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 98 of file Serial_Comm.java.
References serial.
Read() [11/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 106 of file Serial_Comm.java.
References serial.
Read() [12/12]
byte [] Serial_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 106 of file Serial_Comm.java.
References serial.
Write() [1/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 120 of file Serial_Comm.java.
References serial.
Write() [2/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 128 of file Serial_Comm.java.
References serial.
Write() [3/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 128 of file Serial_Comm.java.
References serial.
Write() [4/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 120 of file Serial_Comm.java.
References serial.
Write() [5/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 120 of file Serial_Comm.java.
References serial.
Write() [6/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 128 of file Serial_Comm.java.
References serial.
Write() [7/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 128 of file Serial_Comm.java.
References serial.
Write() [8/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 120 of file Serial_Comm.java.
References serial.
Write() [9/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 120 of file Serial_Comm.java.
References serial.
Write() [10/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 120 of file Serial_Comm.java.
References serial.
Write() [11/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 128 of file Serial_Comm.java.
References serial.
Write() [12/24]
void Serial_Comm.Write (byte[] mesg) throws InterruptedException, IOException
Write Method.
Definition at line 128 of file Serial_Comm.java.
References serial.
Write() [13/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 109 of file Serial_Comm.java.
References serial.
Referenced by MaxiGauge.executeCommand(), TurboVarianV81AG.executeCommand(), TurboPfeifferDCU.executeCommand(), IonicAgilentDual.executeCommand(), TitaneVarianTSP_22.executeCommand(), TitaneVarianTSP_32.executeCommand(), XGSGauge.executeCommand(), MksRotor.executeCommand(), Sicem.executeCommand(), RgaHidenHal201RC.getAnswerFromDevice(), RgaPfeifferQms200.getAnswerFromDevice(), MaxiGauge.updateDeviceData(), TurboVarianV81AG.updateDeviceData(), Chiller.updateDeviceData(), LakeShore.updateDeviceData(), TurboPfeifferDCU.updateDeviceData(), IonicAgilentDual.updateDeviceData(), TitaneVarianTSP_22.updateDeviceData(), TitaneVarianTSP_32.updateDeviceData(), XGSGauge.updateDeviceData(), MksRotor.updateDeviceData(), and Sicem.updateDeviceData().
Write() [14/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 117 of file Serial_Comm.java.
References serial.
Write() [15/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 117 of file Serial_Comm.java.
References serial.
Write() [16/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 109 of file Serial_Comm.java.
References serial.
Write() [17/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 109 of file Serial_Comm.java.
References serial.
Write() [18/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 117 of file Serial_Comm.java.
References serial.
Write() [19/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 117 of file Serial_Comm.java.
References serial.
Write() [20/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 109 of file Serial_Comm.java.
References serial.
Write() [21/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 109 of file Serial_Comm.java.
References serial.
Write() [22/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 109 of file Serial_Comm.java.
References serial.
Write() [23/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 117 of file Serial_Comm.java.
References serial.
Write() [24/24]
void Serial_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 117 of file Serial_Comm.java.
References serial.
Member Data Documentation
baudrate
Baud Serial_Comm.baudrate private
Definition at line 19 of file Serial_Comm.java.
Referenced by Serial_Comm().
config
SerialConfig Serial_Comm.config private
Definition at line 24 of file Serial_Comm.java.
Referenced by Open(), and Serial_Comm().
databits
DataBits Serial_Comm.databits private
Definition at line 20 of file Serial_Comm.java.
Referenced by Serial_Comm().
flowcontrol
FlowControl Serial_Comm.flowcontrol private
Definition at line 23 of file Serial_Comm.java.
Referenced by Serial_Comm().
logger
static final Logger Serial_Comm.logger = Logger.getLogger("Main") static private
Definition at line 25 of file Serial_Comm.java.
Referenced by Serial_Comm().
parity
Parity Serial_Comm.parity private
Definition at line 21 of file Serial_Comm.java.
Referenced by Serial_Comm().
serial
final Serial Serial_Comm.serial = SerialFactory.createInstance() private
Definition at line 28 of file Serial_Comm.java.
Referenced by BytesAvailable(), Close(), isOpen(), Open(), Read(), and Write().
serial_port
String Serial_Comm.serial_port private
Definition at line 18 of file Serial_Comm.java.
Referenced by Serial_Comm().
stopbits
StopBits Serial_Comm.stopbits private
Definition at line 22 of file Serial_Comm.java.
Referenced by Serial_Comm().
The documentation for this class was generated from the following file:
work_cryo/Serial_Comm.java