SCADARPI API: RgaPfeifferQms200 Class Reference
RgaPfeifferQms200 Class Reference
Public Member Functions
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
RgaPfeifferQms200 (String _name, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
RgaPfeifferQms200 (String _name, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
RgaPfeifferQms200 (String _name, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
RgaPfeifferQms200 (String _name, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Private Member Functions
String getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException
String getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException
String getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException
String getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException
Private Attributes
Baud baudrate
int channelPos = 0
DataBits databits
FlowControl flowcontrol
boolean isStarted = false
Parity parity
Serial_Comm rs232
String serial_port
StopBits stopbits
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 14 of file RgaPfeifferQms200.java.
Constructor & Destructor Documentation
RgaPfeifferQms200() [1/4]
RgaPfeifferQms200.RgaPfeifferQms200 (String _name, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
Definition at line 27 of file RgaPfeifferQms200.java.
References DataManager.addDataElement(), baudrate, DataTypes.DataType.COM_STATUS, databits, DataTypes.RegisterType.FLOAT32, flowcontrol, getAnswerFromDevice(), DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), parity, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs232, serial_port, stopbits, and DataTypes.DataType.TRIGGER.
RgaPfeifferQms200() [2/4]
RgaPfeifferQms200.RgaPfeifferQms200 (String _name, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
Definition at line 27 of file RgaPfeifferQms200.java.
References DataManager.addDataElement(), baudrate, DataTypes.DataType.COM_STATUS, databits, DataTypes.RegisterType.FLOAT32, flowcontrol, getAnswerFromDevice(), DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), parity, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs232, serial_port, stopbits, and DataTypes.DataType.TRIGGER.
RgaPfeifferQms200() [3/4]
RgaPfeifferQms200.RgaPfeifferQms200 (String _name, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
Definition at line 27 of file RgaPfeifferQms200.java.
References DataManager.addDataElement(), baudrate, DataTypes.DataType.COM_STATUS, databits, DataTypes.RegisterType.FLOAT32, flowcontrol, getAnswerFromDevice(), DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), parity, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs232, serial_port, stopbits, and DataTypes.DataType.TRIGGER.
RgaPfeifferQms200() [4/4]
RgaPfeifferQms200.RgaPfeifferQms200 (String _name, int _mbRegisterStart, String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol)
Definition at line 27 of file RgaPfeifferQms200.java.
References DataManager.addDataElement(), baudrate, DataTypes.DataType.COM_STATUS, databits, DataTypes.RegisterType.FLOAT32, flowcontrol, getAnswerFromDevice(), DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), parity, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs232, serial_port, stopbits, and DataTypes.DataType.TRIGGER.
Member Function Documentation
bitRead() [1/4]
int RgaPfeifferQms200.bitRead (int target, int bit)
Definition at line 402 of file RgaPfeifferQms200.java.
bitRead() [2/4]
int RgaPfeifferQms200.bitRead (int target, int bit)
Definition at line 407 of file RgaPfeifferQms200.java.
bitRead() [3/4]
int RgaPfeifferQms200.bitRead (int target, int bit)
Definition at line 486 of file RgaPfeifferQms200.java.
bitRead() [4/4]
int RgaPfeifferQms200.bitRead (int target, int bit)
Definition at line 486 of file RgaPfeifferQms200.java.
executeCommand() [1/4]
void RgaPfeifferQms200.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 276 of file RgaPfeifferQms200.java.
References getAnswerFromDevice(), DataManager.getDataElement(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
executeCommand() [2/4]
void RgaPfeifferQms200.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 281 of file RgaPfeifferQms200.java.
References getAnswerFromDevice(), DataManager.getDataElement(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
executeCommand() [3/4]
void RgaPfeifferQms200.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 360 of file RgaPfeifferQms200.java.
References getAnswerFromDevice(), DataManager.getDataElement(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
executeCommand() [4/4]
void RgaPfeifferQms200.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 360 of file RgaPfeifferQms200.java.
References getAnswerFromDevice(), DataManager.getDataElement(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
getAnswerFromDevice() [1/4]
String RgaPfeifferQms200.getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException private
Definition at line 370 of file RgaPfeifferQms200.java.
References Serial_Comm.BytesAvailable(), logger, Serial_Comm.Read(), rs232, and Serial_Comm.Write().
Referenced by executeCommand(), RgaPfeifferQms200(), and updateDeviceData().
getAnswerFromDevice() [2/4]
String RgaPfeifferQms200.getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException private
Definition at line 375 of file RgaPfeifferQms200.java.
References Serial_Comm.BytesAvailable(), logger, Serial_Comm.Read(), rs232, and Serial_Comm.Write().
getAnswerFromDevice() [3/4]
String RgaPfeifferQms200.getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException private
Definition at line 454 of file RgaPfeifferQms200.java.
References Serial_Comm.BytesAvailable(), logger, Serial_Comm.Read(), rs232, and Serial_Comm.Write().
getAnswerFromDevice() [4/4]
String RgaPfeifferQms200.getAnswerFromDevice (String query) throws UnsupportedEncodingException, InterruptedException, IOException private
Definition at line 454 of file RgaPfeifferQms200.java.
References Serial_Comm.BytesAvailable(), logger, Serial_Comm.Read(), rs232, and Serial_Comm.Write().
updateDeviceData() [1/4]
void RgaPfeifferQms200.updateDeviceData ()
Reimplemented from Device.
Definition at line 151 of file RgaPfeifferQms200.java.
References channelPos, Serial_Comm.Close(), getAnswerFromDevice(), DataManager.getDataElement(), isStarted, logger, Device.name, Serial_Comm.Open(), Device.popCommand(), rs232, Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [2/4]
void RgaPfeifferQms200.updateDeviceData ()
Reimplemented from Device.
Definition at line 151 of file RgaPfeifferQms200.java.
References channelPos, Serial_Comm.Close(), getAnswerFromDevice(), DataManager.getDataElement(), Device.hasWarned, isStarted, logger, Device.name, Serial_Comm.Open(), Device.popCommand(), rs232, Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [3/4]
void RgaPfeifferQms200.updateDeviceData ()
Reimplemented from Device.
Definition at line 150 of file RgaPfeifferQms200.java.
References channelPos, Serial_Comm.Close(), getAnswerFromDevice(), DataManager.getDataElement(), Device.hasWarned, isStarted, logger, Device.name, Serial_Comm.Open(), Device.popCommand(), rs232, Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [4/4]
void RgaPfeifferQms200.updateDeviceData ()
Reimplemented from Device.
Definition at line 150 of file RgaPfeifferQms200.java.
References channelPos, Serial_Comm.Close(), getAnswerFromDevice(), DataManager.getDataElement(), Device.hasWarned, isStarted, logger, Device.name, Serial_Comm.Open(), Device.popCommand(), rs232, Device.setErrorComStatus(), and DataElement.value.
Member Data Documentation
baudrate
Baud RgaPfeifferQms200.baudrate private
Definition at line 21 of file RgaPfeifferQms200.java.
Referenced by RgaPfeifferQms200().
channelPos
int RgaPfeifferQms200.channelPos = 0 private
Definition at line 19 of file RgaPfeifferQms200.java.
Referenced by updateDeviceData().
databits
DataBits RgaPfeifferQms200.databits private
Definition at line 22 of file RgaPfeifferQms200.java.
Referenced by RgaPfeifferQms200().
flowcontrol
FlowControl RgaPfeifferQms200.flowcontrol private
Definition at line 25 of file RgaPfeifferQms200.java.
Referenced by RgaPfeifferQms200().
isStarted
boolean RgaPfeifferQms200.isStarted = false private
Definition at line 18 of file RgaPfeifferQms200.java.
Referenced by updateDeviceData().
logger
static final Logger RgaPfeifferQms200.logger = Logger.getLogger("Main") static private
Definition at line 17 of file RgaPfeifferQms200.java.
Referenced by executeCommand(), getAnswerFromDevice(), RgaPfeifferQms200(), and updateDeviceData().
parity
Parity RgaPfeifferQms200.parity private
Definition at line 23 of file RgaPfeifferQms200.java.
Referenced by RgaPfeifferQms200().
rs232
Serial_Comm RgaPfeifferQms200.rs232 private
Definition at line 16 of file RgaPfeifferQms200.java.
Referenced by getAnswerFromDevice(), RgaPfeifferQms200(), and updateDeviceData().
serial_port
String RgaPfeifferQms200.serial_port private
Definition at line 20 of file RgaPfeifferQms200.java.
Referenced by RgaPfeifferQms200().
stopbits
StopBits RgaPfeifferQms200.stopbits private
Definition at line 24 of file RgaPfeifferQms200.java.
Referenced by RgaPfeifferQms200().
The documentation for this class was generated from the following file:
work_pump_rack/RgaPfeifferQms200.java