SCADARPI API: SupervisorClient2 Class Reference
SupervisorClient2 Class Reference
Public Member Functions
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
SupervisorClient2 (String _name, int _mbRegisterStart)
SupervisorClient2 (String _name, int _mbRegisterStart)
SupervisorClient2 (String _name, int _mbRegisterStart)
SupervisorClient2 (String _name, int _mbRegisterStart)
SupervisorClient2 (String _name, int _mbRegisterStart)
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Protected Member Functions
HttpURLConnection getServerConnection (String url) throws MalformedURLException, IOException
A connection method called every time a connection to the servlet is needed.
HttpURLConnection getServerConnection (String url) throws MalformedURLException, IOException
A connection method called every time a connection to the servlet is needed.
HttpURLConnection getServerConnection (String url) throws MalformedURLException, IOException
A connection method called every time a connection to the servlet is needed.
HttpURLConnection getServerConnection (String url) throws MalformedURLException, IOException
A connection method called every time a connection to the servlet is needed.
HttpURLConnection getServerConnection (String url) throws MalformedURLException, IOException
A connection method called every time a connection to the servlet is needed.
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Public Attributes inherited from ChannelList
Hashtable< Integer, GlgPoint > ACColorSTATUS
Hashtable< Integer, String > ACSTATUS
Hashtable< Integer, GlgPoint > BypassColorSTATUS
Hashtable< Integer, String > BypassSTATUS
Hashtable< String, String > CRYO1500WCMD
Hashtable< String, String > Cryo1500wIntCMD
Hashtable< String, String > Cryo1500wIntStatus
Hashtable< String, String > CRYO1500WSTATUS
Hashtable< String, String > Cryo1500wStatusDetails
Hashtable< String, String > Cryo1500wTemp
Hashtable< String, String > CRYOIBDETCMD
Hashtable< String, String > CRYOIBDETSTATUS
Hashtable< String, String > CryoIbDetStatusDetails
Hashtable< Integer, GlgPoint > FailOkColorSTATUS
Hashtable< Integer, String > FailOkSTATUS
Hashtable< Integer, GlgPoint > FanColorSTATUS
Hashtable< Integer, GlgPoint > FanSpeedColorSTATUS
Hashtable< Integer, String > FanSpeedSTATUS
Hashtable< Integer, String > FanSTATUS
Hashtable< String, String > FLOWMETERCMD
Hashtable< String, String > FLOWMETERSTATUS
Hashtable< String, String > FlowMeterStatusDetails
Hashtable< String, String > FlowMeterTemp
Hashtable< Integer, GlgPoint > GaugeColorSTATUS
Hashtable< Integer, GlgPoint > GaugePressureColorSTATUS
Hashtable< Integer, String > GaugePressureSTATUS
Hashtable< Integer, String > GaugeSTATUS
Hashtable< Integer, GlgPoint > IonicONOFFColorSTATUS
Hashtable< Integer, String > IonicONOFFSTATUS
Hashtable< Integer, GlgPoint > IonicOperatingModeColorSTATUS
Hashtable< Integer, String > IonicOperatingModeSTATUS
Hashtable< Integer, GlgPoint > IonicRemoteColorSTATUS
Hashtable< Integer, String > IonicRemoteSTATUS
Hashtable< Integer, GlgPoint > IonicVoltageModeColorSTATUS
Hashtable< Integer, String > IonicVoltageModeSTATUS
Hashtable< Integer, GlgPoint > IPSColorSTATUS
Hashtable< Integer, String > IPSSTATUS
Hashtable< String, String > LINKCMD
Hashtable< String, String > LINKSTATUS
Hashtable< String, String > LinkStatusDetails
Hashtable< String, String > LinkTemp
String mainDrawing = "Station.g"
String mainDrawing1 = "PARTICLECOUNTER.g"
String mainDrawing2 = "GAUGE.g"
Hashtable< Integer, GlgPoint > MksComColorSTATUS
Hashtable< Integer, String > MksComSTATUS
Hashtable< Integer, GlgPoint > OkFailColorSTATUS
Hashtable< Integer, String > OkFailSTATUS
Hashtable< String, String > PANEL1STATUS
Hashtable< String, String > PANEL2STATUS
Hashtable< String, String > PANELCMD
Hashtable< String, String > PANELSTATUS
Hashtable< String, String > PCOUNTER2CMD
Hashtable< String, String > PCOUNTER2STATUS
Hashtable< String, String > PCOUNTERCMD
Hashtable< Integer, GlgPoint > PCounterColorCOMSTATUS
Hashtable< Integer, GlgPoint > PCounterColorFLAGSTATUS
Hashtable< Integer, GlgPoint > PCounterColorINSTRSTATUS
Hashtable< Integer, GlgPoint > PCounterColorSTATUS
Hashtable< Integer, String > PCounterCOMSTATUS
Hashtable< Integer, String > PCounterFLAGSTATUS
Hashtable< Integer, String > PCounterINSTRSTATUS
Hashtable< Integer, GlgPoint > PCounterMobileColorFLAGSTATUS
Hashtable< Integer, GlgPoint > PCounterMobileColorSTATUS
Hashtable< Integer, String > PCounterMobileFLAGSTATUS
Hashtable< Integer, String > PCounterMobileSTATUS
Hashtable< String, String > PCOUNTERMOBSTATUS
Hashtable< Integer, String > PCounterSTATUS
Hashtable< String, String > PCOUNTERSTATUS
Hashtable< String, String > PCounterStatusDetails
Hashtable< String, String > PCounterTemp
Hashtable< Integer, GlgPoint > PumpColorSTATUS
Hashtable< Integer, String > PumpSTATUS
Hashtable< Integer, GlgPoint > PushO2ColorSTATUS
Hashtable< Integer, GlgPoint > RearmColorSTATUS
Hashtable< Integer, String > RearmSTATUS
Hashtable< Integer, GlgPoint > RelayGeneralColorSTATUS
Hashtable< Integer, String > RelayGeneralSTATUS
Hashtable< Integer, GlgPoint > RelayO2ColorSTATUS
Hashtable< String, String > RGACMD
Hashtable< Integer, String > RGADegasONOFFSTATUS
Hashtable< Integer, String > RGAEmissionONOFFSTATUS
Hashtable< Integer, GlgPoint > RGAFilamentColorSTATUS
Hashtable< Integer, String > RGAFilamentSTATUS
Hashtable< Integer, String > RGAMODESTATUS
Hashtable< Integer, GlgPoint > RGAONOFFColorSTATUS
Hashtable< Integer, String > RGAOperationONOFFSTATUS
Hashtable< Integer, String > RGARunningONOFFSTATUS
Hashtable< String, String > RGASTATUS
Hashtable< String, String > RgaStatusDetails
Hashtable< String, String > RgaTemp
Hashtable< Integer, GlgPoint > ROTGaugeEmissionColorSTATUS
Hashtable< Integer, String > ROTGaugeEmissionSTATUS
Hashtable< Integer, GlgPoint > SensorO2ColorSTATUS
Hashtable< String, String > SQZCMD
Hashtable< String, String > SQZSTATUS
Hashtable< String, String > SqzStatusDetails
Hashtable< String, String > SqzTemp
Hashtable< String, String > STATIONCMD
Hashtable< String, String > STATIONSTATUS
Hashtable< String, String > TCMuxTemp
Hashtable< Integer, GlgPoint > TitaneAutoStartModeColorSTATUS
Hashtable< Integer, String > TitaneAutoStartModeSTATUS
Hashtable< Integer, GlgPoint > TitaneControllerColorSTATUS
Hashtable< Integer, GlgPoint > TitaneControllerOperatingModeColorSTATUS
Hashtable< Integer, String > TitaneControllerOperatingModeSTATUS
Hashtable< Integer, String > TitaneControllerSTATUS
Hashtable< Integer, GlgPoint > TitaneErrorColorSTATUS
Hashtable< Integer, String > TitaneErrorSTATUS
Hashtable< Integer, GlgPoint > TitaneFilamentColorSTATUS
Hashtable< Integer, String > TitaneFilamentSTATUS
Hashtable< Integer, GlgPoint > TitaneOperatingModeColorSTATUS
Hashtable< Integer, String > TitaneOperatingModeSTATUS
Hashtable< Integer, GlgPoint > TitaneRecoverModeColorSTATUS
Hashtable< Integer, String > TitaneRecoverModeSTATUS
Hashtable< Integer, GlgPoint > TitaneRemoteColorSTATUS
Hashtable< Integer, String > TitaneRemoteSTATUS
Hashtable< Integer, GlgPoint > TitaneStartColorSTATUS
Hashtable< Integer, String > TitaneStartSTATUS
Hashtable< String, String > TUBE1500WCMD
Hashtable< String, String > TUBE1500WSTATUS
Hashtable< String, String > Tube1500wStatusDetails
Hashtable< String, String > TUBECMD
Hashtable< String, String > TUBESTATUS
Hashtable< String, String > TubeStatusDetails
Hashtable< Integer, GlgPoint > Turbo1ErrorColorSTATUS
Hashtable< Integer, String > Turbo1ErrorSTATUS
Hashtable< Integer, GlgPoint > Turbo2ErrorColorSTATUS
Hashtable< Integer, String > Turbo2ErrorSTATUS
Hashtable< Integer, GlgPoint > Turbo3ErrorColorSTATUS
Hashtable< Integer, String > Turbo3ErrorSTATUS
Hashtable< Integer, GlgPoint > TurboONOFFColorSTATUS
Hashtable< Integer, String > TurboONOFFSTATUS
Hashtable< Integer, GlgPoint > TurboStandbyColorSTATUS
Hashtable< Integer, String > TurboStandbySTATUS
Hashtable< Integer, GlgPoint > TurboTemperatureBoxColorSTATUS
Hashtable< Integer, String > TurboTemperatureBoxSTATUS
Hashtable< Integer, GlgPoint > TurboTemperatureColorSTATUS
Hashtable< Integer, String > TurboTemperatureSTATUS
Hashtable< Integer, GlgPoint > VacuumColorSTATUS
Hashtable< Integer, GlgPoint > VacuumComColorSTATUS
Hashtable< Integer, String > VacuumComSTATUS
Hashtable< Integer, String > VacuumSTATUS
Hashtable< Integer, GlgPoint > ValveColorSTATUS
Hashtable< Integer, String > ValveSTATUS
Hashtable< String, String > VENTINGCMD
Hashtable< String, String > VENTINGSTATUS
Hashtable< String, String > VENTINGVIEWSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeDegasColorSTATUS
Hashtable< Integer, String > XGSGaugeDegasSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeEmissionColorSTATUS
Hashtable< Integer, String > XGSGaugeEmissionSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeFilamentColorSTATUS
Hashtable< Integer, String > XGSGaugeFilamentSTATUS
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 26 of file SupervisorClient2.java.
Constructor & Destructor Documentation
SupervisorClient2() [1/5]
SupervisorClient2.SupervisorClient2 (String _name, int _mbRegisterStart)
Definition at line 32 of file SupervisorClient2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, ChannelList.PANEL2STATUS, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.READ_ONLY_VALUE.
SupervisorClient2() [2/5]
SupervisorClient2.SupervisorClient2 (String _name, int _mbRegisterStart)
Definition at line 31 of file SupervisorClient2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.READ_ONLY_VALUE.
SupervisorClient2() [3/5]
SupervisorClient2.SupervisorClient2 (String _name, int _mbRegisterStart)
Definition at line 32 of file SupervisorClient2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, DataTypes.RegisterType.INT32, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, ChannelList.PANEL2STATUS, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.READ_ONLY_VALUE.
SupervisorClient2() [4/5]
SupervisorClient2.SupervisorClient2 (String _name, int _mbRegisterStart)
Definition at line 32 of file SupervisorClient2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, DataTypes.RegisterType.INT32, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, ChannelList.PANEL2STATUS, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.READ_ONLY_VALUE.
SupervisorClient2() [5/5]
SupervisorClient2.SupervisorClient2 (String _name, int _mbRegisterStart)
Definition at line 32 of file SupervisorClient2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, DataTypes.RegisterType.INT32, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, ChannelList.PANEL2STATUS, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.READ_ONLY_VALUE.
Member Function Documentation
executeCommand() [1/5]
void SupervisorClient2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 170 of file SupervisorClient2.java.
executeCommand() [2/5]
void SupervisorClient2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 276 of file SupervisorClient2.java.
executeCommand() [3/5]
void SupervisorClient2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 180 of file SupervisorClient2.java.
executeCommand() [4/5]
void SupervisorClient2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 180 of file SupervisorClient2.java.
executeCommand() [5/5]
void SupervisorClient2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 180 of file SupervisorClient2.java.
getServerConnection() [1/5]
HttpURLConnection SupervisorClient2.getServerConnection (String url) throws MalformedURLException, IOException protected
A connection method called every time a connection to the servlet is needed.
The servlet path points to "jchv" which contains the main servlet for channel visualization.
Definition at line 92 of file SupervisorClient2.java.
Referenced by updateDeviceData().
getServerConnection() [2/5]
HttpURLConnection SupervisorClient2.getServerConnection (String url) throws MalformedURLException, IOException protected
A connection method called every time a connection to the servlet is needed.
The servlet path points to "jchv" which contains the main servlet for channel visualization.
Definition at line 111 of file SupervisorClient2.java.
getServerConnection() [3/5]
HttpURLConnection SupervisorClient2.getServerConnection (String url) throws MalformedURLException, IOException protected
A connection method called every time a connection to the servlet is needed.
The servlet path points to "jchv" which contains the main servlet for channel visualization.
Definition at line 102 of file SupervisorClient2.java.
getServerConnection() [4/5]
HttpURLConnection SupervisorClient2.getServerConnection (String url) throws MalformedURLException, IOException protected
A connection method called every time a connection to the servlet is needed.
The servlet path points to "jchv" which contains the main servlet for channel visualization.
Definition at line 102 of file SupervisorClient2.java.
getServerConnection() [5/5]
HttpURLConnection SupervisorClient2.getServerConnection (String url) throws MalformedURLException, IOException protected
A connection method called every time a connection to the servlet is needed.
The servlet path points to "jchv" which contains the main servlet for channel visualization.
Definition at line 102 of file SupervisorClient2.java.
updateDeviceData() [1/5]
void SupervisorClient2.updateDeviceData ()
Reimplemented from Device.
Definition at line 106 of file SupervisorClient2.java.
References DataManager.getDataElement(), getServerConnection(), Device.hasWarned, logger, Device.name, Device.popCommand(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [2/5]
void SupervisorClient2.updateDeviceData ()
Reimplemented from Device.
Definition at line 125 of file SupervisorClient2.java.
References DataManager.getDataElement(), getServerConnection(), Device.hasWarned, logger, Device.name, Device.popCommand(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [3/5]
void SupervisorClient2.updateDeviceData ()
Reimplemented from Device.
Definition at line 116 of file SupervisorClient2.java.
References DataManager.getDataElement(), getServerConnection(), Device.hasWarned, logger, Device.name, Device.popCommand(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [4/5]
void SupervisorClient2.updateDeviceData ()
Reimplemented from Device.
Definition at line 116 of file SupervisorClient2.java.
References DataManager.getDataElement(), getServerConnection(), Device.hasWarned, logger, Device.name, Device.popCommand(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [5/5]
void SupervisorClient2.updateDeviceData ()
Reimplemented from Device.
Definition at line 116 of file SupervisorClient2.java.
References DataManager.getDataElement(), getServerConnection(), Device.hasWarned, logger, Device.name, Device.popCommand(), Device.setErrorComStatus(), and DataElement.value.
Member Data Documentation
logger
static final Logger SupervisorClient2.logger = Logger.getLogger("Main") static private
Definition at line 28 of file SupervisorClient2.java.
Referenced by SupervisorClient2(), and updateDeviceData().
The documentation for this class was generated from the following file:
work_1500npanel/SupervisorClient2.java