SCADARPI API: GlgPCounterTempGui Class Reference
GlgPCounterTempGui Class Reference
Classes
class InputListener
Public Member Functions
void createCommandMap (Hashtable< String, String > CMD)
void createStatusMap (Hashtable< String, String > STATUS)
GlgPCounterTempGui (GlgGui _parent, Operation _op, String _title, String _origin)
Public Member Functions inherited from GlgChildGui
void addWindowsListener ()
void addWindowsListener ()
void addWindowsListener ()
void addWindowsListener ()
void addWindowsListener ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, DeviceManager _deviceManager, String _title, String _origin)
GlgChildGui (GlgGui _parent, Operation _op, String _title, String _origin)
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
Protected Member Functions
void createAndShowGui ()
void updateGuiFeatures (String glgName, DataElement dataElement)
Protected Member Functions inherited from GlgChildGui
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
static final long serialVersionUID = 354054054072L
Additional Inherited Members
Public Attributes inherited from GlgChildGui
GlgChildGui child
boolean isSuspended = false
GlgGui parent
Public Attributes inherited from ChannelList
Hashtable< Integer, GlgPoint > ACColorSTATUS
Hashtable< Integer, String > ACSTATUS
Hashtable< Integer, GlgPoint > BypassColorSTATUS
Hashtable< Integer, String > BypassSTATUS
Hashtable< String, String > CRYO1500WCMD
Hashtable< String, String > Cryo1500wIntCMD
Hashtable< String, String > Cryo1500wIntStatus
Hashtable< String, String > CRYO1500WSTATUS
Hashtable< String, String > Cryo1500wStatusDetails
Hashtable< String, String > Cryo1500wTemp
Hashtable< String, String > CRYOIBDETCMD
Hashtable< String, String > CRYOIBDETSTATUS
Hashtable< String, String > CryoIbDetStatusDetails
Hashtable< Integer, GlgPoint > FailOkColorSTATUS
Hashtable< Integer, String > FailOkSTATUS
Hashtable< Integer, GlgPoint > FanColorSTATUS
Hashtable< Integer, GlgPoint > FanSpeedColorSTATUS
Hashtable< Integer, String > FanSpeedSTATUS
Hashtable< Integer, String > FanSTATUS
Hashtable< String, String > FLOWMETERCMD
Hashtable< String, String > FLOWMETERSTATUS
Hashtable< String, String > FlowMeterStatusDetails
Hashtable< String, String > FlowMeterTemp
Hashtable< Integer, GlgPoint > GaugeColorSTATUS
Hashtable< Integer, GlgPoint > GaugePressureColorSTATUS
Hashtable< Integer, String > GaugePressureSTATUS
Hashtable< Integer, String > GaugeSTATUS
Hashtable< Integer, GlgPoint > IonicONOFFColorSTATUS
Hashtable< Integer, String > IonicONOFFSTATUS
Hashtable< Integer, GlgPoint > IonicOperatingModeColorSTATUS
Hashtable< Integer, String > IonicOperatingModeSTATUS
Hashtable< Integer, GlgPoint > IonicRemoteColorSTATUS
Hashtable< Integer, String > IonicRemoteSTATUS
Hashtable< Integer, GlgPoint > IonicVoltageModeColorSTATUS
Hashtable< Integer, String > IonicVoltageModeSTATUS
Hashtable< Integer, GlgPoint > IPSColorSTATUS
Hashtable< Integer, String > IPSSTATUS
Hashtable< String, String > LINKCMD
Hashtable< String, String > LINKSTATUS
Hashtable< String, String > LinkStatusDetails
Hashtable< String, String > LinkTemp
String mainDrawing = "Station.g"
String mainDrawing1 = "PARTICLECOUNTER.g"
String mainDrawing2 = "GAUGE.g"
Hashtable< Integer, GlgPoint > MksComColorSTATUS
Hashtable< Integer, String > MksComSTATUS
Hashtable< Integer, GlgPoint > OkFailColorSTATUS
Hashtable< Integer, String > OkFailSTATUS
Hashtable< String, String > PANEL1STATUS
Hashtable< String, String > PANEL2STATUS
Hashtable< String, String > PANELCMD
Hashtable< String, String > PANELSTATUS
Hashtable< String, String > PCOUNTER2CMD
Hashtable< String, String > PCOUNTER2STATUS
Hashtable< String, String > PCOUNTERCMD
Hashtable< Integer, GlgPoint > PCounterColorCOMSTATUS
Hashtable< Integer, GlgPoint > PCounterColorFLAGSTATUS
Hashtable< Integer, GlgPoint > PCounterColorINSTRSTATUS
Hashtable< Integer, GlgPoint > PCounterColorSTATUS
Hashtable< Integer, String > PCounterCOMSTATUS
Hashtable< Integer, String > PCounterFLAGSTATUS
Hashtable< Integer, String > PCounterINSTRSTATUS
Hashtable< Integer, GlgPoint > PCounterMobileColorFLAGSTATUS
Hashtable< Integer, GlgPoint > PCounterMobileColorSTATUS
Hashtable< Integer, String > PCounterMobileFLAGSTATUS
Hashtable< Integer, String > PCounterMobileSTATUS
Hashtable< String, String > PCOUNTERMOBSTATUS
Hashtable< Integer, String > PCounterSTATUS
Hashtable< String, String > PCOUNTERSTATUS
Hashtable< String, String > PCounterStatusDetails
Hashtable< String, String > PCounterTemp
Hashtable< Integer, GlgPoint > PumpColorSTATUS
Hashtable< Integer, String > PumpSTATUS
Hashtable< Integer, GlgPoint > PushO2ColorSTATUS
Hashtable< Integer, GlgPoint > RearmColorSTATUS
Hashtable< Integer, String > RearmSTATUS
Hashtable< Integer, GlgPoint > RelayGeneralColorSTATUS
Hashtable< Integer, String > RelayGeneralSTATUS
Hashtable< Integer, GlgPoint > RelayO2ColorSTATUS
Hashtable< String, String > RGACMD
Hashtable< Integer, String > RGADegasONOFFSTATUS
Hashtable< Integer, String > RGAEmissionONOFFSTATUS
Hashtable< Integer, GlgPoint > RGAFilamentColorSTATUS
Hashtable< Integer, String > RGAFilamentSTATUS
Hashtable< Integer, String > RGAMODESTATUS
Hashtable< Integer, GlgPoint > RGAONOFFColorSTATUS
Hashtable< Integer, String > RGAOperationONOFFSTATUS
Hashtable< Integer, String > RGARunningONOFFSTATUS
Hashtable< String, String > RGASTATUS
Hashtable< String, String > RgaStatusDetails
Hashtable< String, String > RgaTemp
Hashtable< Integer, GlgPoint > ROTGaugeEmissionColorSTATUS
Hashtable< Integer, String > ROTGaugeEmissionSTATUS
Hashtable< Integer, GlgPoint > SensorO2ColorSTATUS
Hashtable< String, String > SQZCMD
Hashtable< String, String > SQZSTATUS
Hashtable< String, String > SqzStatusDetails
Hashtable< String, String > SqzTemp
Hashtable< String, String > STATIONCMD
Hashtable< String, String > STATIONSTATUS
Hashtable< String, String > TCMuxTemp
Hashtable< Integer, GlgPoint > TitaneAutoStartModeColorSTATUS
Hashtable< Integer, String > TitaneAutoStartModeSTATUS
Hashtable< Integer, GlgPoint > TitaneControllerColorSTATUS
Hashtable< Integer, GlgPoint > TitaneControllerOperatingModeColorSTATUS
Hashtable< Integer, String > TitaneControllerOperatingModeSTATUS
Hashtable< Integer, String > TitaneControllerSTATUS
Hashtable< Integer, GlgPoint > TitaneErrorColorSTATUS
Hashtable< Integer, String > TitaneErrorSTATUS
Hashtable< Integer, GlgPoint > TitaneFilamentColorSTATUS
Hashtable< Integer, String > TitaneFilamentSTATUS
Hashtable< Integer, GlgPoint > TitaneOperatingModeColorSTATUS
Hashtable< Integer, String > TitaneOperatingModeSTATUS
Hashtable< Integer, GlgPoint > TitaneRecoverModeColorSTATUS
Hashtable< Integer, String > TitaneRecoverModeSTATUS
Hashtable< Integer, GlgPoint > TitaneRemoteColorSTATUS
Hashtable< Integer, String > TitaneRemoteSTATUS
Hashtable< Integer, GlgPoint > TitaneStartColorSTATUS
Hashtable< Integer, String > TitaneStartSTATUS
Hashtable< String, String > TUBE1500WCMD
Hashtable< String, String > TUBE1500WSTATUS
Hashtable< String, String > Tube1500wStatusDetails
Hashtable< String, String > TUBECMD
Hashtable< String, String > TUBESTATUS
Hashtable< String, String > TubeStatusDetails
Hashtable< Integer, GlgPoint > Turbo1ErrorColorSTATUS
Hashtable< Integer, String > Turbo1ErrorSTATUS
Hashtable< Integer, GlgPoint > Turbo2ErrorColorSTATUS
Hashtable< Integer, String > Turbo2ErrorSTATUS
Hashtable< Integer, GlgPoint > Turbo3ErrorColorSTATUS
Hashtable< Integer, String > Turbo3ErrorSTATUS
Hashtable< Integer, GlgPoint > TurboONOFFColorSTATUS
Hashtable< Integer, String > TurboONOFFSTATUS
Hashtable< Integer, GlgPoint > TurboStandbyColorSTATUS
Hashtable< Integer, String > TurboStandbySTATUS
Hashtable< Integer, GlgPoint > TurboTemperatureBoxColorSTATUS
Hashtable< Integer, String > TurboTemperatureBoxSTATUS
Hashtable< Integer, GlgPoint > TurboTemperatureColorSTATUS
Hashtable< Integer, String > TurboTemperatureSTATUS
Hashtable< Integer, GlgPoint > VacuumColorSTATUS
Hashtable< Integer, GlgPoint > VacuumComColorSTATUS
Hashtable< Integer, String > VacuumComSTATUS
Hashtable< Integer, String > VacuumSTATUS
Hashtable< Integer, GlgPoint > ValveColorSTATUS
Hashtable< Integer, String > ValveSTATUS
Hashtable< String, String > VENTINGCMD
Hashtable< String, String > VENTINGSTATUS
Hashtable< String, String > VENTINGVIEWSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeDegasColorSTATUS
Hashtable< Integer, String > XGSGaugeDegasSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeEmissionColorSTATUS
Hashtable< Integer, String > XGSGaugeEmissionSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeFilamentColorSTATUS
Hashtable< Integer, String > XGSGaugeFilamentSTATUS
Protected Attributes inherited from GlgChildGui
Hashtable< String, String > CMD = new Hashtable < String, String > ()
Container content
DeviceManager deviceManager
GlgJLWBean glg_bean
String glgdrawing
Operation op
String origin
boolean showParent = false
Hashtable< String, String > STATUS = new Hashtable < String, String > ()
String title
Detailed Description
Definition at line 17 of file GlgPCounterTempGui.java.
Constructor & Destructor Documentation
GlgPCounterTempGui()
GlgPCounterTempGui.GlgPCounterTempGui (GlgGui _parent, Operation _op, String _title, String _origin)
Definition at line 22 of file GlgPCounterTempGui.java.
Member Function Documentation
createAndShowGui()
void GlgPCounterTempGui.createAndShowGui () protected
Reimplemented from GlgChildGui.
Definition at line 26 of file GlgPCounterTempGui.java.
References GlgChildGui.CMD, GlgChildGui.content, createCommandMap(), createStatusMap(), GlgChildGui.glg_bean, logger, GlgChildGui.STATUS, and GlgChildGui.title.
createCommandMap()
void GlgPCounterTempGui.createCommandMap (Hashtable< String, String > CMD)
Reimplemented from GlgChildGui.
Definition at line 49 of file GlgPCounterTempGui.java.
References GlgChildGui.CMD, and ChannelList.PCOUNTERCMD.
Referenced by createAndShowGui().
createStatusMap()
void GlgPCounterTempGui.createStatusMap (Hashtable< String, String > STATUS)
Reimplemented from GlgChildGui.
Definition at line 55 of file GlgPCounterTempGui.java.
References ChannelList.PCounterTemp, and GlgChildGui.STATUS.
Referenced by createAndShowGui().
updateGuiFeatures()
void GlgPCounterTempGui.updateGuiFeatures (String glgName, DataElement dataElement) protected
Reimplemented from GlgChildGui.
Definition at line 62 of file GlgPCounterTempGui.java.
References GlgChildGui.glg_bean, ChannelList.OkFailColorSTATUS, ChannelList.OkFailSTATUS, and DataElement.value.
Member Data Documentation
logger
final Logger GlgPCounterTempGui.logger = Logger.getLogger("Main") static private
Definition at line 20 of file GlgPCounterTempGui.java.
Referenced by createAndShowGui(), and GlgPCounterTempGui.InputListener.InputCallback().
serialVersionUID
final long GlgPCounterTempGui.serialVersionUID = 354054054072L static private
Definition at line 19 of file GlgPCounterTempGui.java.
The documentation for this class was generated from the following file:
work_pcounter/GlgPCounterTempGui.java