SCADARPI API: MaxiGauge Class Reference
MaxiGauge Class Reference
Public Member Functions
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Private Attributes
Serial_Comm rs485
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 13 of file MaxiGauge.java.
Constructor & Destructor Documentation
MaxiGauge() [1/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [2/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [3/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [4/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [5/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [6/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [7/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [8/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [9/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [10/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
MaxiGauge() [11/11]
MaxiGauge.MaxiGauge (String _name, int _mbRegisterStart, String serial_port, Baud baudrate, DataBits databits, Parity parity, StopBits stopbits, FlowControl flowcontrol)
Definition at line 18 of file MaxiGauge.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, Serial_Comm.Open(), DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, rs485, and DataTypes.DataType.TRIGGER.
Member Function Documentation
executeCommand() [1/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [2/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [3/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [4/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [5/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [6/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 191 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [7/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [8/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [9/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [10/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
executeCommand() [11/11]
void MaxiGauge.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [1/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [2/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [3/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [4/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [5/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [6/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), Device.comm_cnt_failure, Device.comm_max_failure, DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [7/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [8/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [9/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [10/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
updateDeviceData() [11/11]
void MaxiGauge.updateDeviceData ()
Reimplemented from Device.
Definition at line 88 of file MaxiGauge.java.
References Serial_Comm.BytesAvailable(), DataManager.getDataElement(), Device.hasWarned, logger, Device.name, Device.popCommand(), Serial_Comm.Read(), rs485, Device.setErrorComStatus(), DataElement.value, and Serial_Comm.Write().
Member Data Documentation
logger
static final Logger MaxiGauge.logger = Logger.getLogger("Main") static private
Definition at line 16 of file MaxiGauge.java.
Referenced by executeCommand(), MaxiGauge(), and updateDeviceData().
rs485
Serial_Comm MaxiGauge.rs485 private
Definition at line 15 of file MaxiGauge.java.
Referenced by executeCommand(), MaxiGauge(), and updateDeviceData().
The documentation for this class was generated from the following file:
work_cryo/MaxiGauge.java