SCADARPI API: Controllino Class Reference
Controllino Class Reference
Public Member Functions
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
Controllino (String _name, int _mbRegisterStart, int i2c_addr)
Controllino (String _name, int _mbRegisterStart, int i2c_addr)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
int setBit (int target, int bit)
int setBit (int target, int bit)
void updateDeviceData ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Private Member Functions
byte[] intToBytes (final int i)
Private Attributes
I2C_Comm i2c
Static Private Attributes
static final int ARD_RESET_BIT = 8
static final int COMPRESSAIR_STATUS_BIT = 13
static final int DUTYCYCLE_TRIG_BIT = 7
static final int FREQUENCY_TRIG_BIT = 6
static final Logger logger = Logger.getLogger("Main")
static final int MAIN_OFF_CMD_BIT = 1
static final int MAIN_OFF_STATUS_BIT = 3
static final int MAIN_ON_CMD_BIT = 0
static final int MAIN_ON_STATUS_BIT = 2
static final int NEGATIVE_VOLT_TRIG_BIT = 4
static final int P22_OFF_CMD_BIT = 5
static final int P22_ON_CMD_BIT = 4
static final int P22_STATUS_BIT = 10
static final int P31_32_OFF_CMD_BIT = 23
static final int P31_32_ON_CMD_BIT = 22
static final int P31_32_STATUS_BIT = 24
static final int POSITIVE_VOLT_TRIG_BIT = 5
static final int V21_CLOSE_CMD_BIT = 1
static final int V21_CLOSE_STATUS_BIT = 7
static final int V21_OPEN_CMD_BIT = 0
static final int V21_OPEN_STATUS_BIT = 6
static final int V22_CLOSE_CMD_BIT = 3
static final int V22_CLOSE_STATUS_BIT = 9
static final int V22_OPEN_CMD_BIT = 2
static final int V22_OPEN_STATUS_BIT = 8
static final int V23_CLOSE_STATUS_BIT = 12
static final int V23_OPEN_STATUS_BIT = 11
static final int V31_CLOSE_CMD_BIT = 21
static final int V31_CLOSE_STATUS_BIT = 19
static final int V31_OPEN_CMD_BIT = 20
static final int V31_OPEN_STATUS_BIT = 18
static final int VA1_CLOSE_STATUS_BIT = 15
static final int VA1_OPEN_STATUS_BIT = 14
static final int VA2_CLOSE_STATUS_BIT = 17
static final int VA2_OPEN_STATUS_BIT = 16
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 15 of file Controllino.java.
Constructor & Destructor Documentation
Controllino() [1/2]
Controllino.Controllino (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 30 of file Controllino.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, Device.sleepTime, and DataTypes.DataType.TRIGGER.
Controllino() [2/2]
Controllino.Controllino (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 47 of file Controllino.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.TRIGGER.
Member Function Documentation
bitRead() [1/2]
int Controllino.bitRead (int target, int bit)
Definition at line 254 of file Controllino.java.
Referenced by updateDeviceData().
bitRead() [2/2]
int Controllino.bitRead (int target, int bit)
Definition at line 251 of file Controllino.java.
clearBit() [1/2]
int Controllino.clearBit (int target, int bit)
Definition at line 262 of file Controllino.java.
Referenced by executeCommand().
clearBit() [2/2]
int Controllino.clearBit (int target, int bit)
Definition at line 259 of file Controllino.java.
executeCommand() [1/2]
void Controllino.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 173 of file Controllino.java.
References clearBit(), DUTYCYCLE_TRIG_BIT, FREQUENCY_TRIG_BIT, DataManager.holdingRegisters, i2c, logger, MAIN_OFF_CMD_BIT, MAIN_ON_CMD_BIT, DataElement.mbRegisterOffset, DataElement.name, Device.name, NEGATIVE_VOLT_TRIG_BIT, POSITIVE_VOLT_TRIG_BIT, I2C_Comm.Read28bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [2/2]
void Controllino.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 188 of file Controllino.java.
References clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, P31_32_OFF_CMD_BIT, P31_32_ON_CMD_BIT, I2C_Comm.Read(), setBit(), Device.setErrorComStatus(), V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, V31_CLOSE_CMD_BIT, V31_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.Write().
intToBytes()
byte [] Controllino.intToBytes (final int i) private
Definition at line 248 of file Controllino.java.
setBit() [1/2]
int Controllino.setBit (int target, int bit)
Definition at line 258 of file Controllino.java.
Referenced by executeCommand().
setBit() [2/2]
int Controllino.setBit (int target, int bit)
Definition at line 255 of file Controllino.java.
updateDeviceData() [1/2]
void Controllino.updateDeviceData ()
Reimplemented from Device.
Definition at line 76 of file Controllino.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, DataManager.getDataElement(), Device.hasWarned, i2c, logger, MAIN_OFF_STATUS_BIT, MAIN_ON_STATUS_BIT, Device.name, Device.popCommand(), I2C_Comm.Read28bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [2/2]
void Controllino.updateDeviceData ()
Reimplemented from Device.
Definition at line 95 of file Controllino.java.
References bitRead(), Device.busmutex, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), i2c, logger, Device.name, P22_STATUS_BIT, P31_32_STATUS_BIT, Device.popCommand(), I2C_Comm.Read(), Device.setErrorComStatus(), V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, V31_CLOSE_STATUS_BIT, V31_OPEN_STATUS_BIT, VA1_CLOSE_STATUS_BIT, VA1_OPEN_STATUS_BIT, VA2_CLOSE_STATUS_BIT, VA2_OPEN_STATUS_BIT, and DataElement.value.
Member Data Documentation
ARD_RESET_BIT
static final int Controllino.ARD_RESET_BIT = 8 static private
Definition at line 28 of file Controllino.java.
COMPRESSAIR_STATUS_BIT
final int Controllino.COMPRESSAIR_STATUS_BIT = 13 static private
Definition at line 32 of file Controllino.java.
Referenced by updateDeviceData().
DUTYCYCLE_TRIG_BIT
final int Controllino.DUTYCYCLE_TRIG_BIT = 7 static private
Definition at line 27 of file Controllino.java.
Referenced by executeCommand().
FREQUENCY_TRIG_BIT
final int Controllino.FREQUENCY_TRIG_BIT = 6 static private
Definition at line 26 of file Controllino.java.
Referenced by executeCommand().
i2c
I2C_Comm Controllino.i2c private
Definition at line 17 of file Controllino.java.
Referenced by Controllino(), executeCommand(), and updateDeviceData().
logger
static final Logger Controllino.logger = Logger.getLogger("Main") static private
Definition at line 18 of file Controllino.java.
Referenced by Controllino(), executeCommand(), and updateDeviceData().
MAIN_OFF_CMD_BIT
final int Controllino.MAIN_OFF_CMD_BIT = 1 static private
Definition at line 21 of file Controllino.java.
Referenced by executeCommand().
MAIN_OFF_STATUS_BIT
final int Controllino.MAIN_OFF_STATUS_BIT = 3 static private
Definition at line 23 of file Controllino.java.
Referenced by updateDeviceData().
MAIN_ON_CMD_BIT
final int Controllino.MAIN_ON_CMD_BIT = 0 static private
Definition at line 20 of file Controllino.java.
Referenced by executeCommand().
MAIN_ON_STATUS_BIT
final int Controllino.MAIN_ON_STATUS_BIT = 2 static private
Definition at line 22 of file Controllino.java.
Referenced by updateDeviceData().
NEGATIVE_VOLT_TRIG_BIT
final int Controllino.NEGATIVE_VOLT_TRIG_BIT = 4 static private
Definition at line 24 of file Controllino.java.
Referenced by executeCommand().
P22_OFF_CMD_BIT
final int Controllino.P22_OFF_CMD_BIT = 5 static private
Definition at line 24 of file Controllino.java.
Referenced by executeCommand().
P22_ON_CMD_BIT
final int Controllino.P22_ON_CMD_BIT = 4 static private
Definition at line 23 of file Controllino.java.
Referenced by executeCommand().
P22_STATUS_BIT
final int Controllino.P22_STATUS_BIT = 10 static private
Definition at line 29 of file Controllino.java.
Referenced by updateDeviceData().
P31_32_OFF_CMD_BIT
final int Controllino.P31_32_OFF_CMD_BIT = 23 static private
Definition at line 42 of file Controllino.java.
Referenced by executeCommand().
P31_32_ON_CMD_BIT
final int Controllino.P31_32_ON_CMD_BIT = 22 static private
Definition at line 41 of file Controllino.java.
Referenced by executeCommand().
P31_32_STATUS_BIT
final int Controllino.P31_32_STATUS_BIT = 24 static private
Definition at line 43 of file Controllino.java.
Referenced by updateDeviceData().
POSITIVE_VOLT_TRIG_BIT
final int Controllino.POSITIVE_VOLT_TRIG_BIT = 5 static private
Definition at line 25 of file Controllino.java.
Referenced by executeCommand().
V21_CLOSE_CMD_BIT
final int Controllino.V21_CLOSE_CMD_BIT = 1 static private
Definition at line 20 of file Controllino.java.
Referenced by executeCommand().
V21_CLOSE_STATUS_BIT
final int Controllino.V21_CLOSE_STATUS_BIT = 7 static private
Definition at line 26 of file Controllino.java.
Referenced by updateDeviceData().
V21_OPEN_CMD_BIT
final int Controllino.V21_OPEN_CMD_BIT = 0 static private
Definition at line 19 of file Controllino.java.
Referenced by executeCommand().
V21_OPEN_STATUS_BIT
final int Controllino.V21_OPEN_STATUS_BIT = 6 static private
Definition at line 25 of file Controllino.java.
Referenced by updateDeviceData().
V22_CLOSE_CMD_BIT
final int Controllino.V22_CLOSE_CMD_BIT = 3 static private
Definition at line 22 of file Controllino.java.
Referenced by executeCommand().
V22_CLOSE_STATUS_BIT
final int Controllino.V22_CLOSE_STATUS_BIT = 9 static private
Definition at line 28 of file Controllino.java.
Referenced by updateDeviceData().
V22_OPEN_CMD_BIT
final int Controllino.V22_OPEN_CMD_BIT = 2 static private
Definition at line 21 of file Controllino.java.
Referenced by executeCommand().
V22_OPEN_STATUS_BIT
final int Controllino.V22_OPEN_STATUS_BIT = 8 static private
Definition at line 27 of file Controllino.java.
Referenced by updateDeviceData().
V23_CLOSE_STATUS_BIT
final int Controllino.V23_CLOSE_STATUS_BIT = 12 static private
Definition at line 31 of file Controllino.java.
Referenced by updateDeviceData().
V23_OPEN_STATUS_BIT
final int Controllino.V23_OPEN_STATUS_BIT = 11 static private
Definition at line 30 of file Controllino.java.
Referenced by updateDeviceData().
V31_CLOSE_CMD_BIT
final int Controllino.V31_CLOSE_CMD_BIT = 21 static private
Definition at line 40 of file Controllino.java.
Referenced by executeCommand().
V31_CLOSE_STATUS_BIT
final int Controllino.V31_CLOSE_STATUS_BIT = 19 static private
Definition at line 38 of file Controllino.java.
Referenced by updateDeviceData().
V31_OPEN_CMD_BIT
final int Controllino.V31_OPEN_CMD_BIT = 20 static private
Definition at line 39 of file Controllino.java.
Referenced by executeCommand().
V31_OPEN_STATUS_BIT
final int Controllino.V31_OPEN_STATUS_BIT = 18 static private
Definition at line 37 of file Controllino.java.
Referenced by updateDeviceData().
VA1_CLOSE_STATUS_BIT
final int Controllino.VA1_CLOSE_STATUS_BIT = 15 static private
Definition at line 34 of file Controllino.java.
Referenced by updateDeviceData().
VA1_OPEN_STATUS_BIT
final int Controllino.VA1_OPEN_STATUS_BIT = 14 static private
Definition at line 33 of file Controllino.java.
Referenced by updateDeviceData().
VA2_CLOSE_STATUS_BIT
final int Controllino.VA2_CLOSE_STATUS_BIT = 17 static private
Definition at line 36 of file Controllino.java.
Referenced by updateDeviceData().
VA2_OPEN_STATUS_BIT
final int Controllino.VA2_OPEN_STATUS_BIT = 16 static private
Definition at line 35 of file Controllino.java.
Referenced by updateDeviceData().
The documentation for this class was generated from the following file:
work_modulator/Controllino.java