SCADARPI API: Vacuum Class Reference
Vacuum Class Reference
Public Member Functions
void executeCommand (DataElement e)
void updateDeviceData ()
Vacuum (String _name, int _mbRegisterStart, DeviceManager _deviceManager)
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Private Attributes
DeviceManager deviceManager
double g22tmp = 0
int g22wait_st = 0
int g22wait_ust = 0
int p21wait = 0
int v1wait = 0
int v21wait = 0
boolean vac_isStarted = false
boolean vac_isStopped = false
boolean vac_Start = false
int vac_step = -1
boolean vac_Stop = false
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 21 of file Vacuum.java.
Constructor & Destructor Documentation
Vacuum()
Vacuum.Vacuum (String _name, int _mbRegisterStart, DeviceManager _deviceManager)
Definition at line 39 of file Vacuum.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, deviceManager, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.TRIGGER.
Member Function Documentation
executeCommand()
void Vacuum.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 496 of file Vacuum.java.
References DataManager.holdingRegisters, logger, Device.name, and Device.setErrorComStatus().
updateDeviceData()
void Vacuum.updateDeviceData ()
Reimplemented from Device.
Definition at line 67 of file Vacuum.java.
References Device.commandSetQueue, deviceManager, g22tmp, g22wait_st, g22wait_ust, DataManager.getDataElement(), Device.hasWarned, logger, Device.name, p21wait, Device.popCommand(), Device.setErrorComStatus(), DataElement.setvalue, v1wait, v21wait, vac_isStarted, vac_isStopped, vac_Start, vac_step, vac_Stop, and DataElement.value.
Member Data Documentation
deviceManager
DeviceManager Vacuum.deviceManager private
Definition at line 26 of file Vacuum.java.
Referenced by updateDeviceData(), and Vacuum().
g22tmp
double Vacuum.g22tmp = 0 private
Definition at line 32 of file Vacuum.java.
Referenced by updateDeviceData().
g22wait_st
int Vacuum.g22wait_st = 0 private
Definition at line 33 of file Vacuum.java.
Referenced by updateDeviceData().
g22wait_ust
int Vacuum.g22wait_ust = 0 private
Definition at line 34 of file Vacuum.java.
Referenced by updateDeviceData().
logger
final Logger Vacuum.logger = Logger.getLogger("Main") static private
Definition at line 23 of file Vacuum.java.
Referenced by executeCommand(), updateDeviceData(), and Vacuum().
p21wait
int Vacuum.p21wait = 0 private
Definition at line 37 of file Vacuum.java.
Referenced by updateDeviceData().
v1wait
int Vacuum.v1wait = 0 private
Definition at line 35 of file Vacuum.java.
Referenced by updateDeviceData().
v21wait
int Vacuum.v21wait = 0 private
Definition at line 36 of file Vacuum.java.
Referenced by updateDeviceData().
vac_isStarted
boolean Vacuum.vac_isStarted = false private
Definition at line 29 of file Vacuum.java.
Referenced by updateDeviceData().
vac_isStopped
boolean Vacuum.vac_isStopped = false private
Definition at line 30 of file Vacuum.java.
Referenced by updateDeviceData().
vac_Start
boolean Vacuum.vac_Start = false private
Definition at line 27 of file Vacuum.java.
Referenced by updateDeviceData().
vac_step
int Vacuum.vac_step = -1 private
Definition at line 31 of file Vacuum.java.
Referenced by updateDeviceData().
vac_Stop
boolean Vacuum.vac_Stop = false private
Definition at line 28 of file Vacuum.java.
Referenced by updateDeviceData().
The documentation for this class was generated from the following file:
work_sqz/Vacuum.java