SCADARPI API: RS232_Comm Class Reference
RS232_Comm Class Reference
Public Member Functions
byte[] Read () throws InterruptedException, IOException
Read Method.
RS232_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
void Write (String mesg) throws InterruptedException, IOException
Write Method.
Private Attributes
Baud baudrate
DataBits databits
FlowControl flowcontrol
Parity parity
final Serial serial = SerialFactory.createInstance()
String serial_port
StopBits stopbits
Static Private Attributes
static final Logger logger = Logger.getLogger("JPiMainTest")
Detailed Description
Definition at line 15 of file RS232_Comm.java.
Constructor & Destructor Documentation
RS232_Comm()
RS232_Comm.RS232_Comm (String _serial_port, Baud _baudrate, DataBits _databits, Parity _parity, StopBits _stopbits, FlowControl _flowcontrol) throws InterruptedException, IOException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file RS232_Comm.java.
References baudrate, databits, flowcontrol, logger, parity, serial, serial_port, and stopbits.
Member Function Documentation
Read()
byte [] RS232_Comm.Read () throws InterruptedException, IOException
Read Method.
Definition at line 82 of file RS232_Comm.java.
References logger, and serial.
Write()
void RS232_Comm.Write (String mesg) throws InterruptedException, IOException
Write Method.
Definition at line 93 of file RS232_Comm.java.
References logger, and serial.
Member Data Documentation
baudrate
Baud RS232_Comm.baudrate private
Definition at line 19 of file RS232_Comm.java.
Referenced by RS232_Comm().
databits
DataBits RS232_Comm.databits private
Definition at line 20 of file RS232_Comm.java.
Referenced by RS232_Comm().
flowcontrol
FlowControl RS232_Comm.flowcontrol private
Definition at line 23 of file RS232_Comm.java.
Referenced by RS232_Comm().
logger
final Logger RS232_Comm.logger = Logger.getLogger("JPiMainTest") static private
Definition at line 24 of file RS232_Comm.java.
Referenced by Read(), RS232_Comm(), and Write().
parity
Parity RS232_Comm.parity private
Definition at line 21 of file RS232_Comm.java.
Referenced by RS232_Comm().
serial
final Serial RS232_Comm.serial = SerialFactory.createInstance() private
Definition at line 27 of file RS232_Comm.java.
Referenced by Read(), RS232_Comm(), and Write().
serial_port
String RS232_Comm.serial_port private
Definition at line 18 of file RS232_Comm.java.
Referenced by RS232_Comm().
stopbits
StopBits RS232_Comm.stopbits private
Definition at line 22 of file RS232_Comm.java.
Referenced by RS232_Comm().
The documentation for this class was generated from the following file:
work_sqz0n/copy/RS232_Comm.java