SCADARPI API: Controllino_1 Class Reference
Controllino_1 Class Reference
Public Member Functions
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Private Attributes
I2C_Comm i2c
Static Private Attributes
static final int ARD_RESET_BIT = 31
static final int BYPASS_OFF_CMD_BIT = 5
static final int BYPASS_OFF_STATUS_BIT = 15
static final int BYPASS_ON_CMD_BIT = 4
static final int BYPASS_ON_STATUS_BIT = 14
static final int BYPASS_STATUS_BIT = 6
static final int COMPRESSAIR_STATUS_BIT = 22
static final Logger logger = Logger.getLogger("Main")
static final int P1_OFF_CMD_BIT = 8
static final int P1_ON_CMD_BIT = 7
static final int P1_STATUS_BIT = 9
static final int P22_OFF_CMD_BIT = 17
static final int P22_ON_CMD_BIT = 16
static final int P22_STATUS_BIT = 18
static final int P22DET_OFF_CMD_BIT = 17
static final int P22DET_ON_CMD_BIT = 16
static final int P22DET_STATUS_BIT = 18
static final int P22IB_OFF_CMD_BIT = 20
static final int P22IB_ON_CMD_BIT = 19
static final int P22IB_STATUS_BIT = 21
static final int V1_CLOSE_CMD_BIT = 9
static final int V1_CLOSE_STATUS_BIT = 11
static final int V1_OPEN_CMD_BIT = 8
static final int V1_OPEN_STATUS_BIT = 10
static final int V21_CLOSE_CMD_BIT = 1
static final int V21_CLOSE_STATUS_BIT = 3
static final int V21_OPEN_CMD_BIT = 0
static final int V21_OPEN_STATUS_BIT = 2
static final int V21DET_CLOSE_CMD_BIT = 1
static final int V21DET_CLOSE_STATUS_BIT = 3
static final int V21DET_OPEN_CMD_BIT = 0
static final int V21DET_OPEN_STATUS_BIT = 2
static final int V21IB_CLOSE_CMD_BIT = 9
static final int V21IB_CLOSE_STATUS_BIT = 11
static final int V21IB_OPEN_CMD_BIT = 8
static final int V21IB_OPEN_STATUS_BIT = 10
static final int V22_CLOSE_CMD_BIT = 5
static final int V22_CLOSE_STATUS_BIT = 7
static final int V22_OPEN_CMD_BIT = 4
static final int V22_OPEN_STATUS_BIT = 6
static final int V22DET_CLOSE_CMD_BIT = 5
static final int V22DET_CLOSE_STATUS_BIT = 7
static final int V22DET_OPEN_CMD_BIT = 4
static final int V22DET_OPEN_STATUS_BIT = 6
static final int V22IB_CLOSE_CMD_BIT = 13
static final int V22IB_CLOSE_STATUS_BIT = 15
static final int V22IB_OPEN_CMD_BIT = 12
static final int V22IB_OPEN_STATUS_BIT = 14
static final int V23_CLOSE_STATUS_BIT = 20
static final int V23_OPEN_STATUS_BIT = 19
static final int VBI_CLOSE_CMD_BIT = 25
static final int VBI_CLOSE_STATUS_BIT = 27
static final int VBI_OPEN_CMD_BIT = 24
static final int VBI_OPEN_STATUS_BIT = 26
static final int VBO_CLOSE_CMD_BIT = 21
static final int VBO_CLOSE_STATUS_BIT = 23
static final int VBO_OPEN_CMD_BIT = 20
static final int VBO_OPEN_STATUS_BIT = 22
static final int VBYPASS_CLOSE_CMD_BIT = 1
static final int VBYPASS_CLOSE_STATUS_BIT = 3
static final int VBYPASS_OPEN_CMD_BIT = 0
static final int VBYPASS_OPEN_STATUS_BIT = 2
static final int VDRYER_CLOSE_CMD_BIT = 9
static final int VDRYER_CLOSE_STATUS_BIT = 11
static final int VDRYER_OPEN_CMD_BIT = 8
static final int VDRYER_OPEN_STATUS_BIT = 10
static final int VENT_CLOSE_STATUS_BIT = 19
static final int VENT_OPEN_STATUS_BIT = 18
static final int VGAS_CLOSE_CMD_BIT = 1
static final int VGAS_CLOSE_STATUS_BIT = 3
static final int VGAS_OPEN_CMD_BIT = 0
static final int VGAS_OPEN_STATUS_BIT = 2
static final int VI_CLOSE_CMD_BIT = 17
static final int VI_CLOSE_STATUS_BIT = 19
static final int VI_OPEN_CMD_BIT = 16
static final int VI_OPEN_STATUS_BIT = 18
static final int VMAIN_CLOSE_CMD_BIT = 17
static final int VMAIN_OPEN_CMD_BIT = 16
static final int VO_CLOSE_CMD_BIT = 13
static final int VO_CLOSE_STATUS_BIT = 15
static final int VO_OPEN_CMD_BIT = 12
static final int VO_OPEN_STATUS_BIT = 14
static final int VP1_CLOSE_CMD_BIT = 9
static final int VP1_CLOSE_STATUS_BIT = 11
static final int VP1_OPEN_CMD_BIT = 8
static final int VP1_OPEN_STATUS_BIT = 10
static final int VPI_CLOSE_CMD_BIT = 5
static final int VPI_CLOSE_STATUS_BIT = 7
static final int VPI_OPEN_CMD_BIT = 4
static final int VPI_OPEN_STATUS_BIT = 6
static final int VPO_CLOSE_CMD_BIT = 1
static final int VPO_CLOSE_STATUS_BIT = 3
static final int VPO_OPEN_CMD_BIT = 0
static final int VPO_OPEN_STATUS_BIT = 2
static final int VRP_CLOSE_CMD_BIT = 5
static final int VRP_CLOSE_STATUS_BIT = 7
static final int VRP_OPEN_CMD_BIT = 4
static final int VRP_OPEN_STATUS_BIT = 6
static final int VSOFT_CLOSE_CMD_BIT = 21
static final int VSOFT_OPEN_CMD_BIT = 20
static final int VVENTING_CLOSE_CMD_BIT = 29
static final int VVENTING_CLOSE_STATUS_BIT = 31
static final int VVENTING_OPEN_CMD_BIT = 28
static final int VVENTING_OPEN_STATUS_BIT = 30
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 15 of file Controllino_1.java.
Constructor & Destructor Documentation
Controllino_1() [1/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 45 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.TRIGGER.
Controllino_1() [2/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 65 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_1() [3/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_1() [4/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_1() [5/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_1() [6/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_1() [7/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_1() [8/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 44 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, Device.gpio, i2c, Device.i2c_out, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataTypes.DataType.TRIGGER, and Device.use_i2c_out.
Controllino_1() [9/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_1() [10/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_1() [11/11]
Controllino_1.Controllino_1 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 47 of file Controllino_1.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.TRIGGER.
Member Function Documentation
bitRead() [1/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 273 of file Controllino_1.java.
Referenced by updateDeviceData().
bitRead() [2/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 395 of file Controllino_1.java.
bitRead() [3/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 271 of file Controllino_1.java.
bitRead() [4/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 271 of file Controllino_1.java.
bitRead() [5/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 271 of file Controllino_1.java.
bitRead() [6/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 271 of file Controllino_1.java.
bitRead() [7/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 271 of file Controllino_1.java.
bitRead() [8/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 277 of file Controllino_1.java.
bitRead() [9/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 271 of file Controllino_1.java.
bitRead() [10/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 271 of file Controllino_1.java.
bitRead() [11/11]
int Controllino_1.bitRead (int target, int bit)
Definition at line 280 of file Controllino_1.java.
clearBit() [1/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 281 of file Controllino_1.java.
Referenced by executeCommand().
clearBit() [2/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 403 of file Controllino_1.java.
clearBit() [3/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 279 of file Controllino_1.java.
clearBit() [4/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 279 of file Controllino_1.java.
clearBit() [5/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 279 of file Controllino_1.java.
clearBit() [6/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 279 of file Controllino_1.java.
clearBit() [7/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 279 of file Controllino_1.java.
clearBit() [8/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 285 of file Controllino_1.java.
clearBit() [9/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 279 of file Controllino_1.java.
clearBit() [10/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 279 of file Controllino_1.java.
clearBit() [11/11]
int Controllino_1.clearBit (int target, int bit)
Definition at line 288 of file Controllino_1.java.
executeCommand() [1/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 200 of file Controllino_1.java.
References clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22DET_OFF_CMD_BIT, P22DET_ON_CMD_BIT, P22IB_OFF_CMD_BIT, P22IB_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V21DET_CLOSE_CMD_BIT, V21DET_OPEN_CMD_BIT, V21IB_CLOSE_CMD_BIT, V21IB_OPEN_CMD_BIT, V22DET_CLOSE_CMD_BIT, V22DET_OPEN_CMD_BIT, V22IB_CLOSE_CMD_BIT, V22IB_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [2/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 277 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P1_OFF_CMD_BIT, P1_ON_CMD_BIT, I2C_Comm.Read8bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.value, VBI_CLOSE_CMD_BIT, VBI_OPEN_CMD_BIT, VBO_CLOSE_CMD_BIT, VBO_OPEN_CMD_BIT, VGAS_CLOSE_CMD_BIT, VGAS_OPEN_CMD_BIT, VI_CLOSE_CMD_BIT, VI_OPEN_CMD_BIT, VO_CLOSE_CMD_BIT, VO_OPEN_CMD_BIT, VP1_CLOSE_CMD_BIT, VP1_OPEN_CMD_BIT, VPI_CLOSE_CMD_BIT, VPI_OPEN_CMD_BIT, VPO_CLOSE_CMD_BIT, VPO_OPEN_CMD_BIT, VVENTING_CLOSE_CMD_BIT, VVENTING_OPEN_CMD_BIT, and I2C_Comm.WritePlusCRC32().
executeCommand() [3/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [4/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [5/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [6/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [7/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [8/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 214 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.Write().
executeCommand() [9/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [10/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_1.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [11/11]
void Controllino_1.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 199 of file Controllino_1.java.
References clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P1_OFF_CMD_BIT, P1_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, DataElement.value, VBYPASS_CLOSE_CMD_BIT, VBYPASS_OPEN_CMD_BIT, VDRYER_CLOSE_CMD_BIT, VDRYER_OPEN_CMD_BIT, VMAIN_CLOSE_CMD_BIT, VMAIN_OPEN_CMD_BIT, VRP_CLOSE_CMD_BIT, VRP_OPEN_CMD_BIT, VSOFT_CLOSE_CMD_BIT, VSOFT_OPEN_CMD_BIT, and I2C_Comm.WritePlusCRC32().
setBit() [1/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 277 of file Controllino_1.java.
Referenced by executeCommand().
setBit() [2/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 399 of file Controllino_1.java.
setBit() [3/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 275 of file Controllino_1.java.
setBit() [4/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 275 of file Controllino_1.java.
setBit() [5/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 275 of file Controllino_1.java.
setBit() [6/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 275 of file Controllino_1.java.
setBit() [7/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 275 of file Controllino_1.java.
setBit() [8/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 281 of file Controllino_1.java.
setBit() [9/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 275 of file Controllino_1.java.
setBit() [10/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 275 of file Controllino_1.java.
setBit() [11/11]
int Controllino_1.setBit (int target, int bit)
Definition at line 284 of file Controllino_1.java.
updateDeviceData() [1/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 93 of file Controllino_1.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22DET_STATUS_BIT, P22IB_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V21DET_CLOSE_STATUS_BIT, V21DET_OPEN_STATUS_BIT, V21IB_CLOSE_STATUS_BIT, V21IB_OPEN_STATUS_BIT, V22DET_CLOSE_STATUS_BIT, V22DET_OPEN_STATUS_BIT, V22IB_CLOSE_STATUS_BIT, V22IB_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [2/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 124 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P1_STATUS_BIT, Device.popCommand(), I2C_Comm.Read8bytesPlusCRC32(), Device.setErrorComStatus(), DataElement.value, VBI_CLOSE_STATUS_BIT, VBI_OPEN_STATUS_BIT, VBO_CLOSE_STATUS_BIT, VBO_OPEN_STATUS_BIT, VGAS_CLOSE_STATUS_BIT, VGAS_OPEN_STATUS_BIT, VI_CLOSE_STATUS_BIT, VI_OPEN_STATUS_BIT, VO_CLOSE_STATUS_BIT, VO_OPEN_STATUS_BIT, VP1_CLOSE_STATUS_BIT, VP1_OPEN_STATUS_BIT, VPI_CLOSE_STATUS_BIT, VPI_OPEN_STATUS_BIT, VPO_CLOSE_STATUS_BIT, VPO_OPEN_STATUS_BIT, VVENTING_CLOSE_STATUS_BIT, and VVENTING_OPEN_STATUS_BIT.
updateDeviceData() [3/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [4/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [5/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [6/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [7/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [8/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 98 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.gpio, Device.hasWarned, i2c, Device.i2c_in, Device.i2c_out, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [9/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [10/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_1.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [11/11]
void Controllino_1.updateDeviceData ()
Reimplemented from Device.
Definition at line 94 of file Controllino_1.java.
References bitRead(), Device.busmutex, Device.comm_cnt_failure, Device.comm_max_failure, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P1_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, DataElement.value, VBYPASS_CLOSE_STATUS_BIT, VBYPASS_OPEN_STATUS_BIT, VDRYER_CLOSE_STATUS_BIT, VDRYER_OPEN_STATUS_BIT, VENT_CLOSE_STATUS_BIT, VENT_OPEN_STATUS_BIT, VRP_CLOSE_STATUS_BIT, and VRP_OPEN_STATUS_BIT.
Member Data Documentation
ARD_RESET_BIT
static final int Controllino_1.ARD_RESET_BIT = 31 static private
Definition at line 43 of file Controllino_1.java.
BYPASS_OFF_CMD_BIT
static final int Controllino_1.BYPASS_OFF_CMD_BIT = 5 static private
Definition at line 57 of file Controllino_1.java.
Referenced by executeCommand().
BYPASS_OFF_STATUS_BIT
static final int Controllino_1.BYPASS_OFF_STATUS_BIT = 15 static private
Definition at line 34 of file Controllino_1.java.
Referenced by updateDeviceData().
BYPASS_ON_CMD_BIT
static final int Controllino_1.BYPASS_ON_CMD_BIT = 4 static private
Definition at line 56 of file Controllino_1.java.
Referenced by executeCommand().
BYPASS_ON_STATUS_BIT
static final int Controllino_1.BYPASS_ON_STATUS_BIT = 14 static private
Definition at line 33 of file Controllino_1.java.
Referenced by updateDeviceData().
BYPASS_STATUS_BIT
final int Controllino_1.BYPASS_STATUS_BIT = 6 static private
Definition at line 58 of file Controllino_1.java.
Referenced by updateDeviceData().
COMPRESSAIR_STATUS_BIT
static final int Controllino_1.COMPRESSAIR_STATUS_BIT = 22 static private
Definition at line 42 of file Controllino_1.java.
Referenced by updateDeviceData().
i2c
I2C_Comm Controllino_1.i2c private
Definition at line 17 of file Controllino_1.java.
Referenced by Controllino_1(), executeCommand(), and updateDeviceData().
logger
static final Logger Controllino_1.logger = Logger.getLogger("Main") static private
Definition at line 18 of file Controllino_1.java.
Referenced by Controllino_1(), executeCommand(), and updateDeviceData().
P1_OFF_CMD_BIT
static final int Controllino_1.P1_OFF_CMD_BIT = 8 static private
Definition at line 60 of file Controllino_1.java.
Referenced by executeCommand().
P1_ON_CMD_BIT
static final int Controllino_1.P1_ON_CMD_BIT = 7 static private
Definition at line 59 of file Controllino_1.java.
Referenced by executeCommand().
P1_STATUS_BIT
static final int Controllino_1.P1_STATUS_BIT = 9 static private
Definition at line 61 of file Controllino_1.java.
Referenced by updateDeviceData().
P22_OFF_CMD_BIT
static final int Controllino_1.P22_OFF_CMD_BIT = 17 static private
Definition at line 36 of file Controllino_1.java.
Referenced by executeCommand().
P22_ON_CMD_BIT
static final int Controllino_1.P22_ON_CMD_BIT = 16 static private
Definition at line 35 of file Controllino_1.java.
Referenced by executeCommand().
P22_STATUS_BIT
static final int Controllino_1.P22_STATUS_BIT = 18 static private
Definition at line 37 of file Controllino_1.java.
Referenced by updateDeviceData().
P22DET_OFF_CMD_BIT
final int Controllino_1.P22DET_OFF_CMD_BIT = 17 static private
Definition at line 37 of file Controllino_1.java.
Referenced by executeCommand().
P22DET_ON_CMD_BIT
final int Controllino_1.P22DET_ON_CMD_BIT = 16 static private
Definition at line 36 of file Controllino_1.java.
Referenced by executeCommand().
P22DET_STATUS_BIT
final int Controllino_1.P22DET_STATUS_BIT = 18 static private
Definition at line 38 of file Controllino_1.java.
Referenced by updateDeviceData().
P22IB_OFF_CMD_BIT
final int Controllino_1.P22IB_OFF_CMD_BIT = 20 static private
Definition at line 40 of file Controllino_1.java.
Referenced by executeCommand().
P22IB_ON_CMD_BIT
final int Controllino_1.P22IB_ON_CMD_BIT = 19 static private
Definition at line 39 of file Controllino_1.java.
Referenced by executeCommand().
P22IB_STATUS_BIT
final int Controllino_1.P22IB_STATUS_BIT = 21 static private
Definition at line 41 of file Controllino_1.java.
Referenced by updateDeviceData().
V1_CLOSE_CMD_BIT
static final int Controllino_1.V1_CLOSE_CMD_BIT = 9 static private
Definition at line 28 of file Controllino_1.java.
Referenced by executeCommand().
V1_CLOSE_STATUS_BIT
static final int Controllino_1.V1_CLOSE_STATUS_BIT = 11 static private
Definition at line 30 of file Controllino_1.java.
Referenced by updateDeviceData().
V1_OPEN_CMD_BIT
static final int Controllino_1.V1_OPEN_CMD_BIT = 8 static private
Definition at line 27 of file Controllino_1.java.
Referenced by executeCommand().
V1_OPEN_STATUS_BIT
static final int Controllino_1.V1_OPEN_STATUS_BIT = 10 static private
Definition at line 29 of file Controllino_1.java.
Referenced by updateDeviceData().
V21_CLOSE_CMD_BIT
static final int Controllino_1.V21_CLOSE_CMD_BIT = 1 static private
Definition at line 20 of file Controllino_1.java.
Referenced by executeCommand().
V21_CLOSE_STATUS_BIT
static final int Controllino_1.V21_CLOSE_STATUS_BIT = 3 static private
Definition at line 22 of file Controllino_1.java.
Referenced by updateDeviceData().
V21_OPEN_CMD_BIT
static final int Controllino_1.V21_OPEN_CMD_BIT = 0 static private
Definition at line 19 of file Controllino_1.java.
Referenced by executeCommand().
V21_OPEN_STATUS_BIT
static final int Controllino_1.V21_OPEN_STATUS_BIT = 2 static private
Definition at line 21 of file Controllino_1.java.
Referenced by updateDeviceData().
V21DET_CLOSE_CMD_BIT
final int Controllino_1.V21DET_CLOSE_CMD_BIT = 1 static private
Definition at line 21 of file Controllino_1.java.
Referenced by executeCommand().
V21DET_CLOSE_STATUS_BIT
final int Controllino_1.V21DET_CLOSE_STATUS_BIT = 3 static private
Definition at line 23 of file Controllino_1.java.
Referenced by updateDeviceData().
V21DET_OPEN_CMD_BIT
final int Controllino_1.V21DET_OPEN_CMD_BIT = 0 static private
Definition at line 20 of file Controllino_1.java.
Referenced by executeCommand().
V21DET_OPEN_STATUS_BIT
final int Controllino_1.V21DET_OPEN_STATUS_BIT = 2 static private
Definition at line 22 of file Controllino_1.java.
Referenced by updateDeviceData().
V21IB_CLOSE_CMD_BIT
final int Controllino_1.V21IB_CLOSE_CMD_BIT = 9 static private
Definition at line 29 of file Controllino_1.java.
Referenced by executeCommand().
V21IB_CLOSE_STATUS_BIT
final int Controllino_1.V21IB_CLOSE_STATUS_BIT = 11 static private
Definition at line 31 of file Controllino_1.java.
Referenced by updateDeviceData().
V21IB_OPEN_CMD_BIT
final int Controllino_1.V21IB_OPEN_CMD_BIT = 8 static private
Definition at line 28 of file Controllino_1.java.
Referenced by executeCommand().
V21IB_OPEN_STATUS_BIT
final int Controllino_1.V21IB_OPEN_STATUS_BIT = 10 static private
Definition at line 30 of file Controllino_1.java.
Referenced by updateDeviceData().
V22_CLOSE_CMD_BIT
static final int Controllino_1.V22_CLOSE_CMD_BIT = 5 static private
Definition at line 24 of file Controllino_1.java.
Referenced by executeCommand().
V22_CLOSE_STATUS_BIT
static final int Controllino_1.V22_CLOSE_STATUS_BIT = 7 static private
Definition at line 26 of file Controllino_1.java.
Referenced by updateDeviceData().
V22_OPEN_CMD_BIT
static final int Controllino_1.V22_OPEN_CMD_BIT = 4 static private
Definition at line 23 of file Controllino_1.java.
Referenced by executeCommand().
V22_OPEN_STATUS_BIT
static final int Controllino_1.V22_OPEN_STATUS_BIT = 6 static private
Definition at line 25 of file Controllino_1.java.
Referenced by updateDeviceData().
V22DET_CLOSE_CMD_BIT
final int Controllino_1.V22DET_CLOSE_CMD_BIT = 5 static private
Definition at line 25 of file Controllino_1.java.
Referenced by executeCommand().
V22DET_CLOSE_STATUS_BIT
final int Controllino_1.V22DET_CLOSE_STATUS_BIT = 7 static private
Definition at line 27 of file Controllino_1.java.
Referenced by updateDeviceData().
V22DET_OPEN_CMD_BIT
final int Controllino_1.V22DET_OPEN_CMD_BIT = 4 static private
Definition at line 24 of file Controllino_1.java.
Referenced by executeCommand().
V22DET_OPEN_STATUS_BIT
final int Controllino_1.V22DET_OPEN_STATUS_BIT = 6 static private
Definition at line 26 of file Controllino_1.java.
Referenced by updateDeviceData().
V22IB_CLOSE_CMD_BIT
final int Controllino_1.V22IB_CLOSE_CMD_BIT = 13 static private
Definition at line 33 of file Controllino_1.java.
Referenced by executeCommand().
V22IB_CLOSE_STATUS_BIT
final int Controllino_1.V22IB_CLOSE_STATUS_BIT = 15 static private
Definition at line 35 of file Controllino_1.java.
Referenced by updateDeviceData().
V22IB_OPEN_CMD_BIT
final int Controllino_1.V22IB_OPEN_CMD_BIT = 12 static private
Definition at line 32 of file Controllino_1.java.
Referenced by executeCommand().
V22IB_OPEN_STATUS_BIT
final int Controllino_1.V22IB_OPEN_STATUS_BIT = 14 static private
Definition at line 34 of file Controllino_1.java.
Referenced by updateDeviceData().
V23_CLOSE_STATUS_BIT
static final int Controllino_1.V23_CLOSE_STATUS_BIT = 20 static private
Definition at line 39 of file Controllino_1.java.
Referenced by updateDeviceData().
V23_OPEN_STATUS_BIT
static final int Controllino_1.V23_OPEN_STATUS_BIT = 19 static private
Definition at line 38 of file Controllino_1.java.
Referenced by updateDeviceData().
VBI_CLOSE_CMD_BIT
final int Controllino_1.VBI_CLOSE_CMD_BIT = 25 static private
Definition at line 44 of file Controllino_1.java.
Referenced by executeCommand().
VBI_CLOSE_STATUS_BIT
final int Controllino_1.VBI_CLOSE_STATUS_BIT = 27 static private
Definition at line 46 of file Controllino_1.java.
Referenced by updateDeviceData().
VBI_OPEN_CMD_BIT
final int Controllino_1.VBI_OPEN_CMD_BIT = 24 static private
Definition at line 43 of file Controllino_1.java.
Referenced by executeCommand().
VBI_OPEN_STATUS_BIT
final int Controllino_1.VBI_OPEN_STATUS_BIT = 26 static private
Definition at line 45 of file Controllino_1.java.
Referenced by updateDeviceData().
VBO_CLOSE_CMD_BIT
final int Controllino_1.VBO_CLOSE_CMD_BIT = 21 static private
Definition at line 40 of file Controllino_1.java.
Referenced by executeCommand().
VBO_CLOSE_STATUS_BIT
final int Controllino_1.VBO_CLOSE_STATUS_BIT = 23 static private
Definition at line 42 of file Controllino_1.java.
Referenced by updateDeviceData().
VBO_OPEN_CMD_BIT
final int Controllino_1.VBO_OPEN_CMD_BIT = 20 static private
Definition at line 39 of file Controllino_1.java.
Referenced by executeCommand().
VBO_OPEN_STATUS_BIT
final int Controllino_1.VBO_OPEN_STATUS_BIT = 22 static private
Definition at line 41 of file Controllino_1.java.
Referenced by updateDeviceData().
VBYPASS_CLOSE_CMD_BIT
final int Controllino_1.VBYPASS_CLOSE_CMD_BIT = 1 static private
Definition at line 20 of file Controllino_1.java.
Referenced by executeCommand().
VBYPASS_CLOSE_STATUS_BIT
final int Controllino_1.VBYPASS_CLOSE_STATUS_BIT = 3 static private
Definition at line 22 of file Controllino_1.java.
Referenced by updateDeviceData().
VBYPASS_OPEN_CMD_BIT
final int Controllino_1.VBYPASS_OPEN_CMD_BIT = 0 static private
Definition at line 19 of file Controllino_1.java.
Referenced by executeCommand().
VBYPASS_OPEN_STATUS_BIT
final int Controllino_1.VBYPASS_OPEN_STATUS_BIT = 2 static private
Definition at line 21 of file Controllino_1.java.
Referenced by updateDeviceData().
VDRYER_CLOSE_CMD_BIT
final int Controllino_1.VDRYER_CLOSE_CMD_BIT = 9 static private
Definition at line 28 of file Controllino_1.java.
Referenced by executeCommand().
VDRYER_CLOSE_STATUS_BIT
final int Controllino_1.VDRYER_CLOSE_STATUS_BIT = 11 static private
Definition at line 30 of file Controllino_1.java.
Referenced by updateDeviceData().
VDRYER_OPEN_CMD_BIT
final int Controllino_1.VDRYER_OPEN_CMD_BIT = 8 static private
Definition at line 27 of file Controllino_1.java.
Referenced by executeCommand().
VDRYER_OPEN_STATUS_BIT
final int Controllino_1.VDRYER_OPEN_STATUS_BIT = 10 static private
Definition at line 29 of file Controllino_1.java.
Referenced by updateDeviceData().
VENT_CLOSE_STATUS_BIT
final int Controllino_1.VENT_CLOSE_STATUS_BIT = 19 static private
Definition at line 38 of file Controllino_1.java.
Referenced by updateDeviceData().
VENT_OPEN_STATUS_BIT
final int Controllino_1.VENT_OPEN_STATUS_BIT = 18 static private
Definition at line 37 of file Controllino_1.java.
Referenced by updateDeviceData().
VGAS_CLOSE_CMD_BIT
final int Controllino_1.VGAS_CLOSE_CMD_BIT = 1 static private
Definition at line 53 of file Controllino_1.java.
Referenced by executeCommand().
VGAS_CLOSE_STATUS_BIT
final int Controllino_1.VGAS_CLOSE_STATUS_BIT = 3 static private
Definition at line 55 of file Controllino_1.java.
Referenced by updateDeviceData().
VGAS_OPEN_CMD_BIT
final int Controllino_1.VGAS_OPEN_CMD_BIT = 0 static private
Definition at line 52 of file Controllino_1.java.
Referenced by executeCommand().
VGAS_OPEN_STATUS_BIT
final int Controllino_1.VGAS_OPEN_STATUS_BIT = 2 static private
Definition at line 54 of file Controllino_1.java.
Referenced by updateDeviceData().
VI_CLOSE_CMD_BIT
final int Controllino_1.VI_CLOSE_CMD_BIT = 17 static private
Definition at line 36 of file Controllino_1.java.
Referenced by executeCommand().
VI_CLOSE_STATUS_BIT
final int Controllino_1.VI_CLOSE_STATUS_BIT = 19 static private
Definition at line 38 of file Controllino_1.java.
Referenced by updateDeviceData().
VI_OPEN_CMD_BIT
final int Controllino_1.VI_OPEN_CMD_BIT = 16 static private
Definition at line 35 of file Controllino_1.java.
Referenced by executeCommand().
VI_OPEN_STATUS_BIT
final int Controllino_1.VI_OPEN_STATUS_BIT = 18 static private
Definition at line 37 of file Controllino_1.java.
Referenced by updateDeviceData().
VMAIN_CLOSE_CMD_BIT
final int Controllino_1.VMAIN_CLOSE_CMD_BIT = 17 static private
Definition at line 36 of file Controllino_1.java.
Referenced by executeCommand().
VMAIN_OPEN_CMD_BIT
final int Controllino_1.VMAIN_OPEN_CMD_BIT = 16 static private
Definition at line 35 of file Controllino_1.java.
Referenced by executeCommand().
VO_CLOSE_CMD_BIT
final int Controllino_1.VO_CLOSE_CMD_BIT = 13 static private
Definition at line 32 of file Controllino_1.java.
Referenced by executeCommand().
VO_CLOSE_STATUS_BIT
final int Controllino_1.VO_CLOSE_STATUS_BIT = 15 static private
Definition at line 34 of file Controllino_1.java.
Referenced by updateDeviceData().
VO_OPEN_CMD_BIT
final int Controllino_1.VO_OPEN_CMD_BIT = 12 static private
Definition at line 31 of file Controllino_1.java.
Referenced by executeCommand().
VO_OPEN_STATUS_BIT
final int Controllino_1.VO_OPEN_STATUS_BIT = 14 static private
Definition at line 33 of file Controllino_1.java.
Referenced by updateDeviceData().
VP1_CLOSE_CMD_BIT
final int Controllino_1.VP1_CLOSE_CMD_BIT = 9 static private
Definition at line 28 of file Controllino_1.java.
Referenced by executeCommand().
VP1_CLOSE_STATUS_BIT
final int Controllino_1.VP1_CLOSE_STATUS_BIT = 11 static private
Definition at line 30 of file Controllino_1.java.
Referenced by updateDeviceData().
VP1_OPEN_CMD_BIT
final int Controllino_1.VP1_OPEN_CMD_BIT = 8 static private
Definition at line 27 of file Controllino_1.java.
Referenced by executeCommand().
VP1_OPEN_STATUS_BIT
final int Controllino_1.VP1_OPEN_STATUS_BIT = 10 static private
Definition at line 29 of file Controllino_1.java.
Referenced by updateDeviceData().
VPI_CLOSE_CMD_BIT
final int Controllino_1.VPI_CLOSE_CMD_BIT = 5 static private
Definition at line 24 of file Controllino_1.java.
Referenced by executeCommand().
VPI_CLOSE_STATUS_BIT
final int Controllino_1.VPI_CLOSE_STATUS_BIT = 7 static private
Definition at line 26 of file Controllino_1.java.
Referenced by updateDeviceData().
VPI_OPEN_CMD_BIT
final int Controllino_1.VPI_OPEN_CMD_BIT = 4 static private
Definition at line 23 of file Controllino_1.java.
Referenced by executeCommand().
VPI_OPEN_STATUS_BIT
final int Controllino_1.VPI_OPEN_STATUS_BIT = 6 static private
Definition at line 25 of file Controllino_1.java.
Referenced by updateDeviceData().
VPO_CLOSE_CMD_BIT
final int Controllino_1.VPO_CLOSE_CMD_BIT = 1 static private
Definition at line 20 of file Controllino_1.java.
Referenced by executeCommand().
VPO_CLOSE_STATUS_BIT
final int Controllino_1.VPO_CLOSE_STATUS_BIT = 3 static private
Definition at line 22 of file Controllino_1.java.
Referenced by updateDeviceData().
VPO_OPEN_CMD_BIT
final int Controllino_1.VPO_OPEN_CMD_BIT = 0 static private
Definition at line 19 of file Controllino_1.java.
Referenced by executeCommand().
VPO_OPEN_STATUS_BIT
final int Controllino_1.VPO_OPEN_STATUS_BIT = 2 static private
Definition at line 21 of file Controllino_1.java.
Referenced by updateDeviceData().
VRP_CLOSE_CMD_BIT
final int Controllino_1.VRP_CLOSE_CMD_BIT = 5 static private
Definition at line 24 of file Controllino_1.java.
Referenced by executeCommand().
VRP_CLOSE_STATUS_BIT
final int Controllino_1.VRP_CLOSE_STATUS_BIT = 7 static private
Definition at line 26 of file Controllino_1.java.
Referenced by updateDeviceData().
VRP_OPEN_CMD_BIT
final int Controllino_1.VRP_OPEN_CMD_BIT = 4 static private
Definition at line 23 of file Controllino_1.java.
Referenced by executeCommand().
VRP_OPEN_STATUS_BIT
final int Controllino_1.VRP_OPEN_STATUS_BIT = 6 static private
Definition at line 25 of file Controllino_1.java.
Referenced by updateDeviceData().
VSOFT_CLOSE_CMD_BIT
final int Controllino_1.VSOFT_CLOSE_CMD_BIT = 21 static private
Definition at line 40 of file Controllino_1.java.
Referenced by executeCommand().
VSOFT_OPEN_CMD_BIT
final int Controllino_1.VSOFT_OPEN_CMD_BIT = 20 static private
Definition at line 39 of file Controllino_1.java.
Referenced by executeCommand().
VVENTING_CLOSE_CMD_BIT
final int Controllino_1.VVENTING_CLOSE_CMD_BIT = 29 static private
Definition at line 48 of file Controllino_1.java.
Referenced by executeCommand().
VVENTING_CLOSE_STATUS_BIT
final int Controllino_1.VVENTING_CLOSE_STATUS_BIT = 31 static private
Definition at line 50 of file Controllino_1.java.
Referenced by updateDeviceData().
VVENTING_OPEN_CMD_BIT
final int Controllino_1.VVENTING_OPEN_CMD_BIT = 28 static private
Definition at line 47 of file Controllino_1.java.
Referenced by executeCommand().
VVENTING_OPEN_STATUS_BIT
final int Controllino_1.VVENTING_OPEN_STATUS_BIT = 30 static private
Definition at line 49 of file Controllino_1.java.
Referenced by updateDeviceData().
The documentation for this class was generated from the following file:
work_cryo/Controllino_1.java