SCADARPI API: Device Class Reference
Device Class Reference abstract
Inherits DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, DataTypes, DataManager, Runnable, and DataTypes.
Inherited by Chiller, Controllino, Controllino, Controllino_1, Controllino_1, Controllino_1, Controllino_1, Controllino_1, Controllino_1, Controllino_1, Controllino_1, Controllino_1, Controllino_1, Controllino_1, Controllino_2, Controllino_2, Controllino_2, Controllino_2, Controllino_2, Controllino_2, Controllino_2, Controllino_2, Controllino_3, Controllino_3, Controllino_3, Controllino_3, Controllino_3, Controllino_3, Controllino_3, Controllino_3, DS2438, FlowMeterModbusMaster, FlowMeterModbusMaster, IntesisBox, IonicAgilentDual, IonicAgilentDual, LakeShore, MaxiGauge, MaxiGauge, MaxiGauge, MaxiGauge, MaxiGauge, MaxiGauge, MaxiGauge, MaxiGauge, MaxiGauge, MaxiGauge, MaxiGauge, MksRotor, PCounterMasterRTU, PWM, RgaHidenHal201RC, RgaHidenHal201RC, RgaPfeifferQms200, RgaPfeifferQms200, RgaPfeifferQms200, RgaPfeifferQms200, Sicem, SupervisorClient, SupervisorClient, SupervisorClient, SupervisorClient, SupervisorClient, SupervisorClient, SupervisorClient, SupervisorClient, SupervisorClient, SupervisorClient2, SupervisorClient2, SupervisorClient2, SupervisorClient2, SupervisorClient2, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TitaneVarianTSP_22, TitaneVarianTSP_22, TitaneVarianTSP_32, TitaneVarianTSP_32, TurboPfeifferDCU, TurboPfeifferDCU, TurboPfeifferDCU, TurboPfeifferDCU, TurboPfeifferDCU, TurboPfeifferDCU, TurboPfeifferDCU, TurboPfeifferDCU, TurboVarianV81AG, TurboVarianV81AG, TurboVarianV81AG, TurboVarianV81AG, Vacuum, VentingOperationController, XGSGauge, XGSGauge, and XGSGauge.
Public Member Functions
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
abstract void executeCommand (DataElement e)
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
abstract void updateDeviceData ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Public Attributes
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes
static final GpioController gpio = initGpioController()
Static Private Member Functions
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
Private Attributes
Thread thread
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 18 of file Device.java.
Member Function Documentation
addModbusCommand() [1/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
Referenced by ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegister().
addModbusCommand() [2/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [3/22]
void Device.addModbusCommand ()
Definition at line 93 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [4/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [5/22]
void Device.addModbusCommand ()
Definition at line 92 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [6/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [7/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [8/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [9/22]
void Device.addModbusCommand ()
Definition at line 90 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [10/22]
void Device.addModbusCommand ()
Definition at line 92 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [11/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [12/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [13/22]
void Device.addModbusCommand ()
Definition at line 93 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [14/22]
void Device.addModbusCommand ()
Definition at line 62 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [15/22]
void Device.addModbusCommand ()
Definition at line 92 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [16/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [17/22]
void Device.addModbusCommand ()
Definition at line 71 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [18/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [19/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [20/22]
void Device.addModbusCommand ()
Definition at line 92 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [21/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
addModbusCommand() [22/22]
void Device.addModbusCommand ()
Definition at line 91 of file Device.java.
References commandSetQueue, DataManager.dataList, DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
doStart() [1/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
Referenced by Main.main().
doStart() [2/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [3/22]
void Device.doStart ()
Definition at line 59 of file Device.java.
References thread.
doStart() [4/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [5/22]
void Device.doStart ()
Definition at line 57 of file Device.java.
References thread.
doStart() [6/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [7/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [8/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [9/22]
void Device.doStart ()
Definition at line 55 of file Device.java.
References thread.
doStart() [10/22]
void Device.doStart ()
Definition at line 57 of file Device.java.
References thread.
doStart() [11/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [12/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [13/22]
void Device.doStart ()
Definition at line 58 of file Device.java.
References thread.
doStart() [14/22]
void Device.doStart ()
Definition at line 30 of file Device.java.
References thread.
doStart() [15/22]
void Device.doStart ()
Definition at line 57 of file Device.java.
References thread.
doStart() [16/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [17/22]
void Device.doStart ()
Definition at line 36 of file Device.java.
References thread.
doStart() [18/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [19/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [20/22]
void Device.doStart ()
Definition at line 57 of file Device.java.
References thread.
doStart() [21/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStart() [22/22]
void Device.doStart ()
Definition at line 56 of file Device.java.
References thread.
doStop() [1/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [2/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [3/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 64 of file Device.java.
References thread.
doStop() [4/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [5/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 62 of file Device.java.
References thread.
doStop() [6/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [7/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [8/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [9/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 60 of file Device.java.
References thread.
doStop() [10/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 62 of file Device.java.
References thread.
doStop() [11/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [12/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [13/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 63 of file Device.java.
References thread.
doStop() [14/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 35 of file Device.java.
References thread.
doStop() [15/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 62 of file Device.java.
References thread.
doStop() [16/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [17/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 41 of file Device.java.
References thread.
doStop() [18/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [19/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [20/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 62 of file Device.java.
References thread.
doStop() [21/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
doStop() [22/22]
void Device.doStop ()
Reimplemented in PWM, and DS2438.
Definition at line 61 of file Device.java.
References thread.
executeCommand() [1/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
Referenced by popCommand().
executeCommand() [2/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [3/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [4/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [5/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [6/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [7/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [8/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [9/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [10/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [11/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [12/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [13/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [14/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [15/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [16/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [17/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [18/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [19/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [20/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [21/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
executeCommand() [22/22]
abstract void Device.executeCommand (DataElement e) abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
initGpioController() [1/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [2/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [3/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 41 of file Device.java.
References logger.
initGpioController() [4/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [5/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 39 of file Device.java.
References logger.
initGpioController() [6/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [7/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [8/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [9/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [10/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 39 of file Device.java.
References logger.
initGpioController() [11/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [12/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [13/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 40 of file Device.java.
References logger.
initGpioController() [14/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 39 of file Device.java.
References logger.
initGpioController() [15/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [16/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [17/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [18/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 39 of file Device.java.
References logger.
initGpioController() [19/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
initGpioController() [20/20]
static GpioController Device.initGpioController () static private
Reimplemented in TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, TCMuxShield, and TCMuxShield.
Definition at line 38 of file Device.java.
References logger.
popCommand() [1/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
Referenced by SupervisorClient.updateDeviceData(), SupervisorClient2.updateDeviceData(), IntesisBox.updateDeviceData(), PWM.updateDeviceData(), Controllino_1.updateDeviceData(), MaxiGauge.updateDeviceData(), TurboVarianV81AG.updateDeviceData(), Chiller.updateDeviceData(), Controllino_2.updateDeviceData(), LakeShore.updateDeviceData(), FlowMeterModbusMaster.updateDeviceData(), Controllino_3.updateDeviceData(), RgaHidenHal201RC.updateDeviceData(), TurboPfeifferDCU.updateDeviceData(), Controllino.updateDeviceData(), PCounterMasterRTU.updateDeviceData(), IonicAgilentDual.updateDeviceData(), RgaPfeifferQms200.updateDeviceData(), TitaneVarianTSP_22.updateDeviceData(), TitaneVarianTSP_32.updateDeviceData(), XGSGauge.updateDeviceData(), Vacuum.updateDeviceData(), MksRotor.updateDeviceData(), Sicem.updateDeviceData(), and VentingOperationController.updateDeviceData().
popCommand() [2/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [3/22]
void Device.popCommand ()
Definition at line 70 of file Device.java.
References commandSetQueue, executeCommand(), logger, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [4/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [5/22]
void Device.popCommand ()
Definition at line 68 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [6/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [7/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [8/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [9/22]
void Device.popCommand ()
Definition at line 66 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [10/22]
void Device.popCommand ()
Definition at line 68 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [11/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [12/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [13/22]
void Device.popCommand ()
Definition at line 69 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [14/22]
void Device.popCommand ()
Definition at line 41 of file Device.java.
References commandSetQueue, executeCommand(), logger, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [15/22]
void Device.popCommand ()
Definition at line 68 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [16/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [17/22]
void Device.popCommand ()
Definition at line 47 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [18/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [19/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [20/22]
void Device.popCommand ()
Definition at line 68 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [21/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
popCommand() [22/22]
void Device.popCommand ()
Definition at line 67 of file Device.java.
References commandSetQueue, executeCommand(), DataManager.holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.name, DataElement.setvalue, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
run() [1/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, name, and updateDeviceData().
run() [2/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, name, and updateDeviceData().
run() [3/22]
void Device.run ()
Definition at line 157 of file Device.java.
References delay, logger, mutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [4/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [5/22]
void Device.run ()
Definition at line 161 of file Device.java.
References logger, modbusmutex, name, pause, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [6/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [7/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [8/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [9/22]
void Device.run ()
Definition at line 158 of file Device.java.
References logger, name, and updateDeviceData().
run() [10/22]
void Device.run ()
Definition at line 161 of file Device.java.
References logger, modbusmutex, name, sleepTime, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [11/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, name, and updateDeviceData().
run() [12/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [13/22]
void Device.run ()
Definition at line 164 of file Device.java.
References logger, modbusmutex, name, sleep_period, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [14/22]
void Device.run ()
Definition at line 129 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [15/22]
void Device.run ()
Definition at line 161 of file Device.java.
References logger, modbusmutex, name, sleepPeriod, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [16/22]
void Device.run ()
Definition at line 160 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [17/22]
void Device.run ()
Definition at line 144 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [18/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [19/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [20/22]
void Device.run ()
Definition at line 161 of file Device.java.
References logger, modbusmutex, name, pause, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [21/22]
void Device.run ()
Definition at line 160 of file Device.java.
References logger, modbusmutex, name, updateDeviceData(), and DataManager.updateModbusRegisters().
run() [22/22]
void Device.run ()
Definition at line 159 of file Device.java.
References logger, name, and updateDeviceData().
setErrorComStatus() [1/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
Referenced by Controllino_1.executeCommand(), MaxiGauge.executeCommand(), TurboVarianV81AG.executeCommand(), Controllino_2.executeCommand(), FlowMeterModbusMaster.executeCommand(), SupervisorClient.executeCommand(), Controllino_3.executeCommand(), TurboPfeifferDCU.executeCommand(), Controllino.executeCommand(), IonicAgilentDual.executeCommand(), RgaPfeifferQms200.executeCommand(), TitaneVarianTSP_22.executeCommand(), TitaneVarianTSP_32.executeCommand(), XGSGauge.executeCommand(), Vacuum.executeCommand(), MksRotor.executeCommand(), SupervisorClient.updateDeviceData(), SupervisorClient2.updateDeviceData(), DS2438.updateDeviceData(), IntesisBox.updateDeviceData(), Controllino_1.updateDeviceData(), MaxiGauge.updateDeviceData(), TurboVarianV81AG.updateDeviceData(), Chiller.updateDeviceData(), Controllino_2.updateDeviceData(), LakeShore.updateDeviceData(), TCMuxShield.updateDeviceData(), FlowMeterModbusMaster.updateDeviceData(), Controllino_3.updateDeviceData(), RgaHidenHal201RC.updateDeviceData(), TurboPfeifferDCU.updateDeviceData(), Controllino.updateDeviceData(), IonicAgilentDual.updateDeviceData(), RgaPfeifferQms200.updateDeviceData(), TitaneVarianTSP_22.updateDeviceData(), TitaneVarianTSP_32.updateDeviceData(), XGSGauge.updateDeviceData(), Vacuum.updateDeviceData(), MksRotor.updateDeviceData(), and Sicem.updateDeviceData().
setErrorComStatus() [2/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [3/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 143 of file Device.java.
References DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [4/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [5/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 144 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [6/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [7/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [8/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [9/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 141 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [10/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 144 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [11/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [12/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [13/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 145 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [14/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 112 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [15/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 144 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [16/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 143 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [17/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 121 of file Device.java.
References busmutex, DataTypes.DataType.COM_STATUS, gpio, hasWarned, i2c_out, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, use_i2c_out, and DataElement.value.
setErrorComStatus() [18/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [19/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [20/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 144 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [21/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataElement.name, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
setErrorComStatus() [22/22]
void Device.setErrorComStatus ()
Reimplemented in PCounterMasterRTU.
Definition at line 142 of file Device.java.
References DataTypes.DataType.COM_STATUS, hasWarned, DataTypes.DataType.READ_AND_WRITE_STATUS, DataTypes.DataType.READ_AND_WRITE_VALUE, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataElement.type, and DataElement.value.
updateDeviceData() [1/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
Referenced by run().
updateDeviceData() [2/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [3/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [4/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [5/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [6/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [7/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [8/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [9/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [10/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [11/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [12/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [13/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [14/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [15/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [16/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [17/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [18/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [19/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [20/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [21/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
updateDeviceData() [22/22]
abstract void Device.updateDeviceData () abstract
Reimplemented in SupervisorClient2, SupervisorClient, VentingOperationController, MaxiGauge, FlowMeterModbusMaster, Controllino_1, XGSGauge, TurboPfeifferDCU, TCMuxShield, Sicem, MksRotor, MaxiGauge, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, RgaPfeifferQms200, MaxiGauge, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, TCMuxShield, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino_3, Controllino_2, Controllino_1, Controllino_3, Controllino_2, Controllino_1, Vacuum, TurboPfeifferDCU, TCMuxShield, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TCMuxShield, RgaHidenHal201RC, Controllino_3, XGSGauge, TurboVarianV81AG, TurboPfeifferDCU, TitaneVarianTSP_32, TitaneVarianTSP_22, RgaPfeifferQms200, MaxiGauge, IonicAgilentDual, Controllino, TCMuxShield, PCounterMasterRTU, Controllino_3, Controllino_1, SupervisorClient, SupervisorClient2, SupervisorClient, Controllino, SupervisorClient2, SupervisorClient, TurboPfeifferDCU, TCMuxShield, SupervisorClient, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, TurboPfeifferDCU, TCMuxShield, SupervisorClient, RgaHidenHal201RC, MaxiGauge, Controllino_3, Controllino_2, Controllino_1, SupervisorClient, FlowMeterModbusMaster, TurboVarianV81AG, TCMuxShield, MaxiGauge, LakeShore, Controllino_2, Controllino_1, Chiller, TurboVarianV81AG, MaxiGauge, Controllino_1, PWM, IntesisBox, DS2438, SupervisorClient2, SupervisorClient, SupervisorClient2, and SupervisorClient.
Member Data Documentation
aliasName
String Device.aliasName
Definition at line 24 of file Device.java.
Referenced by GlgGui.createAndShowGui(), GlgPCounter2Gui.createAndShowGui(), GlgPCounterStatusDetailsGui.createAndShowGui(), and PCounterMasterRTU.PCounterMasterRTU().
busmutex
static final Lock Device.busmutex = new ReentrantLock(true) static
Definition at line 22 of file Device.java.
Referenced by setErrorComStatus(), Controllino_1.updateDeviceData(), Controllino_2.updateDeviceData(), Controllino_3.updateDeviceData(), and Controllino.updateDeviceData().
comErr
boolean Device.comErr = false protected
Definition at line 27 of file Device.java.
Referenced by DS2438.updateDeviceData(), and IntesisBox.updateDeviceData().
comm_cnt_failure
int Device.comm_cnt_failure = 0 protected
Definition at line 25 of file Device.java.
Referenced by Controllino_1.updateDeviceData(), Controllino_2.updateDeviceData(), Controllino_3.updateDeviceData(), Controllino.updateDeviceData(), PCounterMasterRTU.updateDeviceData(), and MaxiGauge.updateDeviceData().
comm_max_failure
int Device.comm_max_failure = 5 protected
Definition at line 26 of file Device.java.
Referenced by PCounterMasterRTU.PCounterMasterRTU(), Controllino_1.updateDeviceData(), Controllino_2.updateDeviceData(), Controllino_3.updateDeviceData(), Controllino.updateDeviceData(), PCounterMasterRTU.updateDeviceData(), and MaxiGauge.updateDeviceData().
commandSetQueue
LinkedList< DataElement > Device.commandSetQueue = new LinkedList<DataElement>()
Definition at line 28 of file Device.java.
Referenced by addModbusCommand(), GlgCryoIbDetStatusDetailsGui.InputListener.InputCallback(), GlgDryGui.InputListener.InputCallback(), GlgGaugeGui.InputListener.InputCallback(), GlgIonicGui.InputListener.InputCallback(), GlgRGAGui.InputListener.InputCallback(), GlgTitane_22Gui.InputListener.InputCallback(), GlgTitane_32Gui.InputListener.InputCallback(), GlgTurboGui.InputListener.InputCallback(), GlgValveGui.InputListener.InputCallback(), GlgXGSGaugeGui.InputListener.InputCallback(), GlgCryo1500wIntGui.InputListener.InputCallback(), GlgCryo1500wStatusDetailsGui.InputListener.InputCallback(), GlgLinkStatusDetailsGui.InputListener.InputCallback(), GlgRGA3Gui.InputListener.InputCallback(), GlgPCounter2Gui.InputListener.InputCallback(), GlgPCounterStatusDetailsGui.InputListener.InputCallback(), GlgRgaStatusDetailsGui.InputListener.InputCallback(), GlgSqzStatusDetailsGui.InputListener.InputCallback(), GlgSqzVacuumGui.InputListener.InputCallback(), GlgTitaneGui.InputListener.InputCallback(), GlgTurboPfeifferDCUGui.InputListener.InputCallback(), GlgTube1500wStatusDetailsGui.InputListener.InputCallback(), popCommand(), VentingTableView.pulseOperationCommand(), VentingOperations.sendFlowUsingStatusKey(), VentingOperations.sendPumpCommand(), VentingOperations.sendValveCommand(), Operation.setValue(), and Vacuum.updateDeviceData().
delay
int Device.delay
Definition at line 25 of file Device.java.
Referenced by DS2438.DS2438(), IntesisBox.IntesisBox(), PWM.PWM(), and run().
gpio [1/2]
final GpioController Device.gpio = initGpioController() protected
Definition at line 33 of file Device.java.
Referenced by Controllino_1.Controllino_1(), DS2438.doStop(), PWM.doStop(), DS2438.DS2438(), PWM.PWM(), setErrorComStatus(), Controllino_1.updateDeviceData(), Controllino_2.updateDeviceData(), and Controllino_3.updateDeviceData().
gpio [2/2]
final GpioController Device.gpio = initGpioController() static protected
Definition at line 39 of file Device.java.
hasWarned
boolean Device.hasWarned = false protected
Definition at line 24 of file Device.java.
Referenced by PCounterMasterRTU.PCounterMasterRTU(), setErrorComStatus(), PCounterMasterRTU.setErrorComStatus(), SupervisorClient.updateDeviceData(), SupervisorClient2.updateDeviceData(), Controllino_1.updateDeviceData(), MaxiGauge.updateDeviceData(), TurboVarianV81AG.updateDeviceData(), Chiller.updateDeviceData(), Controllino_2.updateDeviceData(), LakeShore.updateDeviceData(), TCMuxShield.updateDeviceData(), FlowMeterModbusMaster.updateDeviceData(), Controllino_3.updateDeviceData(), RgaHidenHal201RC.updateDeviceData(), TurboPfeifferDCU.updateDeviceData(), Controllino.updateDeviceData(), PCounterMasterRTU.updateDeviceData(), Vacuum.updateDeviceData(), IonicAgilentDual.updateDeviceData(), RgaPfeifferQms200.updateDeviceData(), TitaneVarianTSP_22.updateDeviceData(), TitaneVarianTSP_32.updateDeviceData(), XGSGauge.updateDeviceData(), MksRotor.updateDeviceData(), and Sicem.updateDeviceData().
i2c_in
GpioPinDigitalInput Device.i2c_in protected
Definition at line 34 of file Device.java.
Referenced by Controllino_1.updateDeviceData(), Controllino_2.updateDeviceData(), and Controllino_3.updateDeviceData().
i2c_out
GpioPinDigitalOutput Device.i2c_out protected
Definition at line 35 of file Device.java.
Referenced by Controllino_1.Controllino_1(), setErrorComStatus(), Controllino_1.updateDeviceData(), Controllino_2.updateDeviceData(), and Controllino_3.updateDeviceData().
logger
static final Logger Device.logger = Logger.getLogger("Main") static private
Definition at line 20 of file Device.java.
Referenced by addModbusCommand(), initGpioController(), popCommand(), and run().
modbusmutex
final Lock Device.modbusmutex = new ReentrantLock(true)
Definition at line 21 of file Device.java.
Referenced by run(), and ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegister().
mutex
final Lock Device.mutex = new ReentrantLock(true)
Definition at line 29 of file Device.java.
Referenced by run(), and ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegister().
name
String Device.name
Definition at line 23 of file Device.java.
Referenced by Chiller.Chiller(), Controllino.Controllino(), Controllino_1.Controllino_1(), Controllino_2.Controllino_2(), Controllino_3.Controllino_3(), DS2438.DS2438(), Controllino_1.executeCommand(), TurboVarianV81AG.executeCommand(), Controllino_2.executeCommand(), FlowMeterModbusMaster.executeCommand(), SupervisorClient.executeCommand(), Controllino_3.executeCommand(), RgaHidenHal201RC.executeCommand(), TurboPfeifferDCU.executeCommand(), Controllino.executeCommand(), RgaPfeifferQms200.executeCommand(), XGSGauge.executeCommand(), Vacuum.executeCommand(), TitaneVarianTSP_22.executeCommand(), TitaneVarianTSP_32.executeCommand(), Sicem.executeCommand(), FlowMeterModbusMaster.FlowMeterModbusMaster(), PCounterMasterRTU.getConfigFilePath(), Operation.getDeviceName(), Operation.getFlowMeter(), GlgValveGui.InputListener.InputCallback(), GlgGaugeGui.InputListener.InputCallback(), GlgTurboGui.InputListener.InputCallback(), GlgFlowMeterGui.InputListener.InputCallback(), IntesisBox.IntesisBox(), IonicAgilentDual.IonicAgilentDual(), LakeShore.LakeShore(), MaxiGauge.MaxiGauge(), MksRotor.MksRotor(), PCounterMasterRTU.PCounterMasterRTU(), PWM.PWM(), RgaHidenHal201RC.RgaHidenHal201RC(), RgaPfeifferQms200.RgaPfeifferQms200(), run(), Operation.setValue(), Sicem.Sicem(), SupervisorClient.SupervisorClient(), SupervisorClient2.SupervisorClient2(), TCMuxShield.TCMuxShield(), TitaneVarianTSP_22.TitaneVarianTSP_22(), TitaneVarianTSP_32.TitaneVarianTSP_32(), TurboPfeifferDCU.TurboPfeifferDCU(), TurboVarianV81AG.TurboVarianV81AG(), SupervisorClient.updateDeviceData(), SupervisorClient2.updateDeviceData(), DS2438.updateDeviceData(), IntesisBox.updateDeviceData(), Controllino_1.updateDeviceData(), MaxiGauge.updateDeviceData(), TurboVarianV81AG.updateDeviceData(), Chiller.updateDeviceData(), Controllino_2.updateDeviceData(), LakeShore.updateDeviceData(), TCMuxShield.updateDeviceData(), FlowMeterModbusMaster.updateDeviceData(), Controllino_3.updateDeviceData(), RgaHidenHal201RC.updateDeviceData(), TurboPfeifferDCU.updateDeviceData(), Controllino.updateDeviceData(), PCounterMasterRTU.updateDeviceData(), RgaPfeifferQms200.updateDeviceData(), XGSGauge.updateDeviceData(), Vacuum.updateDeviceData(), IonicAgilentDual.updateDeviceData(), TitaneVarianTSP_22.updateDeviceData(), TitaneVarianTSP_32.updateDeviceData(), MksRotor.updateDeviceData(), Sicem.updateDeviceData(), Vacuum.Vacuum(), VentingOperationController.VentingOperationController(), ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegister(), and XGSGauge.XGSGauge().
pause
int Device.pause = 1000 protected
Definition at line 37 of file Device.java.
Referenced by Chiller.Chiller(), run(), and Sicem.Sicem().
sleep_period
int Device.sleep_period = 1000 protected
Definition at line 28 of file Device.java.
Referenced by PCounterMasterRTU.PCounterMasterRTU(), and run().
sleepPeriod
int Device.sleepPeriod = 1000 protected
Definition at line 28 of file Device.java.
Referenced by RgaHidenHal201RC.RgaHidenHal201RC(), and run().
sleepTime
int Device.sleepTime = 1000 protected
Definition at line 28 of file Device.java.
Referenced by Controllino.Controllino(), and run().
thread
Thread Device.thread private
Definition at line 27 of file Device.java.
Referenced by doStart(), doStop(), DS2438.doStop(), and PWM.doStop().
use_i2c_out
boolean Device.use_i2c_out = false protected
Definition at line 36 of file Device.java.
Referenced by Controllino_1.Controllino_1(), Controllino_2.Controllino_2(), Controllino_3.Controllino_3(), and setErrorComStatus().
The documentation for this class was generated from the following file:
work_1500npanel/Device.java