SCADARPI API: DialogSetPoint Class Reference
DialogSetPoint Class Reference
Classes
class Keypad
Public Member Functions
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
DialogSetPoint (JFrame _parent, String _title, double initialValue, boolean _modal)
double getResultValue ()
boolean isOk ()
Static Public Member Functions
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
static void setComponentSize (JComponent component, int width, int height)
Protected Member Functions
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
void processWindowEvent (WindowEvent e)
Private Attributes
Vector< String > command
DataElement dataElement
Device device
String glgName
JButton jButtonOK = new JButton()
JLabel jLabelText = new JLabel()
RoundJTextField jTextField = new RoundJTextField(5)
boolean okPressed = false
JPanel panel
JFrame parent
double resultValue = 0.0
String title
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 34 of file DialogSetPoint.java.
Constructor & Destructor Documentation
DialogSetPoint() [1/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [2/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [3/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [4/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [5/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [6/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [7/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [8/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [9/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [10/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [11/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [12/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [13/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 47 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [14/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _glgName, Device _device, DataElement _dataElement, String _title, boolean _modal)
Definition at line 52 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, parent, and title.
DialogSetPoint() [15/15]
DialogSetPoint.DialogSetPoint (JFrame _parent, String _title, double initialValue, boolean _modal)
Definition at line 70 of file DialogSetPoint.java.
References dataElement, device, glgName, jButtonOK, jTextField, parent, and title.
Member Function Documentation
getResultValue()
double DialogSetPoint.getResultValue ()
Definition at line 206 of file DialogSetPoint.java.
Referenced by VentingTableView.editNumericCellWithKeypad().
isOk()
boolean DialogSetPoint.isOk ()
Definition at line 202 of file DialogSetPoint.java.
Referenced by VentingTableView.editNumericCellWithKeypad().
processWindowEvent() [1/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [2/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [3/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [4/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [5/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 133 of file DialogSetPoint.java.
processWindowEvent() [6/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [7/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [8/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [9/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [10/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [11/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [12/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 138 of file DialogSetPoint.java.
processWindowEvent() [13/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 133 of file DialogSetPoint.java.
processWindowEvent() [14/14]
void DialogSetPoint.processWindowEvent (WindowEvent e) protected
Definition at line 186 of file DialogSetPoint.java.
setComponentSize() [1/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [2/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [3/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [4/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [5/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 115 of file DialogSetPoint.java.
setComponentSize() [6/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [7/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [8/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [9/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [10/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [11/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [12/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 120 of file DialogSetPoint.java.
setComponentSize() [13/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 115 of file DialogSetPoint.java.
setComponentSize() [14/14]
static void DialogSetPoint.setComponentSize (JComponent component, int width, int height) static
Definition at line 153 of file DialogSetPoint.java.
Member Data Documentation
command
Vector< String > DialogSetPoint.command private
Definition at line 45 of file DialogSetPoint.java.
dataElement
DataElement DialogSetPoint.dataElement private
Definition at line 44 of file DialogSetPoint.java.
Referenced by DialogSetPoint().
device
Device DialogSetPoint.device private
Definition at line 43 of file DialogSetPoint.java.
Referenced by DialogSetPoint().
glgName
String DialogSetPoint.glgName private
Definition at line 42 of file DialogSetPoint.java.
Referenced by DialogSetPoint().
jButtonOK
JButton DialogSetPoint.jButtonOK = new JButton() private
Definition at line 39 of file DialogSetPoint.java.
Referenced by DialogSetPoint().
jLabelText
JLabel DialogSetPoint.jLabelText = new JLabel() private
Definition at line 38 of file DialogSetPoint.java.
jTextField
RoundJTextField DialogSetPoint.jTextField = new RoundJTextField(5) private
Definition at line 37 of file DialogSetPoint.java.
Referenced by DialogSetPoint().
logger
static final Logger DialogSetPoint.logger = Logger.getLogger("Main") static private
Definition at line 35 of file DialogSetPoint.java.
okPressed
boolean DialogSetPoint.okPressed = false private
Definition at line 47 of file DialogSetPoint.java.
panel
JPanel DialogSetPoint.panel private
Definition at line 36 of file DialogSetPoint.java.
parent
JFrame DialogSetPoint.parent private
Definition at line 40 of file DialogSetPoint.java.
Referenced by DialogSetPoint().
resultValue
double DialogSetPoint.resultValue = 0.0 private
Definition at line 48 of file DialogSetPoint.java.
title
String DialogSetPoint.title private
Definition at line 41 of file DialogSetPoint.java.
Referenced by DialogSetPoint().
The documentation for this class was generated from the following file:
work_cryo/DialogSetPoint.java