SCADARPI API: VentingOperations Class Reference
VentingOperations Class Reference
Executes the venting sequence defined in the 'operations' table.
Classes
class Step
Public Member Functions
void requestStop ()
void run ()
VentingOperations (DeviceManager deviceManager, TableModel model, String g2StatusKey, String mks2000StatusKey, String mks50000StatusKey, String stepStatusKey, JTable table)
Private Member Functions
List< Step > buildStepsFromModel (TableModel model)
DataElement getG2DataElement ()
void highlightRow (int rowIndex)
void sendFlowUsingStatusKey (String mapping, double flow)
void sendMksCommands (Step step)
void sendPumpCommand (String cmdName, String state)
void sendValveCommand (String cmdName, String state)
void setOperationStep (int step)
boolean waitForPressure (double target)
Wait until G2 >= target.
Static Private Member Functions
static double toDouble (Object o, double def)
static int toInt (Object o, int def)
static String toString (Object o)
Private Attributes
final DeviceManager deviceManager
final String g2StatusKey
final String mks2000StatusKey
final String mks50000StatusKey
final List< Step > steps
final String stepStatusKey
volatile boolean stopRequested = false
final JTable table
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Executes the venting sequence defined in the 'operations' table.
One step = one row in the table: STEP, P1, V1, VSOFT, VMAIN, VDRYER, VRP, MKS2000, MKS50000, G2
For each step (in increasing STEP order): 1) Set MKS2000 / MKS50000 setpoints 2) Set valves (V1, VSOFT, VMAIN, VDRYER, VRP) 3) Set pump P1 (ON/OFF) 4) Wait until G2 (chamber pressure) reaches target from that row
Definition at line 20 of file VentingOperations.java.
Constructor & Destructor Documentation
VentingOperations()
VentingOperations.VentingOperations (DeviceManager deviceManager, TableModel model, String g2StatusKey, String mks2000StatusKey, String mks50000StatusKey, String stepStatusKey, JTable table)
Definition at line 48 of file VentingOperations.java.
References buildStepsFromModel(), deviceManager, g2StatusKey, mks2000StatusKey, mks50000StatusKey, stepStatusKey, and table.
Member Function Documentation
buildStepsFromModel()
List<Step> VentingOperations.buildStepsFromModel (TableModel model) private
Definition at line 139 of file VentingOperations.java.
References logger, toDouble(), toInt(), and toString().
Referenced by VentingOperations().
getG2DataElement()
DataElement VentingOperations.getG2DataElement () private
Definition at line 349 of file VentingOperations.java.
References deviceManager, g2StatusKey, DataManager.getDataElement(), and logger.
Referenced by waitForPressure().
highlightRow()
void VentingOperations.highlightRow (int rowIndex) private
Definition at line 120 of file VentingOperations.java.
References VentingLookAndFeel.setActiveRow(), and table.
Referenced by run().
requestStop()
void VentingOperations.requestStop ()
Definition at line 64 of file VentingOperations.java.
References stopRequested.
run()
void VentingOperations.run ()
Definition at line 69 of file VentingOperations.java.
References highlightRow(), logger, sendMksCommands(), sendPumpCommand(), sendValveCommand(), setOperationStep(), steps, stopRequested, and waitForPressure().
Referenced by VentingTableView.startVentingSequence().
sendFlowUsingStatusKey()
void VentingOperations.sendFlowUsingStatusKey (String mapping, double flow) private
Definition at line 273 of file VentingOperations.java.
References Device.commandSetQueue, deviceManager, DataManager.getDataElement(), logger, and DataElement.setvalue.
Referenced by sendMksCommands().
sendMksCommands()
void VentingOperations.sendMksCommands (Step step) private
Definition at line 261 of file VentingOperations.java.
References mks2000StatusKey, mks50000StatusKey, and sendFlowUsingStatusKey().
Referenced by run().
sendPumpCommand()
void VentingOperations.sendPumpCommand (String cmdName, String state) private
Definition at line 195 of file VentingOperations.java.
References Device.commandSetQueue, deviceManager, DataManager.getDataElement(), logger, and DataElement.setvalue.
Referenced by run().
sendValveCommand()
void VentingOperations.sendValveCommand (String cmdName, String state) private
Definition at line 228 of file VentingOperations.java.
References Device.commandSetQueue, deviceManager, DataManager.getDataElement(), logger, and DataElement.setvalue.
Referenced by run().
setOperationStep()
void VentingOperations.setOperationStep (int step) private
Definition at line 365 of file VentingOperations.java.
References deviceManager, DataManager.getDataElement(), logger, stepStatusKey, and DataElement.value.
Referenced by run().
toDouble()
static double VentingOperations.toDouble (Object o, double def) static private
Definition at line 183 of file VentingOperations.java.
Referenced by buildStepsFromModel().
toInt()
static int VentingOperations.toInt (Object o, int def) static private
Definition at line 173 of file VentingOperations.java.
Referenced by buildStepsFromModel().
toString()
static String VentingOperations.toString (Object o) static private
Definition at line 169 of file VentingOperations.java.
Referenced by buildStepsFromModel().
waitForPressure()
boolean VentingOperations.waitForPressure (double target) private
Wait until G2 >= target.
Returns
true if stop was requested / interrupted, false otherwise.
Definition at line 304 of file VentingOperations.java.
References getG2DataElement(), logger, stopRequested, and DataElement.value.
Referenced by run().
Member Data Documentation
deviceManager
final DeviceManager VentingOperations.deviceManager private
Definition at line 24 of file VentingOperations.java.
Referenced by getG2DataElement(), sendFlowUsingStatusKey(), sendPumpCommand(), sendValveCommand(), setOperationStep(), and VentingOperations().
g2StatusKey
final String VentingOperations.g2StatusKey private
Definition at line 26 of file VentingOperations.java.
Referenced by getG2DataElement(), and VentingOperations().
logger
final Logger VentingOperations.logger = Logger.getLogger("Main") static private
Definition at line 22 of file VentingOperations.java.
Referenced by buildStepsFromModel(), getG2DataElement(), run(), sendFlowUsingStatusKey(), sendPumpCommand(), sendValveCommand(), setOperationStep(), and waitForPressure().
mks2000StatusKey
final String VentingOperations.mks2000StatusKey private
Definition at line 27 of file VentingOperations.java.
Referenced by sendMksCommands(), and VentingOperations().
mks50000StatusKey
final String VentingOperations.mks50000StatusKey private
Definition at line 28 of file VentingOperations.java.
Referenced by sendMksCommands(), and VentingOperations().
steps
final List<Step> VentingOperations.steps private
Definition at line 25 of file VentingOperations.java.
Referenced by run().
stepStatusKey
final String VentingOperations.stepStatusKey private
Definition at line 29 of file VentingOperations.java.
Referenced by setOperationStep(), and VentingOperations().
stopRequested
volatile boolean VentingOperations.stopRequested = false private
Definition at line 31 of file VentingOperations.java.
Referenced by requestStop(), run(), and waitForPressure().
table
final JTable VentingOperations.table private
Definition at line 30 of file VentingOperations.java.
Referenced by highlightRow(), and VentingOperations().
The documentation for this class was generated from the following file:
work_venting/VentingOperations.java