SCADARPI API: GlgGui Class Reference
GlgGui Class Reference
Inherits JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, DataTypes, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, DataTypes, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, DataTypes, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, DataTypes, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, Runnable, JFrame, ChannelList, DataTypes, Runnable, JFrame, ChannelList, DataTypes, Runnable, JFrame, ChannelList, and Runnable.
Classes
class InputListener
Public Member Functions
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
void exitProgram ()
GlgGui (DeviceManager _deviceManager, Operation _op2000, Operation _op50000, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (DeviceManager _deviceManager, String _title)
GlgGui (Operation _op, String _title)
GlgGui (Operation _op, String _title)
GlgGui (Operation _op, String _title)
GlgGui (Operation _op, String _title)
void loadURL1 ()
void loadURL1 ()
void loadURL1 ()
void loadURL1 ()
void loadURL1 ()
void loadURL2 ()
void loadURL2 ()
void loadURL2 ()
void loadURL2 ()
void loadURL2 ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateGui ()
void updateStrings ()
void updateStrings ()
void updateStrings ()
Public Attributes
boolean isSuspended = false
Operation op2000
GlgGui parent
Hashtable< String, GlgChildGui > subwindows
Public Attributes inherited from ChannelList
Hashtable< Integer, GlgPoint > ACColorSTATUS
Hashtable< Integer, String > ACSTATUS
Hashtable< Integer, GlgPoint > BypassColorSTATUS
Hashtable< Integer, String > BypassSTATUS
Hashtable< String, String > CRYO1500WCMD
Hashtable< String, String > Cryo1500wIntCMD
Hashtable< String, String > Cryo1500wIntStatus
Hashtable< String, String > CRYO1500WSTATUS
Hashtable< String, String > Cryo1500wStatusDetails
Hashtable< String, String > Cryo1500wTemp
Hashtable< String, String > CRYOIBDETCMD
Hashtable< String, String > CRYOIBDETSTATUS
Hashtable< String, String > CryoIbDetStatusDetails
Hashtable< Integer, GlgPoint > FailOkColorSTATUS
Hashtable< Integer, String > FailOkSTATUS
Hashtable< Integer, GlgPoint > FanColorSTATUS
Hashtable< Integer, GlgPoint > FanSpeedColorSTATUS
Hashtable< Integer, String > FanSpeedSTATUS
Hashtable< Integer, String > FanSTATUS
Hashtable< String, String > FLOWMETERCMD
Hashtable< String, String > FLOWMETERSTATUS
Hashtable< String, String > FlowMeterStatusDetails
Hashtable< String, String > FlowMeterTemp
Hashtable< Integer, GlgPoint > GaugeColorSTATUS
Hashtable< Integer, GlgPoint > GaugePressureColorSTATUS
Hashtable< Integer, String > GaugePressureSTATUS
Hashtable< Integer, String > GaugeSTATUS
Hashtable< Integer, GlgPoint > IonicONOFFColorSTATUS
Hashtable< Integer, String > IonicONOFFSTATUS
Hashtable< Integer, GlgPoint > IonicOperatingModeColorSTATUS
Hashtable< Integer, String > IonicOperatingModeSTATUS
Hashtable< Integer, GlgPoint > IonicRemoteColorSTATUS
Hashtable< Integer, String > IonicRemoteSTATUS
Hashtable< Integer, GlgPoint > IonicVoltageModeColorSTATUS
Hashtable< Integer, String > IonicVoltageModeSTATUS
Hashtable< Integer, GlgPoint > IPSColorSTATUS
Hashtable< Integer, String > IPSSTATUS
Hashtable< String, String > LINKCMD
Hashtable< String, String > LINKSTATUS
Hashtable< String, String > LinkStatusDetails
Hashtable< String, String > LinkTemp
String mainDrawing = "Station.g"
String mainDrawing1 = "PARTICLECOUNTER.g"
String mainDrawing2 = "GAUGE.g"
Hashtable< Integer, GlgPoint > MksComColorSTATUS
Hashtable< Integer, String > MksComSTATUS
Hashtable< Integer, GlgPoint > OkFailColorSTATUS
Hashtable< Integer, String > OkFailSTATUS
Hashtable< String, String > PANEL1STATUS
Hashtable< String, String > PANEL2STATUS
Hashtable< String, String > PANELCMD
Hashtable< String, String > PANELSTATUS
Hashtable< String, String > PCOUNTER2CMD
Hashtable< String, String > PCOUNTER2STATUS
Hashtable< String, String > PCOUNTERCMD
Hashtable< Integer, GlgPoint > PCounterColorCOMSTATUS
Hashtable< Integer, GlgPoint > PCounterColorFLAGSTATUS
Hashtable< Integer, GlgPoint > PCounterColorINSTRSTATUS
Hashtable< Integer, GlgPoint > PCounterColorSTATUS
Hashtable< Integer, String > PCounterCOMSTATUS
Hashtable< Integer, String > PCounterFLAGSTATUS
Hashtable< Integer, String > PCounterINSTRSTATUS
Hashtable< Integer, GlgPoint > PCounterMobileColorFLAGSTATUS
Hashtable< Integer, GlgPoint > PCounterMobileColorSTATUS
Hashtable< Integer, String > PCounterMobileFLAGSTATUS
Hashtable< Integer, String > PCounterMobileSTATUS
Hashtable< String, String > PCOUNTERMOBSTATUS
Hashtable< Integer, String > PCounterSTATUS
Hashtable< String, String > PCOUNTERSTATUS
Hashtable< String, String > PCounterStatusDetails
Hashtable< String, String > PCounterTemp
Hashtable< Integer, GlgPoint > PumpColorSTATUS
Hashtable< Integer, String > PumpSTATUS
Hashtable< Integer, GlgPoint > PushO2ColorSTATUS
Hashtable< Integer, GlgPoint > RearmColorSTATUS
Hashtable< Integer, String > RearmSTATUS
Hashtable< Integer, GlgPoint > RelayGeneralColorSTATUS
Hashtable< Integer, String > RelayGeneralSTATUS
Hashtable< Integer, GlgPoint > RelayO2ColorSTATUS
Hashtable< String, String > RGACMD
Hashtable< Integer, String > RGADegasONOFFSTATUS
Hashtable< Integer, String > RGAEmissionONOFFSTATUS
Hashtable< Integer, GlgPoint > RGAFilamentColorSTATUS
Hashtable< Integer, String > RGAFilamentSTATUS
Hashtable< Integer, String > RGAMODESTATUS
Hashtable< Integer, GlgPoint > RGAONOFFColorSTATUS
Hashtable< Integer, String > RGAOperationONOFFSTATUS
Hashtable< Integer, String > RGARunningONOFFSTATUS
Hashtable< String, String > RGASTATUS
Hashtable< String, String > RgaStatusDetails
Hashtable< String, String > RgaTemp
Hashtable< Integer, GlgPoint > ROTGaugeEmissionColorSTATUS
Hashtable< Integer, String > ROTGaugeEmissionSTATUS
Hashtable< Integer, GlgPoint > SensorO2ColorSTATUS
Hashtable< String, String > SQZCMD
Hashtable< String, String > SQZSTATUS
Hashtable< String, String > SqzStatusDetails
Hashtable< String, String > SqzTemp
Hashtable< String, String > STATIONCMD
Hashtable< String, String > STATIONSTATUS
Hashtable< String, String > TCMuxTemp
Hashtable< Integer, GlgPoint > TitaneAutoStartModeColorSTATUS
Hashtable< Integer, String > TitaneAutoStartModeSTATUS
Hashtable< Integer, GlgPoint > TitaneControllerColorSTATUS
Hashtable< Integer, GlgPoint > TitaneControllerOperatingModeColorSTATUS
Hashtable< Integer, String > TitaneControllerOperatingModeSTATUS
Hashtable< Integer, String > TitaneControllerSTATUS
Hashtable< Integer, GlgPoint > TitaneErrorColorSTATUS
Hashtable< Integer, String > TitaneErrorSTATUS
Hashtable< Integer, GlgPoint > TitaneFilamentColorSTATUS
Hashtable< Integer, String > TitaneFilamentSTATUS
Hashtable< Integer, GlgPoint > TitaneOperatingModeColorSTATUS
Hashtable< Integer, String > TitaneOperatingModeSTATUS
Hashtable< Integer, GlgPoint > TitaneRecoverModeColorSTATUS
Hashtable< Integer, String > TitaneRecoverModeSTATUS
Hashtable< Integer, GlgPoint > TitaneRemoteColorSTATUS
Hashtable< Integer, String > TitaneRemoteSTATUS
Hashtable< Integer, GlgPoint > TitaneStartColorSTATUS
Hashtable< Integer, String > TitaneStartSTATUS
Hashtable< String, String > TUBE1500WCMD
Hashtable< String, String > TUBE1500WSTATUS
Hashtable< String, String > Tube1500wStatusDetails
Hashtable< String, String > TUBECMD
Hashtable< String, String > TUBESTATUS
Hashtable< String, String > TubeStatusDetails
Hashtable< Integer, GlgPoint > Turbo1ErrorColorSTATUS
Hashtable< Integer, String > Turbo1ErrorSTATUS
Hashtable< Integer, GlgPoint > Turbo2ErrorColorSTATUS
Hashtable< Integer, String > Turbo2ErrorSTATUS
Hashtable< Integer, GlgPoint > Turbo3ErrorColorSTATUS
Hashtable< Integer, String > Turbo3ErrorSTATUS
Hashtable< Integer, GlgPoint > TurboONOFFColorSTATUS
Hashtable< Integer, String > TurboONOFFSTATUS
Hashtable< Integer, GlgPoint > TurboStandbyColorSTATUS
Hashtable< Integer, String > TurboStandbySTATUS
Hashtable< Integer, GlgPoint > TurboTemperatureBoxColorSTATUS
Hashtable< Integer, String > TurboTemperatureBoxSTATUS
Hashtable< Integer, GlgPoint > TurboTemperatureColorSTATUS
Hashtable< Integer, String > TurboTemperatureSTATUS
Hashtable< Integer, GlgPoint > VacuumColorSTATUS
Hashtable< Integer, GlgPoint > VacuumComColorSTATUS
Hashtable< Integer, String > VacuumComSTATUS
Hashtable< Integer, String > VacuumSTATUS
Hashtable< Integer, GlgPoint > ValveColorSTATUS
Hashtable< Integer, String > ValveSTATUS
Hashtable< String, String > VENTINGCMD
Hashtable< String, String > VENTINGSTATUS
Hashtable< String, String > VENTINGVIEWSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeDegasColorSTATUS
Hashtable< Integer, String > XGSGaugeDegasSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeEmissionColorSTATUS
Hashtable< Integer, String > XGSGaugeEmissionSTATUS
Hashtable< Integer, GlgPoint > XGSGaugeFilamentColorSTATUS
Hashtable< Integer, String > XGSGaugeFilamentSTATUS
Private Member Functions
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createAndShowGui ()
void createVacScene ()
void createVacScene ()
void createVacScene ()
void createVacScene ()
void createVacScene ()
void createWebScene ()
void createWebScene ()
void createWebScene ()
void createWebScene ()
void createWebScene ()
void initVacComponents ()
void initVacComponents ()
void initVacComponents ()
void initVacComponents ()
void initVacComponents ()
void initWebComponents ()
void initWebComponents ()
void initWebComponents ()
void initWebComponents ()
void initWebComponents ()
String resolveDbUrl ()
Private Attributes
boolean CleanOKst = true
String CleanStr = ""
Container content
String dbUrl
boolean DetOKst = true
String DetStr = ""
DeviceManager deviceManager
WebEngine engine1
WebEngine engine2
SimpleDateFormat formatter = new SimpleDateFormat("EEE, dd-MMM-yyyy HH:mm:ss")
boolean GeneralOKst = true
String GeneralStr = ""
GlgJLWBean glg_bean
GlgJLWBean glg_bean1
GlgJLWBean glg_bean2
boolean InjOKst = true
String InjStr = ""
boolean isVimLoaded = true
JFXPanel jfxPanel1
JFXPanel jfxPanel2
JFXPanel jfxPanel3
long lastTime = 0
boolean NEBaseOKst = true
String NEBaseStr = ""
boolean NECleanOKst = true
String NECleanStr = ""
boolean NECryoOKst = true
String NECryoStr = ""
boolean NEGeneralOKst = true
String NEGeneralStr = ""
boolean NETuOKst = true
String NETuStr = ""
boolean NiOKst = true
String NiStr = ""
Operation op
long pageTime = 100000
JPanel panel
JPanel panelvac = new JPanel()
JPanel panelweb = new JPanel()
int sleepTime = 1000
boolean TankOKst = true
String TankStr = ""
Thread thread
String title
VentingTableView ventingTableView
boolean WEBaseOKst = true
String WEBaseStr = ""
boolean WECleanOKst = true
String WECleanStr = ""
boolean WECryoOKst = true
String WECryoStr = ""
boolean WEGeneralOKst = true
String WEGeneralStr = ""
boolean WETuOKst = true
String WETuStr = ""
boolean WiOKst = true
String WiStr = ""
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
static final long serialVersionUID = 354054054055L
Detailed Description
Definition at line 48 of file GlgGui.java.
Constructor & Destructor Documentation
GlgGui() [1/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 77 of file GlgGui.java.
References createAndShowGui(), deviceManager, parent, run(), and title.
Referenced by createAndShowGui().
GlgGui() [2/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 77 of file GlgGui.java.
References createAndShowGui(), deviceManager, parent, run(), and title.
GlgGui() [3/22]
GlgGui.GlgGui (Operation _op, String _title)
Definition at line 31 of file GlgGui.java.
References createAndShowGui(), deviceManager, Operation.deviceManager, doStart(), op, parent, and title.
GlgGui() [4/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [5/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [6/22]
GlgGui.GlgGui (Operation _op, String _title)
Definition at line 31 of file GlgGui.java.
References createAndShowGui(), deviceManager, Operation.deviceManager, doStart(), op, parent, and title.
GlgGui() [7/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [8/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [9/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 111 of file GlgGui.java.
References createAndShowGui(), deviceManager, parent, run(), and title.
GlgGui() [10/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [11/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 111 of file GlgGui.java.
References createAndShowGui(), deviceManager, parent, run(), and title.
GlgGui() [12/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 32 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [13/22]
GlgGui.GlgGui (Operation _op, String _title)
Definition at line 31 of file GlgGui.java.
References createAndShowGui(), deviceManager, Operation.deviceManager, doStart(), op, parent, and title.
GlgGui() [14/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [15/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [16/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [17/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [18/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [19/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 30 of file GlgGui.java.
References createAndShowGui(), deviceManager, doStart(), parent, and title.
GlgGui() [20/22]
GlgGui.GlgGui (Operation _op, String _title)
Definition at line 31 of file GlgGui.java.
References createAndShowGui(), deviceManager, Operation.deviceManager, doStart(), op, parent, and title.
GlgGui() [21/22]
GlgGui.GlgGui (DeviceManager _deviceManager, Operation _op2000, Operation _op50000, String _title)
Definition at line 48 of file GlgGui.java.
References createAndShowGui(), dbUrl, deviceManager, doStart(), op2000, parent, resolveDbUrl(), and title.
GlgGui() [22/22]
GlgGui.GlgGui (DeviceManager _deviceManager, String _title)
Definition at line 111 of file GlgGui.java.
References createAndShowGui(), deviceManager, parent, run(), and title.
Member Function Documentation
createAndShowGui() [1/22]
void GlgGui.createAndShowGui () private
Definition at line 101 of file GlgGui.java.
References doStart(), glg_bean1, glg_bean2, initVacComponents(), initWebComponents(), jfxPanel3, logger, ChannelList.mainDrawing1, ChannelList.mainDrawing2, panel, panelvac, panelweb, and title.
Referenced by GlgGui().
createAndShowGui() [2/22]
void GlgGui.createAndShowGui () private
Definition at line 101 of file GlgGui.java.
References doStart(), glg_bean1, glg_bean2, initVacComponents(), initWebComponents(), jfxPanel3, logger, ChannelList.mainDrawing1, ChannelList.mainDrawing2, panel, panelvac, and panelweb.
createAndShowGui() [3/22]
void GlgGui.createAndShowGui () private
Definition at line 54 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, op, Operation.setHumPoint(), Operation.setTempPoint(), subwindows, and title.
createAndShowGui() [4/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [5/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [6/22]
void GlgGui.createAndShowGui () private
Definition at line 54 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [7/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [8/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [9/22]
void GlgGui.createAndShowGui () private
Definition at line 135 of file GlgGui.java.
References doStart(), glg_bean1, glg_bean2, initVacComponents(), initWebComponents(), jfxPanel3, logger, ChannelList.mainDrawing1, ChannelList.mainDrawing2, panel, panelvac, panelweb, and title.
createAndShowGui() [10/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [11/22]
void GlgGui.createAndShowGui () private
Definition at line 135 of file GlgGui.java.
References doStart(), glg_bean1, glg_bean2, initVacComponents(), initWebComponents(), jfxPanel3, logger, ChannelList.mainDrawing1, ChannelList.mainDrawing2, panel, panelvac, panelweb, and title.
createAndShowGui() [12/22]
void GlgGui.createAndShowGui () private
Definition at line 54 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [13/22]
void GlgGui.createAndShowGui () private
Definition at line 54 of file GlgGui.java.
References Device.aliasName, content, deviceManager, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [14/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [15/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [16/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [17/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [18/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [19/22]
void GlgGui.createAndShowGui () private
Definition at line 52 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [20/22]
void GlgGui.createAndShowGui () private
Definition at line 54 of file GlgGui.java.
References content, exitProgram(), glg_bean, GlgGui(), logger, ChannelList.mainDrawing, subwindows, and title.
createAndShowGui() [21/22]
void GlgGui.createAndShowGui () private
Definition at line 75 of file GlgGui.java.
References content, dbUrl, deviceManager, exitProgram(), VentingTableView.getPanel(), glg_bean, logger, ChannelList.mainDrawing, run(), subwindows, ChannelList.VENTINGCMD, ventingTableView, and ChannelList.VENTINGVIEWSTATUS.
createAndShowGui() [22/22]
void GlgGui.createAndShowGui () private
Definition at line 135 of file GlgGui.java.
References doStart(), glg_bean1, glg_bean2, initVacComponents(), initWebComponents(), jfxPanel3, logger, ChannelList.mainDrawing1, ChannelList.mainDrawing2, panel, panelvac, panelweb, and title.
createVacScene() [1/5]
void GlgGui.createVacScene () private
Definition at line 175 of file GlgGui.java.
References jfxPanel3, and run().
Referenced by initVacComponents().
createVacScene() [2/5]
void GlgGui.createVacScene () private
Definition at line 188 of file GlgGui.java.
References jfxPanel3, and run().
createVacScene() [3/5]
void GlgGui.createVacScene () private
Definition at line 209 of file GlgGui.java.
References jfxPanel3, and run().
createVacScene() [4/5]
void GlgGui.createVacScene () private
Definition at line 209 of file GlgGui.java.
References jfxPanel3, and run().
createVacScene() [5/5]
void GlgGui.createVacScene () private
Definition at line 209 of file GlgGui.java.
References jfxPanel3, and run().
createWebScene() [1/5]
void GlgGui.createWebScene () private
Definition at line 186 of file GlgGui.java.
References engine1, engine2, jfxPanel1, jfxPanel2, panel, and run().
Referenced by initWebComponents().
createWebScene() [2/5]
void GlgGui.createWebScene () private
Definition at line 199 of file GlgGui.java.
References engine1, engine2, jfxPanel1, jfxPanel2, panel, and run().
createWebScene() [3/5]
void GlgGui.createWebScene () private
Definition at line 220 of file GlgGui.java.
References engine1, engine2, jfxPanel1, jfxPanel2, panel, and run().
createWebScene() [4/5]
void GlgGui.createWebScene () private
Definition at line 220 of file GlgGui.java.
References engine1, engine2, jfxPanel1, jfxPanel2, panel, and run().
createWebScene() [5/5]
void GlgGui.createWebScene () private
Definition at line 220 of file GlgGui.java.
References engine1, engine2, jfxPanel1, jfxPanel2, panel, and run().
doStart() [1/22]
void GlgGui.doStart ()
Definition at line 90 of file GlgGui.java.
References thread.
Referenced by createAndShowGui(), and GlgGui().
doStart() [2/22]
void GlgGui.doStart ()
Definition at line 90 of file GlgGui.java.
References thread.
doStart() [3/22]
void GlgGui.doStart ()
Definition at line 43 of file GlgGui.java.
References thread.
doStart() [4/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [5/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [6/22]
void GlgGui.doStart ()
Definition at line 43 of file GlgGui.java.
References thread.
doStart() [7/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [8/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [9/22]
void GlgGui.doStart ()
Definition at line 124 of file GlgGui.java.
References thread.
doStart() [10/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [11/22]
void GlgGui.doStart ()
Definition at line 124 of file GlgGui.java.
References thread.
doStart() [12/22]
void GlgGui.doStart ()
Definition at line 43 of file GlgGui.java.
References thread.
doStart() [13/22]
void GlgGui.doStart ()
Definition at line 43 of file GlgGui.java.
References thread.
doStart() [14/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [15/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [16/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [17/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [18/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [19/22]
void GlgGui.doStart ()
Definition at line 41 of file GlgGui.java.
References thread.
doStart() [20/22]
void GlgGui.doStart ()
Definition at line 43 of file GlgGui.java.
References thread.
doStart() [21/22]
void GlgGui.doStart ()
Definition at line 64 of file GlgGui.java.
References thread.
doStart() [22/22]
void GlgGui.doStart ()
Definition at line 124 of file GlgGui.java.
References thread.
doStop() [1/22]
void GlgGui.doStop ()
Definition at line 95 of file GlgGui.java.
References thread.
doStop() [2/22]
void GlgGui.doStop ()
Definition at line 95 of file GlgGui.java.
References thread.
doStop() [3/22]
void GlgGui.doStop ()
Definition at line 48 of file GlgGui.java.
References thread.
doStop() [4/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [5/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [6/22]
void GlgGui.doStop ()
Definition at line 48 of file GlgGui.java.
References thread.
doStop() [7/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [8/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [9/22]
void GlgGui.doStop ()
Definition at line 129 of file GlgGui.java.
References thread.
doStop() [10/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [11/22]
void GlgGui.doStop ()
Definition at line 129 of file GlgGui.java.
References thread.
doStop() [12/22]
void GlgGui.doStop ()
Definition at line 48 of file GlgGui.java.
References thread.
doStop() [13/22]
void GlgGui.doStop ()
Definition at line 48 of file GlgGui.java.
References thread.
doStop() [14/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [15/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [16/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [17/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [18/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [19/22]
void GlgGui.doStop ()
Definition at line 46 of file GlgGui.java.
References thread.
doStop() [20/22]
void GlgGui.doStop ()
Definition at line 48 of file GlgGui.java.
References thread.
doStop() [21/22]
void GlgGui.doStop ()
Definition at line 69 of file GlgGui.java.
References thread.
doStop() [22/22]
void GlgGui.doStop ()
Definition at line 129 of file GlgGui.java.
References thread.
exitProgram() [1/22]
void GlgGui.exitProgram ()
Definition at line 277 of file GlgGui.java.
Referenced by createAndShowGui(), and Main.main().
exitProgram() [2/22]
void GlgGui.exitProgram ()
Definition at line 290 of file GlgGui.java.
exitProgram() [3/22]
void GlgGui.exitProgram ()
Definition at line 91 of file GlgGui.java.
exitProgram() [4/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [5/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [6/22]
void GlgGui.exitProgram ()
Definition at line 85 of file GlgGui.java.
exitProgram() [7/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [8/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [9/22]
void GlgGui.exitProgram ()
Definition at line 311 of file GlgGui.java.
exitProgram() [10/22]
void GlgGui.exitProgram ()
Definition at line 85 of file GlgGui.java.
exitProgram() [11/22]
void GlgGui.exitProgram ()
Definition at line 311 of file GlgGui.java.
exitProgram() [12/22]
void GlgGui.exitProgram ()
Definition at line 86 of file GlgGui.java.
exitProgram() [13/22]
void GlgGui.exitProgram ()
Definition at line 90 of file GlgGui.java.
exitProgram() [14/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [15/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [16/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [17/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [18/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [19/22]
void GlgGui.exitProgram ()
Definition at line 83 of file GlgGui.java.
exitProgram() [20/22]
void GlgGui.exitProgram ()
Definition at line 85 of file GlgGui.java.
exitProgram() [21/22]
void GlgGui.exitProgram ()
Definition at line 156 of file GlgGui.java.
exitProgram() [22/22]
void GlgGui.exitProgram ()
Definition at line 311 of file GlgGui.java.
initVacComponents() [1/5]
void GlgGui.initVacComponents () private
Definition at line 170 of file GlgGui.java.
References createVacScene(), and jfxPanel3.
Referenced by createAndShowGui().
initVacComponents() [2/5]
void GlgGui.initVacComponents () private
Definition at line 183 of file GlgGui.java.
References createVacScene(), and jfxPanel3.
initVacComponents() [3/5]
void GlgGui.initVacComponents () private
Definition at line 204 of file GlgGui.java.
References createVacScene(), and jfxPanel3.
initVacComponents() [4/5]
void GlgGui.initVacComponents () private
Definition at line 204 of file GlgGui.java.
References createVacScene(), and jfxPanel3.
initVacComponents() [5/5]
void GlgGui.initVacComponents () private
Definition at line 204 of file GlgGui.java.
References createVacScene(), and jfxPanel3.
initWebComponents() [1/5]
void GlgGui.initWebComponents () private
Definition at line 158 of file GlgGui.java.
References createWebScene(), jfxPanel1, jfxPanel2, and panelweb.
Referenced by createAndShowGui().
initWebComponents() [2/5]
void GlgGui.initWebComponents () private
Definition at line 171 of file GlgGui.java.
References createWebScene(), jfxPanel1, jfxPanel2, and panelweb.
initWebComponents() [3/5]
void GlgGui.initWebComponents () private
Definition at line 192 of file GlgGui.java.
References createWebScene(), jfxPanel1, jfxPanel2, and panelweb.
initWebComponents() [4/5]
void GlgGui.initWebComponents () private
Definition at line 192 of file GlgGui.java.
References createWebScene(), jfxPanel1, jfxPanel2, and panelweb.
initWebComponents() [5/5]
void GlgGui.initWebComponents () private
Definition at line 192 of file GlgGui.java.
References createWebScene(), jfxPanel1, jfxPanel2, and panelweb.
loadURL1() [1/5]
void GlgGui.loadURL1 ()
Definition at line 261 of file GlgGui.java.
References engine1, and run().
Referenced by run().
loadURL1() [2/5]
void GlgGui.loadURL1 ()
Definition at line 274 of file GlgGui.java.
References engine1, and run().
loadURL1() [3/5]
void GlgGui.loadURL1 ()
Definition at line 295 of file GlgGui.java.
References engine1, and run().
loadURL1() [4/5]
void GlgGui.loadURL1 ()
Definition at line 295 of file GlgGui.java.
References engine1, and run().
loadURL1() [5/5]
void GlgGui.loadURL1 ()
Definition at line 295 of file GlgGui.java.
References engine1, and run().
loadURL2() [1/5]
void GlgGui.loadURL2 ()
Definition at line 269 of file GlgGui.java.
References engine2, and run().
Referenced by run().
loadURL2() [2/5]
void GlgGui.loadURL2 ()
Definition at line 282 of file GlgGui.java.
References engine2, and run().
loadURL2() [3/5]
void GlgGui.loadURL2 ()
Definition at line 303 of file GlgGui.java.
References engine2, and run().
loadURL2() [4/5]
void GlgGui.loadURL2 ()
Definition at line 303 of file GlgGui.java.
References engine2, and run().
loadURL2() [5/5]
void GlgGui.loadURL2 ()
Definition at line 303 of file GlgGui.java.
References engine2, and run().
resolveDbUrl()
String GlgGui.resolveDbUrl () private
Definition at line 39 of file GlgGui.java.
Referenced by GlgGui().
run() [1/22]
void GlgGui.run ()
Definition at line 392 of file GlgGui.java.
References glg_bean1, glg_bean2, isSuspended, lastTime, loadURL1(), loadURL2(), logger, pageTime, sleepTime, and updateGui().
Referenced by createAndShowGui(), createVacScene(), createWebScene(), GlgGui(), loadURL1(), loadURL2(), and run().
run() [2/22]
void GlgGui.run ()
Definition at line 423 of file GlgGui.java.
References glg_bean1, glg_bean2, isSuspended, lastTime, loadURL1(), loadURL2(), logger, pageTime, run(), sleepTime, and updateGui().
run() [3/22]
void GlgGui.run ()
Definition at line 182 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [4/22]
void GlgGui.run ()
Definition at line 162 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [5/22]
void GlgGui.run ()
Definition at line 165 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [6/22]
void GlgGui.run ()
Definition at line 186 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [7/22]
void GlgGui.run ()
Definition at line 166 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [8/22]
void GlgGui.run ()
Definition at line 166 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [9/22]
void GlgGui.run ()
Definition at line 990 of file GlgGui.java.
References glg_bean1, glg_bean2, isSuspended, loadURL1(), loadURL2(), logger, run(), sleepTime, and updateGui().
run() [10/22]
void GlgGui.run ()
Definition at line 141 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [11/22]
void GlgGui.run ()
Definition at line 995 of file GlgGui.java.
References glg_bean1, glg_bean2, isSuspended, loadURL1(), loadURL2(), logger, run(), sleepTime, and updateGui().
run() [12/22]
void GlgGui.run ()
Definition at line 143 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [13/22]
void GlgGui.run ()
Definition at line 175 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [14/22]
void GlgGui.run ()
Definition at line 155 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [15/22]
void GlgGui.run ()
Definition at line 163 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [16/22]
void GlgGui.run ()
Definition at line 163 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [17/22]
void GlgGui.run ()
Definition at line 163 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [18/22]
void GlgGui.run ()
Definition at line 163 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [19/22]
void GlgGui.run ()
Definition at line 163 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [20/22]
void GlgGui.run ()
Definition at line 167 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [21/22]
void GlgGui.run ()
Definition at line 232 of file GlgGui.java.
References glg_bean, isSuspended, logger, run(), and updateGui().
run() [22/22]
void GlgGui.run ()
Definition at line 995 of file GlgGui.java.
References glg_bean1, glg_bean2, isSuspended, loadURL1(), loadURL2(), logger, run(), sleepTime, and updateGui().
updateGui() [1/22]
void GlgGui.updateGui ()
Definition at line 280 of file GlgGui.java.
References deviceManager, formatter, DataManager.getDataElement(), glg_bean1, glg_bean2, logger, DataElement.name, ChannelList.PANEL1STATUS, ChannelList.PANEL2STATUS, ChannelList.PCounterColorCOMSTATUS, ChannelList.PCounterColorFLAGSTATUS, ChannelList.PCounterColorINSTRSTATUS, ChannelList.PCounterMobileColorSTATUS, DataElement.type, and DataElement.value.
Referenced by run().
updateGui() [2/22]
void GlgGui.updateGui ()
Definition at line 293 of file GlgGui.java.
References deviceManager, formatter, DataManager.getDataElement(), glg_bean1, glg_bean2, logger, DataElement.name, ChannelList.PCounterColorINSTRSTATUS, ChannelList.PCounterColorSTATUS, ChannelList.PCounterINSTRSTATUS, ChannelList.PCOUNTERMOBSTATUS, ChannelList.PCounterSTATUS, ChannelList.PCOUNTERSTATUS, DataElement.type, and DataElement.value.
updateGui() [3/22]
void GlgGui.updateGui ()
Definition at line 103 of file GlgGui.java.
References deviceManager, DataManager.getDataElement(), Operation.getMode(), glg_bean, logger, op, ChannelList.STATIONSTATUS, and DataElement.value.
updateGui() [4/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References ChannelList.CRYOIBDETSTATUS, deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [5/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References ChannelList.BypassColorSTATUS, ChannelList.CRYO1500WSTATUS, deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [6/22]
void GlgGui.updateGui ()
Definition at line 97 of file GlgGui.java.
References deviceManager, ChannelList.FLOWMETERSTATUS, ChannelList.GaugeColorSTATUS, ChannelList.GaugePressureColorSTATUS, ChannelList.GaugePressureSTATUS, ChannelList.GaugeSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [7/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, ChannelList.LINKSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [8/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, ChannelList.LINKSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [9/22]
void GlgGui.updateGui ()
Definition at line 323 of file GlgGui.java.
References CleanOKst, CleanStr, DetOKst, DetStr, deviceManager, formatter, GeneralOKst, GeneralStr, DataManager.getDataElement(), glg_bean1, glg_bean2, InjOKst, InjStr, logger, DataElement.name, NiOKst, NiStr, ChannelList.PANEL1STATUS, ChannelList.PANEL2STATUS, ChannelList.PCounterColorCOMSTATUS, ChannelList.PCounterColorFLAGSTATUS, ChannelList.PCounterColorINSTRSTATUS, ChannelList.PCounterColorSTATUS, ChannelList.PushO2ColorSTATUS, ChannelList.RelayO2ColorSTATUS, ChannelList.SensorO2ColorSTATUS, TankOKst, TankStr, DataElement.type, updateStrings(), DataElement.value, WiOKst, and WiStr.
updateGui() [10/22]
void GlgGui.updateGui ()
Definition at line 97 of file GlgGui.java.
References deviceManager, DataManager.getDataElement(), glg_bean, logger, ChannelList.STATIONSTATUS, and DataElement.value.
updateGui() [11/22]
void GlgGui.updateGui ()
Definition at line 323 of file GlgGui.java.
References deviceManager, formatter, DataManager.getDataElement(), glg_bean1, glg_bean2, logger, DataElement.name, NEBaseOKst, NEBaseStr, NECleanOKst, NECleanStr, NECryoOKst, NECryoStr, NEGeneralOKst, NEGeneralStr, NETuOKst, NETuStr, ChannelList.PANEL1STATUS, ChannelList.PANEL2STATUS, ChannelList.PCounterColorCOMSTATUS, ChannelList.PCounterColorFLAGSTATUS, ChannelList.PCounterColorINSTRSTATUS, ChannelList.PCounterColorSTATUS, ChannelList.PushO2ColorSTATUS, ChannelList.RelayO2ColorSTATUS, ChannelList.SensorO2ColorSTATUS, DataElement.type, updateStrings(), and DataElement.value.
updateGui() [12/22]
void GlgGui.updateGui ()
Definition at line 98 of file GlgGui.java.
References deviceManager, DataManager.getDataElement(), glg_bean, logger, DataElement.name, ChannelList.PANELSTATUS, ChannelList.PCounterColorCOMSTATUS, ChannelList.PCounterColorFLAGSTATUS, ChannelList.PCounterColorINSTRSTATUS, ChannelList.PCounterColorSTATUS, DataElement.type, and DataElement.value.
updateGui() [13/22]
void GlgGui.updateGui ()
Definition at line 102 of file GlgGui.java.
References deviceManager, DataManager.getDataElement(), glg_bean, logger, DataElement.name, op, ChannelList.PCounterColorINSTRSTATUS, ChannelList.PCounterColorSTATUS, ChannelList.PCounterINSTRSTATUS, ChannelList.PCounterSTATUS, ChannelList.PCOUNTERSTATUS, DataElement.type, and DataElement.value.
updateGui() [14/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.TUBESTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [15/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.RGASTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [16/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.SQZSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [17/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.SQZSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [18/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.SQZSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [19/22]
void GlgGui.updateGui ()
Definition at line 95 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.SQZSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [20/22]
void GlgGui.updateGui ()
Definition at line 97 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, ChannelList.ROTGaugeEmissionColorSTATUS, ChannelList.TUBE1500WSTATUS, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [21/22]
void GlgGui.updateGui ()
Definition at line 159 of file GlgGui.java.
References deviceManager, ChannelList.GaugeColorSTATUS, DataManager.getDataElement(), glg_bean, ChannelList.IonicONOFFColorSTATUS, logger, ChannelList.MksComColorSTATUS, DataElement.name, ChannelList.RelayGeneralColorSTATUS, ChannelList.RGAONOFFColorSTATUS, title, ChannelList.TurboONOFFColorSTATUS, DataElement.type, DataElement.value, ChannelList.ValveColorSTATUS, ChannelList.VENTINGSTATUS, and ChannelList.XGSGaugeEmissionColorSTATUS.
updateGui() [22/22]
void GlgGui.updateGui ()
Definition at line 323 of file GlgGui.java.
References deviceManager, formatter, DataManager.getDataElement(), glg_bean1, glg_bean2, logger, DataElement.name, ChannelList.PANEL1STATUS, ChannelList.PANEL2STATUS, ChannelList.PCounterColorCOMSTATUS, ChannelList.PCounterColorFLAGSTATUS, ChannelList.PCounterColorINSTRSTATUS, ChannelList.PCounterColorSTATUS, ChannelList.PushO2ColorSTATUS, ChannelList.RelayO2ColorSTATUS, ChannelList.SensorO2ColorSTATUS, DataElement.type, updateStrings(), DataElement.value, WEBaseOKst, WEBaseStr, WECleanOKst, WECleanStr, WECryoOKst, WECryoStr, WEGeneralOKst, WEGeneralStr, WETuOKst, and WETuStr.
updateStrings() [1/3]
void GlgGui.updateStrings ()
Definition at line 806 of file GlgGui.java.
References CleanOKst, CleanStr, DetOKst, DetStr, GeneralOKst, GeneralStr, glg_bean2, InjOKst, InjStr, NiOKst, NiStr, TankOKst, TankStr, WiOKst, and WiStr.
Referenced by updateGui().
updateStrings() [2/3]
void GlgGui.updateStrings ()
Definition at line 807 of file GlgGui.java.
References glg_bean2, NEBaseOKst, NEBaseStr, NECleanOKst, NECleanStr, NECryoOKst, NECryoStr, NEGeneralOKst, NEGeneralStr, NETuOKst, and NETuStr.
updateStrings() [3/3]
void GlgGui.updateStrings ()
Definition at line 807 of file GlgGui.java.
References glg_bean2, WEBaseOKst, WEBaseStr, WECleanOKst, WECleanStr, WECryoOKst, WECryoStr, WEGeneralOKst, WEGeneralStr, WETuOKst, and WETuStr.
Member Data Documentation
CleanOKst
boolean GlgGui.CleanOKst = true private
Definition at line 80 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
CleanStr
String GlgGui.CleanStr = "" private
Definition at line 96 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
content
Container GlgGui.content private
Definition at line 56 of file GlgGui.java.
Referenced by createAndShowGui().
dbUrl
String GlgGui.dbUrl private
Definition at line 37 of file GlgGui.java.
Referenced by createAndShowGui(), and GlgGui().
DetOKst
boolean GlgGui.DetOKst = true private
Definition at line 78 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
DetStr
String GlgGui.DetStr = "" private
Definition at line 95 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
deviceManager
DeviceManager GlgGui.deviceManager private
Definition at line 51 of file GlgGui.java.
Referenced by createAndShowGui(), GlgGui(), and updateGui().
engine1
WebEngine GlgGui.engine1 private
Definition at line 61 of file GlgGui.java.
Referenced by createWebScene(), and loadURL1().
engine2
WebEngine GlgGui.engine2 private
Definition at line 62 of file GlgGui.java.
Referenced by createWebScene(), and loadURL2().
formatter
SimpleDateFormat GlgGui.formatter = new SimpleDateFormat("EEE, dd-MMM-yyyy HH:mm:ss") private
Definition at line 73 of file GlgGui.java.
Referenced by updateGui().
GeneralOKst
boolean GlgGui.GeneralOKst = true private
Definition at line 74 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
GeneralStr
String GlgGui.GeneralStr = "" private
Definition at line 91 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
glg_bean
GlgJLWBean GlgGui.glg_bean private
Definition at line 27 of file GlgGui.java.
Referenced by createAndShowGui(), run(), and updateGui().
glg_bean1
GlgJLWBean GlgGui.glg_bean1 private
Definition at line 65 of file GlgGui.java.
Referenced by createAndShowGui(), run(), and updateGui().
glg_bean2
GlgJLWBean GlgGui.glg_bean2 private
Definition at line 66 of file GlgGui.java.
Referenced by createAndShowGui(), run(), updateGui(), and updateStrings().
InjOKst
boolean GlgGui.InjOKst = true private
Definition at line 77 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
InjStr
String GlgGui.InjStr = "" private
Definition at line 94 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
isSuspended
boolean GlgGui.isSuspended = false
Definition at line 68 of file GlgGui.java.
Referenced by GlgPropsGui.InputListener.InputCallback(), GlgCryoIbDetStatusDetailsGui.InputListener.InputCallback(), GlgDryGui.InputListener.InputCallback(), GlgGaugeGui.InputListener.InputCallback(), GlgIonicGui.InputListener.InputCallback(), GlgRGAGui.InputListener.InputCallback(), GlgTitane_22Gui.InputListener.InputCallback(), GlgTitane_32Gui.InputListener.InputCallback(), GlgTurboGui.InputListener.InputCallback(), GlgValveGui.InputListener.InputCallback(), GlgXGSGaugeGui.InputListener.InputCallback(), GlgCryo1500wIntGui.InputListener.InputCallback(), GlgCryo1500wStatusDetailsGui.InputListener.InputCallback(), GlgCryo1500wTempGui.InputListener.InputCallback(), GlgLinkStatusDetailsGui.InputListener.InputCallback(), GlgLinkTempGui.InputListener.InputCallback(), GlgRGA3Gui.InputListener.InputCallback(), Glg2Gui.InputListener.InputCallback(), GlgPCounter2Gui.InputListener.InputCallback(), GlgPCounterStatusDetailsGui.InputListener.InputCallback(), GlgPCounterTempGui.InputListener.InputCallback(), GlgTubeStatusDetailsGui.InputListener.InputCallback(), GlgRgaStatusDetailsGui.InputListener.InputCallback(), GlgRgaTempGui.InputListener.InputCallback(), GlgSqzStatusDetailsGui.InputListener.InputCallback(), GlgSqzTempGui.InputListener.InputCallback(), GlgSqzVacuumGui.InputListener.InputCallback(), GlgTitaneGui.InputListener.InputCallback(), GlgTurboPfeifferDCUGui.InputListener.InputCallback(), GlgTCMuxTempGui.InputListener.InputCallback(), GlgTube1500wStatusDetailsGui.InputListener.InputCallback(), GlgFlowMeterGui.InputListener.InputCallback(), GlgChildGui.run(), and run().
isVimLoaded
boolean GlgGui.isVimLoaded = true private
Definition at line 71 of file GlgGui.java.
jfxPanel1
JFXPanel GlgGui.jfxPanel1 private
Definition at line 58 of file GlgGui.java.
Referenced by createWebScene(), and initWebComponents().
jfxPanel2
JFXPanel GlgGui.jfxPanel2 private
Definition at line 59 of file GlgGui.java.
Referenced by createWebScene(), and initWebComponents().
jfxPanel3
JFXPanel GlgGui.jfxPanel3 private
Definition at line 60 of file GlgGui.java.
Referenced by createAndShowGui(), createVacScene(), and initVacComponents().
lastTime
long GlgGui.lastTime = 0 private
Definition at line 70 of file GlgGui.java.
Referenced by run().
logger
static final Logger GlgGui.logger = Logger.getLogger("Main") static private
Definition at line 55 of file GlgGui.java.
Referenced by createAndShowGui(), run(), and updateGui().
NEBaseOKst
boolean GlgGui.NEBaseOKst = true private
Definition at line 84 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NEBaseStr
String GlgGui.NEBaseStr = "" private
Definition at line 101 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NECleanOKst
boolean GlgGui.NECleanOKst = true private
Definition at line 85 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NECleanStr
String GlgGui.NECleanStr = "" private
Definition at line 102 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NECryoOKst
boolean GlgGui.NECryoOKst = true private
Definition at line 83 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NECryoStr
String GlgGui.NECryoStr = "" private
Definition at line 100 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NEGeneralOKst
boolean GlgGui.NEGeneralOKst = true private
Definition at line 81 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NEGeneralStr
String GlgGui.NEGeneralStr = "" private
Definition at line 98 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NETuOKst
boolean GlgGui.NETuOKst = true private
Definition at line 82 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NETuStr
String GlgGui.NETuStr = "" private
Definition at line 99 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NiOKst
boolean GlgGui.NiOKst = true private
Definition at line 75 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
NiStr
String GlgGui.NiStr = "" private
Definition at line 92 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
op
Operation GlgGui.op private
Definition at line 21 of file GlgGui.java.
Referenced by createAndShowGui(), GlgGui(), and updateGui().
op2000
Operation GlgGui.op2000
Definition at line 26 of file GlgGui.java.
Referenced by GlgChildGui.GlgChildGui(), and GlgGui().
pageTime
long GlgGui.pageTime = 100000 private
Definition at line 69 of file GlgGui.java.
Referenced by run().
panel
JPanel GlgGui.panel private
Definition at line 57 of file GlgGui.java.
Referenced by createAndShowGui(), and createWebScene().
panelvac
JPanel GlgGui.panelvac = new JPanel() private
Definition at line 64 of file GlgGui.java.
Referenced by createAndShowGui().
panelweb
JPanel GlgGui.panelweb = new JPanel() private
Definition at line 63 of file GlgGui.java.
Referenced by createAndShowGui(), and initWebComponents().
parent
GlgGui GlgGui.parent
Definition at line 52 of file GlgGui.java.
Referenced by GlgGui().
serialVersionUID
static final long GlgGui.serialVersionUID = 354054054055L static private
Definition at line 50 of file GlgGui.java.
sleepTime
int GlgGui.sleepTime = 1000 private
Definition at line 75 of file GlgGui.java.
Referenced by run().
subwindows
Hashtable< String, GlgChildGui > GlgGui.subwindows
Definition at line 67 of file GlgGui.java.
Referenced by GlgChildGui.addWindowsListener(), createAndShowGui(), and GlgChildGui.GlgChildGui().
TankOKst
boolean GlgGui.TankOKst = true private
Definition at line 79 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
TankStr
String GlgGui.TankStr = "" private
Definition at line 97 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
thread
Thread GlgGui.thread private
Definition at line 54 of file GlgGui.java.
Referenced by doStart(), and doStop().
title
String GlgGui.title private
Definition at line 53 of file GlgGui.java.
Referenced by createAndShowGui(), GlgGui(), and updateGui().
ventingTableView
VentingTableView GlgGui.ventingTableView private
Definition at line 36 of file GlgGui.java.
Referenced by createAndShowGui().
WEBaseOKst
boolean GlgGui.WEBaseOKst = true private
Definition at line 89 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WEBaseStr
String GlgGui.WEBaseStr = "" private
Definition at line 106 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WECleanOKst
boolean GlgGui.WECleanOKst = true private
Definition at line 90 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WECleanStr
String GlgGui.WECleanStr = "" private
Definition at line 107 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WECryoOKst
boolean GlgGui.WECryoOKst = true private
Definition at line 88 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WECryoStr
String GlgGui.WECryoStr = "" private
Definition at line 105 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WEGeneralOKst
boolean GlgGui.WEGeneralOKst = true private
Definition at line 86 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WEGeneralStr
String GlgGui.WEGeneralStr = "" private
Definition at line 103 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WETuOKst
boolean GlgGui.WETuOKst = true private
Definition at line 87 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WETuStr
String GlgGui.WETuStr = "" private
Definition at line 104 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WiOKst
boolean GlgGui.WiOKst = true private
Definition at line 76 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
WiStr
String GlgGui.WiStr = "" private
Definition at line 93 of file GlgGui.java.
Referenced by updateGui(), and updateStrings().
The documentation for this class was generated from the following file:
work_1500npanel/GlgGui.java