SCADARPI API: TCMuxShield Class Reference
TCMuxShield Class Reference
Public Member Functions
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
TCMuxShield (String _name, int _mbRegisterStart)
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Static Private Member Functions
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
static GpioController initGpioController ()
Private Attributes
final GpioController gpio = initGpioController()
I2C_Comm i2c
int OPEN = -1000
GpioPinDigitalOutput pina0 = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_05)
GpioPinDigitalOutput pina1 = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_06)
GpioPinDigitalOutput pina2 = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_21)
GpioPinDigitalOutput pincs = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_22)
GpioPinDigitalOutput pinen = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_02)
GpioPinDigitalOutput pinsc = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_23)
GpioPinDigitalInput pinso = gpio.provisionDigitalInputPin(RaspiPin.GPIO_00)
int SHORT = -1001
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 15 of file TCMuxShield.java.
Constructor & Destructor Documentation
TCMuxShield() [1/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 50 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [2/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 50 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [3/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 50 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [4/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 50 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [5/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 50 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [6/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 51 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [7/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 32 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pincs, pinen, pinsc, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [8/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 50 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [9/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 50 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
TCMuxShield() [10/10]
TCMuxShield.TCMuxShield (String _name, int _mbRegisterStart)
Definition at line 50 of file TCMuxShield.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, DataTypes.RegisterType.FLOAT32, gpio, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, pina0, pina1, pina2, pincs, pinen, pinsc, pinso, and DataTypes.DataType.READ_ONLY_VALUE.
Member Function Documentation
executeCommand() [1/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 167 of file TCMuxShield.java.
executeCommand() [2/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 167 of file TCMuxShield.java.
executeCommand() [3/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 167 of file TCMuxShield.java.
executeCommand() [4/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 174 of file TCMuxShield.java.
executeCommand() [5/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 167 of file TCMuxShield.java.
executeCommand() [6/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 168 of file TCMuxShield.java.
executeCommand() [7/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 131 of file TCMuxShield.java.
executeCommand() [8/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 167 of file TCMuxShield.java.
executeCommand() [9/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 167 of file TCMuxShield.java.
executeCommand() [10/10]
void TCMuxShield.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 167 of file TCMuxShield.java.
initGpioController() [1/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 32 of file TCMuxShield.java.
References logger.
initGpioController() [2/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 32 of file TCMuxShield.java.
References logger.
initGpioController() [3/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 32 of file TCMuxShield.java.
References logger.
initGpioController() [4/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 32 of file TCMuxShield.java.
References logger.
initGpioController() [5/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 32 of file TCMuxShield.java.
References logger.
initGpioController() [6/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 33 of file TCMuxShield.java.
References logger.
initGpioController() [7/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 32 of file TCMuxShield.java.
References logger.
initGpioController() [8/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 32 of file TCMuxShield.java.
References logger.
initGpioController() [9/9]
static GpioController TCMuxShield.initGpioController () static private
Reimplemented from Device.
Definition at line 32 of file TCMuxShield.java.
References logger.
updateDeviceData() [1/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 96 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [2/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 96 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [3/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 96 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [4/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 96 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [5/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 96 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [6/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 97 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [7/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 66 of file TCMuxShield.java.
References DataManager.getDataElement(), Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [8/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 96 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [9/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 96 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
updateDeviceData() [10/10]
void TCMuxShield.updateDeviceData ()
Reimplemented from Device.
Definition at line 96 of file TCMuxShield.java.
References DataManager.getDataElement(), gpio, Device.hasWarned, logger, Device.name, OPEN, pina0, pina1, pina2, pincs, Device.setErrorComStatus(), SHORT, and DataElement.value.
Member Data Documentation
gpio
final GpioController TCMuxShield.gpio = initGpioController() private
Definition at line 20 of file TCMuxShield.java.
Referenced by TCMuxShield(), and updateDeviceData().
i2c
I2C_Comm TCMuxShield.i2c private
Definition at line 17 of file TCMuxShield.java.
logger
static final Logger TCMuxShield.logger = Logger.getLogger("Main") static private
Definition at line 18 of file TCMuxShield.java.
Referenced by initGpioController(), TCMuxShield(), and updateDeviceData().
OPEN
int TCMuxShield.OPEN = -1000 private
Definition at line 29 of file TCMuxShield.java.
Referenced by updateDeviceData().
pina0
GpioPinDigitalOutput TCMuxShield.pina0 = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_05) private
Definition at line 23 of file TCMuxShield.java.
Referenced by TCMuxShield(), and updateDeviceData().
pina1
GpioPinDigitalOutput TCMuxShield.pina1 = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_06) private
Definition at line 24 of file TCMuxShield.java.
Referenced by TCMuxShield(), and updateDeviceData().
pina2
GpioPinDigitalOutput TCMuxShield.pina2 = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_21) private
Definition at line 25 of file TCMuxShield.java.
Referenced by TCMuxShield(), and updateDeviceData().
pincs
GpioPinDigitalOutput TCMuxShield.pincs = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_22) private
Definition at line 26 of file TCMuxShield.java.
Referenced by TCMuxShield(), and updateDeviceData().
pinen
GpioPinDigitalOutput TCMuxShield.pinen = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_02) private
Definition at line 22 of file TCMuxShield.java.
Referenced by TCMuxShield().
pinsc
GpioPinDigitalOutput TCMuxShield.pinsc = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_23) private
Definition at line 27 of file TCMuxShield.java.
Referenced by TCMuxShield().
pinso
GpioPinDigitalInput TCMuxShield.pinso = gpio.provisionDigitalInputPin(RaspiPin.GPIO_00) private
Definition at line 21 of file TCMuxShield.java.
Referenced by TCMuxShield().
SHORT
int TCMuxShield.SHORT = -1001 private
Definition at line 30 of file TCMuxShield.java.
Referenced by updateDeviceData().
The documentation for this class was generated from the following file:
work_cryo1500w/TCMuxShield.java