SCADARPI API: I2C_Comm Class Reference
I2C_Comm Class Reference
Public Member Functions
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Method.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
byte[] Read28bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
byte[] ReadbytesPlusCRC32 (int length) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
void WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Private Attributes
I2CDevice device = null
int device_addr
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 19 of file I2C_Comm.java.
Constructor & Destructor Documentation
I2C_Comm() [1/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [2/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [3/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [4/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [5/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [6/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [7/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 36 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [8/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [9/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [10/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 36 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [11/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [12/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [13/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
I2C_Comm() [14/14]
I2C_Comm.I2C_Comm (int _device_addr) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Constructor.
Parameters
args
Exceptions
InterruptedException
PlatformAlreadyAssignedException
IOException
UnsupportedBusNumberException
Definition at line 37 of file I2C_Comm.java.
References device, device_addr, and logger.
Member Function Documentation
Read() [1/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Referenced by Controllino.executeCommand(), Controllino_1.executeCommand(), Controllino_2.executeCommand(), Controllino.updateDeviceData(), Controllino_1.updateDeviceData(), and Controllino_2.updateDeviceData().
Read() [2/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [3/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [4/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [5/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [6/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [7/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Method.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [8/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [9/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [10/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 86 of file I2C_Comm.java.
References device, and logger.
Read() [11/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [12/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [13/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read() [14/14]
byte [] I2C_Comm.Read () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Read Methods.
Definition at line 87 of file I2C_Comm.java.
References device, and logger.
Read28bytesPlusCRC32()
byte [] I2C_Comm.Read28bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 186 of file I2C_Comm.java.
References device, and logger.
Referenced by Controllino.executeCommand(), and Controllino.updateDeviceData().
Read4bytesPlusCRC32() [1/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Referenced by Controllino_1.executeCommand(), Controllino_2.executeCommand(), Controllino_1.updateDeviceData(), and Controllino_2.updateDeviceData().
Read4bytesPlusCRC32() [2/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [3/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [4/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [5/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [6/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [7/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [8/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [9/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [10/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [11/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read4bytesPlusCRC32() [12/12]
byte [] I2C_Comm.Read4bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 120 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [1/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Referenced by Controllino_3.executeCommand(), and Controllino_3.updateDeviceData().
Read8bytes() [2/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [3/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [4/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [5/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [6/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [7/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [8/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [9/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 101 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [10/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [11/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [12/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytes() [13/13]
byte [] I2C_Comm.Read8bytes () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 104 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [1/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Referenced by Controllino_1.executeCommand(), Controllino_3.executeCommand(), Controllino_1.updateDeviceData(), and Controllino_3.updateDeviceData().
Read8bytesPlusCRC32() [2/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [3/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 154 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [4/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [5/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [6/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [7/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [8/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [9/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [10/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [11/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
Read8bytesPlusCRC32() [12/12]
byte [] I2C_Comm.Read8bytesPlusCRC32 () throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 153 of file I2C_Comm.java.
References device, and logger.
ReadbytesPlusCRC32()
byte [] I2C_Comm.ReadbytesPlusCRC32 (int length) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Definition at line 185 of file I2C_Comm.java.
References device, and logger.
Referenced by Controllino_2.executeCommand(), and Controllino_2.updateDeviceData().
Write() [1/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
Referenced by Controllino.executeCommand(), Controllino_1.executeCommand(), Controllino_2.executeCommand(), and Controllino_3.executeCommand().
Write() [2/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
Write() [3/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 190 of file I2C_Comm.java.
References device, and logger.
Write() [4/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
Write() [5/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 222 of file I2C_Comm.java.
References device, and logger.
Write() [6/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
Write() [7/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 106 of file I2C_Comm.java.
References device.
Write() [8/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
Write() [9/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
Write() [10/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 120 of file I2C_Comm.java.
References device.
Write() [11/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
Write() [12/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
Write() [13/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 225 of file I2C_Comm.java.
References device, and logger.
Write() [14/14]
void I2C_Comm.Write (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 189 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [1/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
Referenced by Controllino_1.executeCommand(), Controllino_2.executeCommand(), Controllino_3.executeCommand(), and Controllino.executeCommand().
WritePlusCRC32() [2/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [3/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 202 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [4/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [5/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 234 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [6/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [7/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [8/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [9/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [10/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [11/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 237 of file I2C_Comm.java.
References device, and logger.
WritePlusCRC32() [12/12]
void I2C_Comm.WritePlusCRC32 (byte[] mesg) throws InterruptedException, PlatformAlreadyAssignedException, IOException, UnsupportedBusNumberException
Write Method.
Definition at line 201 of file I2C_Comm.java.
References device, and logger.
Member Data Documentation
device
I2CDevice I2C_Comm.device = null private
Definition at line 26 of file I2C_Comm.java.
Referenced by I2C_Comm(), Read(), Read28bytesPlusCRC32(), Read4bytesPlusCRC32(), Read8bytes(), Read8bytesPlusCRC32(), ReadbytesPlusCRC32(), Write(), and WritePlusCRC32().
device_addr
int I2C_Comm.device_addr private
Definition at line 22 of file I2C_Comm.java.
Referenced by I2C_Comm().
logger
static final Logger I2C_Comm.logger = Logger.getLogger("Main") static private
Definition at line 23 of file I2C_Comm.java.
Referenced by I2C_Comm(), Read(), Read28bytesPlusCRC32(), Read4bytesPlusCRC32(), Read8bytes(), Read8bytesPlusCRC32(), ReadbytesPlusCRC32(), Write(), and WritePlusCRC32().
The documentation for this class was generated from the following file:
work_cryo/I2C_Comm.java