SCADARPI API: Operation Class Reference
Operation Class Reference
Public Member Functions
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
String getDeviceName ()
String getFlowMeter ()
OpMode getMode ()
OpMode getMode ()
Operation (Device _device, int _cycleFreq)
Operation (DeviceManager _deviceManager, int _cycleFreq)
Operation (DeviceManager _deviceManager, int _cycleFreq)
Operation (DeviceManager _deviceManager, int _cycleFreq)
Operation (DeviceManager _deviceManager, int _cycleFreq)
void run ()
void run ()
void run ()
void run ()
void run ()
void setACOFF ()
void setAcqTime (int _acqTime)
void setDevice (String devicename)
void setFlowMax (int _flowMax)
void setFlowMax (int _flowMax)
void setFlowMeter (String devicename)
void setFlowStep (int _flowStep)
void setFlowStep (int _flowStep)
void setHumPoint (int _humPoint)
void setMode (OpMode _mode)
void setMode (OpMode _mode)
void setMode (OpMode _mode)
void setMode (OpMode _mode)
void setMode (OpMode _mode)
void setTempMax (int _tempMax)
void setTempPoint (int _tempPoint)
void setTempStep (int _tempStep)
void setTime (double _time)
void setTime (double _time)
void setTime (double _time)
void setTime (double _time)
void setTimeInter (int _timeInter)
void setTimeInter (int _timeInter)
void setTimeInter (int _timeInter)
void setTimeInter (int _timeInter)
Public Attributes
DeviceManager deviceManager
int humPoint
int tempPoint
Private Member Functions
boolean operationAlone ()
boolean operationAuto ()
boolean operationManual ()
boolean operationStartRamp ()
boolean operationStartRamp ()
boolean operationStartRamp ()
boolean operationStartRamp ()
boolean operationStopRamp ()
boolean operationStopRamp ()
boolean operationStopRamp ()
boolean operationStopRamp ()
void saveLog ()
void setValue (Device d, DataElement e, int type, double value)
void setValue (Device d, DataElement e, int type, double value)
void setValue (Device d, DataElement e, int type, double value)
void setValue (Device d, DataElement e, int type, double value)
void setValue (Device d, DataElement e, int type, double value)
boolean startAcquisition ()
boolean stopAcquisition ()
Private Attributes
double acqTime = 0
int cycleFreq
String dataLog = ""
String dataLogOld = ""
Device device
double flowMax = 0
Device flowmeter
double flowStep = 0
int humDelta = 10
long lastIncrementTime = 0
OpMode mode = OpMode.AUTO
long startAcqTime = -1
long startTime = 0
int tempDelta = 1
double tempMax = 0
double tempStep = 0
Thread thread
double time = 0
double timeInter = 0
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
static final long serialVersionUID = 354054054055L
Detailed Description
Definition at line 20 of file Operation.java.
Constructor & Destructor Documentation
Operation() [1/5]
Operation.Operation (DeviceManager _deviceManager, int _cycleFreq)
Definition at line 35 of file Operation.java.
References cycleFreq, deviceManager, and doStart().
Operation() [2/5]
Operation.Operation (DeviceManager _deviceManager, int _cycleFreq)
Definition at line 37 of file Operation.java.
References cycleFreq, deviceManager, doStart(), and setFlowMeter().
Operation() [3/5]
Operation.Operation (DeviceManager _deviceManager, int _cycleFreq)
Definition at line 38 of file Operation.java.
References cycleFreq, deviceManager, and doStart().
Operation() [4/5]
Operation.Operation (DeviceManager _deviceManager, int _cycleFreq)
Definition at line 36 of file Operation.java.
References cycleFreq, deviceManager, and doStart().
Operation() [5/5]
Operation.Operation (Device _device, int _cycleFreq)
Definition at line 37 of file Operation.java.
References cycleFreq, device, and doStart().
Member Function Documentation
doStart() [1/5]
void Operation.doStart ()
Definition at line 43 of file Operation.java.
References thread.
Referenced by Operation().
doStart() [2/5]
void Operation.doStart ()
Definition at line 46 of file Operation.java.
References thread.
doStart() [3/5]
void Operation.doStart ()
Definition at line 47 of file Operation.java.
References thread.
doStart() [4/5]
void Operation.doStart ()
Definition at line 44 of file Operation.java.
References thread.
doStart() [5/5]
void Operation.doStart ()
Definition at line 45 of file Operation.java.
References thread.
doStop() [1/5]
void Operation.doStop ()
Definition at line 48 of file Operation.java.
References thread.
doStop() [2/5]
void Operation.doStop ()
Definition at line 51 of file Operation.java.
References thread.
doStop() [3/5]
void Operation.doStop ()
Definition at line 52 of file Operation.java.
References thread.
doStop() [4/5]
void Operation.doStop ()
Definition at line 49 of file Operation.java.
References thread.
doStop() [5/5]
void Operation.doStop ()
Definition at line 50 of file Operation.java.
References thread.
getDeviceName()
String Operation.getDeviceName ()
Definition at line 68 of file Operation.java.
References device, and Device.name.
getFlowMeter()
String Operation.getFlowMeter ()
Definition at line 65 of file Operation.java.
References flowmeter, and Device.name.
getMode() [1/2]
OpMode Operation.getMode ()
Definition at line 58 of file Operation.java.
References mode.
Referenced by GlgGui.updateGui().
getMode() [2/2]
OpMode Operation.getMode ()
Definition at line 60 of file Operation.java.
References mode.
operationAlone()
boolean Operation.operationAlone () private
Definition at line 209 of file Operation.java.
References deviceManager, DataManager.getDataElement(), humDelta, humPoint, logger, setValue(), DataElement.value, and PWM.vMax.
Referenced by run().
operationAuto()
boolean Operation.operationAuto () private
Definition at line 70 of file Operation.java.
References deviceManager, IntesisBox.fanMax, DataManager.getDataElement(), humDelta, humPoint, logger, setValue(), tempDelta, IntesisBox.tempMax, IntesisBox.tempMin, tempPoint, DataElement.value, and PWM.vMax.
Referenced by run().
operationManual()
boolean Operation.operationManual () private
Definition at line 202 of file Operation.java.
References logger.
Referenced by run().
operationStartRamp() [1/4]
boolean Operation.operationStartRamp () private
Definition at line 114 of file Operation.java.
References flowMax, flowmeter, flowStep, DataManager.getDataElement(), DataTypes.OpMode.IDLE, lastIncrementTime, logger, mode, setValue(), timeInter, and DataElement.value.
Referenced by run().
operationStartRamp() [2/4]
boolean Operation.operationStartRamp () private
Definition at line 202 of file Operation.java.
References acqTime, lastIncrementTime, logger, startAcqTime, startAcquisition(), stopAcquisition(), and timeInter.
operationStartRamp() [3/4]
boolean Operation.operationStartRamp () private
Definition at line 120 of file Operation.java.
References deviceManager, DataManager.getDataElement(), DataTypes.OpMode.IDLE, lastIncrementTime, logger, mode, setValue(), tempMax, tempStep, timeInter, and DataElement.value.
operationStartRamp() [4/4]
boolean Operation.operationStartRamp () private
Definition at line 118 of file Operation.java.
References device, flowMax, flowStep, DataManager.getDataElement(), DataTypes.OpMode.IDLE, lastIncrementTime, logger, mode, setValue(), timeInter, and DataElement.value.
operationStopRamp() [1/4]
boolean Operation.operationStopRamp () private
Definition at line 93 of file Operation.java.
References flowmeter, DataManager.getDataElement(), DataTypes.OpMode.IDLE, lastIncrementTime, logger, mode, setFlowMax(), setFlowStep(), setTime(), setTimeInter(), setValue(), and startTime.
Referenced by run().
operationStopRamp() [2/4]
boolean Operation.operationStopRamp () private
Definition at line 184 of file Operation.java.
References acqTime, DataTypes.OpMode.IDLE, lastIncrementTime, logger, mode, setAcqTime(), setTime(), setTimeInter(), startAcqTime, startTime, stopAcquisition(), time, and timeInter.
operationStopRamp() [3/4]
boolean Operation.operationStopRamp () private
Definition at line 87 of file Operation.java.
References deviceManager, DataManager.getDataElement(), DataTypes.OpMode.IDLE, lastIncrementTime, logger, mode, setTempMax(), setTempStep(), setTime(), setTimeInter(), setValue(), and startTime.
operationStopRamp() [4/4]
boolean Operation.operationStopRamp () private
Definition at line 97 of file Operation.java.
References device, DataManager.getDataElement(), DataTypes.OpMode.IDLE, lastIncrementTime, logger, mode, setFlowMax(), setFlowStep(), setTime(), setTimeInter(), setValue(), and startTime.
run() [1/5]
void Operation.run ()
Definition at line 319 of file Operation.java.
References cycleFreq, logger, mode, operationAlone(), operationAuto(), operationManual(), and saveLog().
run() [2/5]
void Operation.run ()
Definition at line 158 of file Operation.java.
References cycleFreq, lastIncrementTime, logger, mode, operationStartRamp(), operationStopRamp(), setTime(), and startTime.
run() [3/5]
void Operation.run ()
Definition at line 239 of file Operation.java.
References cycleFreq, deviceManager, DataManager.getDataElement(), lastIncrementTime, logger, mode, operationStartRamp(), operationStopRamp(), setTime(), and startTime.
run() [4/5]
void Operation.run ()
Definition at line 176 of file Operation.java.
References cycleFreq, lastIncrementTime, logger, mode, operationStartRamp(), operationStopRamp(), setTime(), and startTime.
run() [5/5]
void Operation.run ()
Definition at line 162 of file Operation.java.
References cycleFreq, lastIncrementTime, logger, mode, operationStartRamp(), operationStopRamp(), setTime(), and startTime.
saveLog()
void Operation.saveLog () private
Definition at line 278 of file Operation.java.
References DataManager.dataList, dataLog, dataLogOld, deviceManager, humPoint, logger, mode, and tempPoint.
Referenced by run().
setACOFF()
void Operation.setACOFF ()
Definition at line 271 of file Operation.java.
References deviceManager, DataManager.getDataElement(), and setValue().
setAcqTime()
void Operation.setAcqTime (int _acqTime)
Definition at line 62 of file Operation.java.
References acqTime, deviceManager, DataManager.getDataElement(), and DataElement.value.
Referenced by operationStopRamp().
setDevice()
void Operation.setDevice (String devicename)
Definition at line 64 of file Operation.java.
References device, and deviceManager.
setFlowMax() [1/2]
void Operation.setFlowMax (int _flowMax)
Definition at line 69 of file Operation.java.
References flowMax, flowmeter, DataManager.getDataElement(), and DataElement.value.
Referenced by operationStopRamp().
setFlowMax() [2/2]
void Operation.setFlowMax (int _flowMax)
Definition at line 72 of file Operation.java.
References device, flowMax, DataManager.getDataElement(), and DataElement.value.
setFlowMeter()
void Operation.setFlowMeter (String devicename)
Definition at line 61 of file Operation.java.
References deviceManager, and flowmeter.
Referenced by Operation().
setFlowStep() [1/2]
void Operation.setFlowStep (int _flowStep)
Definition at line 75 of file Operation.java.
References flowmeter, flowStep, DataManager.getDataElement(), and DataElement.value.
Referenced by operationStopRamp().
setFlowStep() [2/2]
void Operation.setFlowStep (int _flowStep)
Definition at line 79 of file Operation.java.
References device, flowStep, DataManager.getDataElement(), and DataElement.value.
setHumPoint()
void Operation.setHumPoint (int _humPoint)
Definition at line 66 of file Operation.java.
References humPoint.
Referenced by GlgGui.createAndShowGui().
setMode() [1/5]
void Operation.setMode (OpMode _mode)
Definition at line 54 of file Operation.java.
References mode.
Referenced by GlgPCounter2Gui.InputListener.InputCallback(), and GlgFlowMeterGui.InputListener.InputCallback().
setMode() [2/5]
void Operation.setMode (OpMode _mode)
Definition at line 57 of file Operation.java.
References mode.
setMode() [3/5]
void Operation.setMode (OpMode _mode)
Definition at line 58 of file Operation.java.
References mode.
setMode() [4/5]
void Operation.setMode (OpMode _mode)
Definition at line 55 of file Operation.java.
References mode.
setMode() [5/5]
void Operation.setMode (OpMode _mode)
Definition at line 56 of file Operation.java.
References mode.
setTempMax()
void Operation.setTempMax (int _tempMax)
Definition at line 59 of file Operation.java.
References deviceManager, DataManager.getDataElement(), tempMax, and DataElement.value.
Referenced by operationStopRamp().
setTempPoint()
void Operation.setTempPoint (int _tempPoint)
Definition at line 62 of file Operation.java.
References tempPoint.
Referenced by GlgGui.createAndShowGui().
setTempStep()
void Operation.setTempStep (int _tempStep)
Definition at line 66 of file Operation.java.
References deviceManager, DataManager.getDataElement(), tempStep, and DataElement.value.
Referenced by operationStopRamp().
setTime() [1/4]
void Operation.setTime (double _time)
Definition at line 87 of file Operation.java.
References flowmeter, DataManager.getDataElement(), time, and DataElement.value.
Referenced by operationStopRamp(), and run().
setTime() [2/4]
void Operation.setTime (double _time)
Definition at line 78 of file Operation.java.
References deviceManager, DataManager.getDataElement(), time, and DataElement.value.
setTime() [3/4]
void Operation.setTime (double _time)
Definition at line 80 of file Operation.java.
References deviceManager, DataManager.getDataElement(), time, and DataElement.value.
setTime() [4/4]
void Operation.setTime (double _time)
Definition at line 91 of file Operation.java.
References device, DataManager.getDataElement(), time, and DataElement.value.
setTimeInter() [1/4]
void Operation.setTimeInter (int _timeInter)
Definition at line 81 of file Operation.java.
References flowmeter, DataManager.getDataElement(), timeInter, and DataElement.value.
Referenced by operationStopRamp().
setTimeInter() [2/4]
void Operation.setTimeInter (int _timeInter)
Definition at line 70 of file Operation.java.
References deviceManager, DataManager.getDataElement(), logger, timeInter, and DataElement.value.
setTimeInter() [3/4]
void Operation.setTimeInter (int _timeInter)
Definition at line 73 of file Operation.java.
References deviceManager, DataManager.getDataElement(), timeInter, and DataElement.value.
setTimeInter() [4/4]
void Operation.setTimeInter (int _timeInter)
Definition at line 85 of file Operation.java.
References device, DataManager.getDataElement(), timeInter, and DataElement.value.
setValue() [1/5]
void Operation.setValue (Device d, DataElement e, int type, double value) private
Definition at line 258 of file Operation.java.
References Device.commandSetQueue, logger, DataElement.name, Device.name, DataElement.setvalue, and DataElement.value.
Referenced by operationAlone(), operationAuto(), operationStartRamp(), operationStopRamp(), setACOFF(), startAcquisition(), and stopAcquisition().
setValue() [2/5]
void Operation.setValue (Device d, DataElement e, int type, double value) private
Definition at line 144 of file Operation.java.
References Device.commandSetQueue, logger, DataElement.name, Device.name, DataElement.setvalue, and DataElement.value.
setValue() [3/5]
void Operation.setValue (Device d, DataElement e, int type, double value) private
Definition at line 225 of file Operation.java.
References Device.commandSetQueue, logger, DataElement.name, Device.name, DataElement.setvalue, and DataElement.value.
setValue() [4/5]
void Operation.setValue (Device d, DataElement e, int type, double value) private
Definition at line 162 of file Operation.java.
References Device.commandSetQueue, logger, DataElement.name, Device.name, DataElement.setvalue, and DataElement.value.
setValue() [5/5]
void Operation.setValue (Device d, DataElement e, int type, double value) private
Definition at line 148 of file Operation.java.
References Device.commandSetQueue, logger, DataElement.name, Device.name, DataElement.setvalue, and DataElement.value.
startAcquisition()
boolean Operation.startAcquisition () private
Definition at line 141 of file Operation.java.
References deviceManager, DataManager.getDataElement(), lastIncrementTime, logger, setValue(), and startAcqTime.
Referenced by operationStartRamp().
stopAcquisition()
boolean Operation.stopAcquisition () private
Definition at line 98 of file Operation.java.
References acqTime, deviceManager, DataManager.getDataElement(), lastIncrementTime, logger, setValue(), and startAcqTime.
Referenced by operationStartRamp(), and operationStopRamp().
Member Data Documentation
acqTime
double Operation.acqTime = 0 private
Definition at line 29 of file Operation.java.
Referenced by operationStartRamp(), operationStopRamp(), setAcqTime(), and stopAcquisition().
cycleFreq
int Operation.cycleFreq private
Definition at line 26 of file Operation.java.
Referenced by Operation(), and run().
dataLog
String Operation.dataLog = "" private
Definition at line 32 of file Operation.java.
Referenced by saveLog().
dataLogOld
String Operation.dataLogOld = "" private
Definition at line 33 of file Operation.java.
Referenced by saveLog().
device
Device Operation.device private
Definition at line 27 of file Operation.java.
Referenced by getDeviceName(), Operation(), operationStartRamp(), operationStopRamp(), setDevice(), setFlowMax(), setFlowStep(), setTime(), and setTimeInter().
deviceManager
DeviceManager Operation.deviceManager
Definition at line 27 of file Operation.java.
Referenced by GlgChildGui.GlgChildGui(), GlgGui.GlgGui(), Operation(), operationAlone(), operationAuto(), operationStartRamp(), operationStopRamp(), run(), saveLog(), setACOFF(), setAcqTime(), setDevice(), setFlowMeter(), setTempMax(), setTempStep(), setTime(), setTimeInter(), startAcquisition(), and stopAcquisition().
flowMax
double Operation.flowMax = 0 private
Definition at line 29 of file Operation.java.
Referenced by operationStartRamp(), and setFlowMax().
flowmeter
Device Operation.flowmeter private
Definition at line 27 of file Operation.java.
Referenced by getFlowMeter(), operationStartRamp(), operationStopRamp(), setFlowMax(), setFlowMeter(), setFlowStep(), setTime(), and setTimeInter().
flowStep
double Operation.flowStep = 0 private
Definition at line 30 of file Operation.java.
Referenced by operationStartRamp(), and setFlowStep().
humDelta
int Operation.humDelta = 10 private
Definition at line 28 of file Operation.java.
Referenced by operationAlone(), and operationAuto().
humPoint
int Operation.humPoint
Definition at line 30 of file Operation.java.
Referenced by operationAlone(), operationAuto(), saveLog(), and setHumPoint().
lastIncrementTime
long Operation.lastIncrementTime = 0 private
Definition at line 35 of file Operation.java.
Referenced by operationStartRamp(), operationStopRamp(), run(), startAcquisition(), and stopAcquisition().
logger
static final Logger Operation.logger = Logger.getLogger("Main") static private
Definition at line 24 of file Operation.java.
Referenced by operationAlone(), operationAuto(), operationManual(), operationStartRamp(), operationStopRamp(), run(), saveLog(), setTimeInter(), setValue(), startAcquisition(), and stopAcquisition().
mode
OpMode Operation.mode = OpMode.AUTO private
Definition at line 25 of file Operation.java.
Referenced by getMode(), operationStartRamp(), operationStopRamp(), run(), saveLog(), and setMode().
serialVersionUID
static final long Operation.serialVersionUID = 354054054055L static private
Definition at line 22 of file Operation.java.
startAcqTime
long Operation.startAcqTime = -1 private
Definition at line 33 of file Operation.java.
Referenced by operationStartRamp(), operationStopRamp(), startAcquisition(), and stopAcquisition().
startTime
long Operation.startTime = 0 private
Definition at line 34 of file Operation.java.
Referenced by operationStopRamp(), and run().
tempDelta
int Operation.tempDelta = 1 private
Definition at line 29 of file Operation.java.
Referenced by operationAuto().
tempMax
double Operation.tempMax = 0 private
Definition at line 28 of file Operation.java.
Referenced by operationStartRamp(), and setTempMax().
tempPoint
int Operation.tempPoint
Definition at line 31 of file Operation.java.
Referenced by operationAuto(), saveLog(), and setTempPoint().
tempStep
double Operation.tempStep = 0 private
Definition at line 29 of file Operation.java.
Referenced by operationStartRamp(), and setTempStep().
thread
Thread Operation.thread private
Definition at line 23 of file Operation.java.
Referenced by doStart(), and doStop().
time
double Operation.time = 0 private
Definition at line 32 of file Operation.java.
Referenced by operationStopRamp(), and setTime().
timeInter
double Operation.timeInter = 0 private
Definition at line 31 of file Operation.java.
Referenced by operationStartRamp(), operationStopRamp(), and setTimeInter().
The documentation for this class was generated from the following file:
work_clim/Operation.java