SCADARPI API: DataManager Class Reference
DataManager Class Reference
Public Member Functions
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Public Attributes
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Private Attributes
static final Logger logger = Logger.getLogger("Main")
Detailed Description
Definition at line 13 of file DataManager.java.
Constructor & Destructor Documentation
DataManager() [1/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [2/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [3/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [4/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [5/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [6/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [7/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [8/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [9/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [10/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [11/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [12/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [13/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [14/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [15/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [16/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [17/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [18/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [19/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [20/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [21/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
DataManager() [22/22]
DataManager.DataManager ()
Definition at line 22 of file DataManager.java.
References dataList.
Member Function Documentation
addDataElement() [1/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
Referenced by Chiller.Chiller(), Controllino.Controllino(), Controllino_1.Controllino_1(), Controllino_2.Controllino_2(), Controllino_3.Controllino_3(), DS2438.DS2438(), FlowMeterModbusMaster.FlowMeterModbusMaster(), IntesisBox.IntesisBox(), IonicAgilentDual.IonicAgilentDual(), LakeShore.LakeShore(), MaxiGauge.MaxiGauge(), MksRotor.MksRotor(), PCounterMasterRTU.PCounterMasterRTU(), PWM.PWM(), RgaHidenHal201RC.RgaHidenHal201RC(), RgaPfeifferQms200.RgaPfeifferQms200(), Sicem.Sicem(), SupervisorClient.SupervisorClient(), SupervisorClient2.SupervisorClient2(), TCMuxShield.TCMuxShield(), TitaneVarianTSP_22.TitaneVarianTSP_22(), TitaneVarianTSP_32.TitaneVarianTSP_32(), TurboPfeifferDCU.TurboPfeifferDCU(), TurboVarianV81AG.TurboVarianV81AG(), Vacuum.Vacuum(), VentingOperationController.VentingOperationController(), and XGSGauge.XGSGauge().
addDataElement() [2/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [3/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [4/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [5/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [6/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [7/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [8/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [9/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [10/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [11/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [12/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [13/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [14/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [15/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [16/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [17/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [18/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [19/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [20/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [21/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
addDataElement() [22/22]
void DataManager.addDataElement (DataElement dataElement)
Definition at line 26 of file DataManager.java.
References dataList, and DataElement.name.
getDataElement() [1/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
Referenced by RgaHidenHal201RC.executeCommand(), RgaPfeifferQms200.executeCommand(), RgaHidenHal201RC.GetAllParamsFromDevice(), VentingOperations.getG2DataElement(), GlgCryoIbDetStatusDetailsGui.InputListener.InputCallback(), GlgDryGui.InputListener.InputCallback(), GlgGaugeGui.InputListener.InputCallback(), GlgIonicGui.InputListener.InputCallback(), GlgRGAGui.InputListener.InputCallback(), GlgTitane_22Gui.InputListener.InputCallback(), GlgTitane_32Gui.InputListener.InputCallback(), GlgTurboGui.InputListener.InputCallback(), GlgValveGui.InputListener.InputCallback(), GlgXGSGaugeGui.InputListener.InputCallback(), GlgCryo1500wIntGui.InputListener.InputCallback(), GlgCryo1500wStatusDetailsGui.InputListener.InputCallback(), GlgLinkStatusDetailsGui.InputListener.InputCallback(), GlgRGA3Gui.InputListener.InputCallback(), GlgPCounter2Gui.InputListener.InputCallback(), GlgPCounterStatusDetailsGui.InputListener.InputCallback(), GlgRgaStatusDetailsGui.InputListener.InputCallback(), GlgSqzStatusDetailsGui.InputListener.InputCallback(), GlgSqzVacuumGui.InputListener.InputCallback(), GlgTitaneGui.InputListener.InputCallback(), GlgTurboPfeifferDCUGui.InputListener.InputCallback(), GlgTube1500wStatusDetailsGui.InputListener.InputCallback(), GlgFlowMeterGui.InputListener.InputCallback(), Operation.operationAlone(), Operation.operationAuto(), Operation.operationStartRamp(), Operation.operationStopRamp(), PCounterMasterRTU.PCounterMasterRTU(), PWM.PWM(), RgaHidenHal201RC.resetDevice(), VentingTableView.resolveDataElementFromMap(), Operation.run(), VentingOperations.sendFlowUsingStatusKey(), VentingOperations.sendPumpCommand(), VentingOperations.sendValveCommand(), Operation.setACOFF(), Operation.setAcqTime(), Operation.setFlowMax(), Operation.setFlowStep(), VentingOperations.setOperationStep(), Operation.setTempMax(), Operation.setTempStep(), Operation.setTime(), Operation.setTimeInter(), Operation.startAcquisition(), Operation.stopAcquisition(), RgaHidenHal201RC.StopScanDevice(), SupervisorClient.updateDeviceData(), SupervisorClient2.updateDeviceData(), DS2438.updateDeviceData(), IntesisBox.updateDeviceData(), Controllino_1.updateDeviceData(), MaxiGauge.updateDeviceData(), TurboVarianV81AG.updateDeviceData(), Chiller.updateDeviceData(), Controllino_2.updateDeviceData(), LakeShore.updateDeviceData(), TCMuxShield.updateDeviceData(), FlowMeterModbusMaster.updateDeviceData(), Controllino_3.updateDeviceData(), RgaHidenHal201RC.updateDeviceData(), TurboPfeifferDCU.updateDeviceData(), Controllino.updateDeviceData(), PCounterMasterRTU.updateDeviceData(), IonicAgilentDual.updateDeviceData(), RgaPfeifferQms200.updateDeviceData(), TitaneVarianTSP_22.updateDeviceData(), TitaneVarianTSP_32.updateDeviceData(), XGSGauge.updateDeviceData(), Vacuum.updateDeviceData(), MksRotor.updateDeviceData(), Sicem.updateDeviceData(), VentingOperationController.updateDeviceData(), GlgChildGui.updateGui(), GlgGui.updateGui(), VentingOperationController.VentingOperationController(), and ModbusSlaveThread.ModbusSlaveDataHolder.writeHoldingRegister().
getDataElement() [2/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [3/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [4/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [5/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [6/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [7/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [8/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [9/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [10/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [11/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [12/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [13/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [14/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [15/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [16/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [17/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [18/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [19/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [20/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [21/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [22/44]
DataElement DataManager.getDataElement (int mbRegisterOffset)
Definition at line 30 of file DataManager.java.
References dataList, and DataElement.mbRegisterOffset.
getDataElement() [23/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [24/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [25/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [26/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [27/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [28/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [29/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [30/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [31/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [32/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [33/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [34/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [35/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [36/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [37/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [38/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [39/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [40/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [41/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [42/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [43/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
getDataElement() [44/44]
DataElement DataManager.getDataElement (String name)
Definition at line 40 of file DataManager.java.
References dataList.
setDataElementValue() [1/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [2/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [3/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [4/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [5/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [6/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [7/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [8/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [9/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [10/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [11/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [12/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [13/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [14/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [15/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [16/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [17/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [18/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [19/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [20/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [21/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setDataElementValue() [22/22]
void DataManager.setDataElementValue (String name, double value)
Definition at line 47 of file DataManager.java.
References dataList, and DataElement.value.
setHoldingRegisters() [1/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [2/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [3/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [4/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [5/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [6/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [7/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [8/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [9/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [10/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [11/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [12/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [13/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [14/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [15/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [16/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [17/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [18/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [19/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [20/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [21/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
setHoldingRegisters() [22/22]
void DataManager.setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
Definition at line 54 of file DataManager.java.
References holdingRegisters.
updateModbusRegisters() [1/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
Referenced by Device.run().
updateModbusRegisters() [2/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [3/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [4/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [5/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [6/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [7/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [8/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [9/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [10/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [11/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [12/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [13/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, DataElement.deviceName, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [14/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [15/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [16/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [17/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [18/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [19/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [20/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [21/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
updateModbusRegisters() [22/22]
void DataManager.updateModbusRegisters ()
Definition at line 58 of file DataManager.java.
References dataList, holdingRegisters, logger, DataElement.mbRegisterOffset, DataElement.mbRegisterType, DataElement.name, DataTypes.DataType.TRIGGER, DataElement.type, and DataElement.value.
Member Data Documentation
dataList
Hashtable< String, DataElement > DataManager.dataList
Definition at line 15 of file DataManager.java.
Referenced by addDataElement(), Device.addModbusCommand(), DataManager(), getDataElement(), Operation.saveLog(), setDataElementValue(), and updateModbusRegisters().
holdingRegisters
ModbusHoldingRegisters DataManager.holdingRegisters
Definition at line 16 of file DataManager.java.
Referenced by Device.addModbusCommand(), Controllino_1.executeCommand(), MaxiGauge.executeCommand(), TurboVarianV81AG.executeCommand(), Controllino_2.executeCommand(), Controllino_3.executeCommand(), RgaHidenHal201RC.executeCommand(), TurboPfeifferDCU.executeCommand(), Controllino.executeCommand(), PCounterMasterRTU.executeCommand(), IonicAgilentDual.executeCommand(), RgaPfeifferQms200.executeCommand(), TitaneVarianTSP_22.executeCommand(), TitaneVarianTSP_32.executeCommand(), XGSGauge.executeCommand(), Vacuum.executeCommand(), MksRotor.executeCommand(), VentingOperationController.executeCommand(), Device.popCommand(), VentingTableView.pulseOperationCommand(), setHoldingRegisters(), and updateModbusRegisters().
logger
static final Logger DataManager.logger = Logger.getLogger("Main") static private
Definition at line 20 of file DataManager.java.
Referenced by updateModbusRegisters().
mbRegisterEnd
int DataManager.mbRegisterEnd
Definition at line 18 of file DataManager.java.
Referenced by Chiller.Chiller(), Controllino.Controllino(), Controllino_1.Controllino_1(), Controllino_2.Controllino_2(), Controllino_3.Controllino_3(), DS2438.DS2438(), FlowMeterModbusMaster.FlowMeterModbusMaster(), IntesisBox.IntesisBox(), IonicAgilentDual.IonicAgilentDual(), LakeShore.LakeShore(), Main.main(), MaxiGauge.MaxiGauge(), MksRotor.MksRotor(), PCounterMasterRTU.PCounterMasterRTU(), PWM.PWM(), RgaHidenHal201RC.RgaHidenHal201RC(), RgaPfeifferQms200.RgaPfeifferQms200(), Sicem.Sicem(), SupervisorClient.SupervisorClient(), SupervisorClient2.SupervisorClient2(), TCMuxShield.TCMuxShield(), TitaneVarianTSP_22.TitaneVarianTSP_22(), TitaneVarianTSP_32.TitaneVarianTSP_32(), TurboPfeifferDCU.TurboPfeifferDCU(), TurboVarianV81AG.TurboVarianV81AG(), Vacuum.Vacuum(), VentingOperationController.VentingOperationController(), and XGSGauge.XGSGauge().
mbRegisterStart
int DataManager.mbRegisterStart
Definition at line 17 of file DataManager.java.
Referenced by Chiller.Chiller(), Controllino.Controllino(), Controllino_1.Controllino_1(), Controllino_2.Controllino_2(), Controllino_3.Controllino_3(), DS2438.DS2438(), FlowMeterModbusMaster.FlowMeterModbusMaster(), IntesisBox.IntesisBox(), IonicAgilentDual.IonicAgilentDual(), LakeShore.LakeShore(), MaxiGauge.MaxiGauge(), MksRotor.MksRotor(), PCounterMasterRTU.PCounterMasterRTU(), PWM.PWM(), RgaHidenHal201RC.RgaHidenHal201RC(), RgaPfeifferQms200.RgaPfeifferQms200(), Sicem.Sicem(), SupervisorClient.SupervisorClient(), SupervisorClient2.SupervisorClient2(), TCMuxShield.TCMuxShield(), TitaneVarianTSP_22.TitaneVarianTSP_22(), TitaneVarianTSP_32.TitaneVarianTSP_32(), TurboPfeifferDCU.TurboPfeifferDCU(), TurboVarianV81AG.TurboVarianV81AG(), Vacuum.Vacuum(), VentingOperationController.VentingOperationController(), and XGSGauge.XGSGauge().
The documentation for this class was generated from the following file:
work_1500npanel/DataManager.java