SCADARPI API: Controllino_2 Class Reference
Controllino_2 Class Reference
Public Member Functions
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int bitRead (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
int clearBit (int target, int bit)
Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
void executeCommand (DataElement e)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
int setBit (int target, int bit)
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
void updateDeviceData ()
Public Member Functions inherited from Device
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void addModbusCommand ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStart ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void doStop ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void popCommand ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void run ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
void setErrorComStatus ()
Public Member Functions inherited from DataManager
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
void addDataElement (DataElement dataElement)
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataManager ()
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (int mbRegisterOffset)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
DataElement getDataElement (String name)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setDataElementValue (String name, double value)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void setHoldingRegisters (ModbusHoldingRegisters _holdingRegisters)
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
void updateModbusRegisters ()
Private Attributes
I2C_Comm i2c
Static Private Attributes
static final int ARD_RESET_BIT = 31
static final int BYPASS_OFF_CMD_BIT = 13
static final int BYPASS_OFF_STATUS_BIT = 15
static final int BYPASS_ON_CMD_BIT = 12
static final int BYPASS_ON_STATUS_BIT = 14
static final int CHANNEL_1_OFF_CMD_BIT = 5
static final int CHANNEL_1_OFF_STATUS_BIT = 1
static final int CHANNEL_1_ON_CMD_BIT = 4
static final int CHANNEL_1_ON_STATUS_BIT = 0
static final int CHANNEL_2_OFF_CMD_BIT = 7
static final int CHANNEL_2_OFF_STATUS_BIT = 3
static final int CHANNEL_2_ON_CMD_BIT = 6
static final int CHANNEL_2_ON_STATUS_BIT = 2
static final int CHILLER_OFF_CMD_BIT = 11
static final int CHILLER_ON_CMD_BIT = 10
static final int CHILLER_STATUS_BIT = 4
static final int COMPRESSAIR_STATUS_BIT = 21
static final int CP800_OFF_CMD_BIT = 9
static final int CP800_ON_CMD_BIT = 8
static final int CP800_STATUS_BIT = 3
static final int CP900_OFF_CMD_BIT = 7
static final int CP900_ON_CMD_BIT = 6
static final int CP900_STATUS_BIT = 2
static final int FLUX_STATUS_BIT = 1
static final int LEVEL_STATUS_BIT = 0
static final Logger logger = Logger.getLogger("Main")
static final int MUXSHIELD_COMERR_BIT = 14
static final int MUXSHIELD_COMERR_STATUS_BIT = 10
static final int P22_OFF_CMD_BIT = 17
static final int P22_ON_CMD_BIT = 16
static final int P22_STATUS_BIT = 18
static final int PUMP_OFF_CMD_BIT = 13
static final int PUMP_ON_CMD_BIT = 12
static final int PUMP_STATUS_BIT = 5
static final int SICEM_ALRM_STATUS_BIT = 8
static final int SICEM_COMERR_STATUS_BIT = 9
static final int V1_CLOSE_CMD_BIT = 9
static final int V1_CLOSE_STATUS_BIT = 11
static final int V1_OPEN_CMD_BIT = 8
static final int V1_OPEN_STATUS_BIT = 10
static final int V21_CLOSE_CMD_BIT = 1
static final int V21_CLOSE_STATUS_BIT = 3
static final int V21_OPEN_CMD_BIT = 0
static final int V21_OPEN_STATUS_BIT = 2
static final int V22_CLOSE_CMD_BIT = 5
static final int V22_CLOSE_STATUS_BIT = 7
static final int V22_OPEN_CMD_BIT = 4
static final int V22_OPEN_STATUS_BIT = 6
static final int V23_CLOSE_STATUS_BIT = 20
static final int V23_OPEN_STATUS_BIT = 19
static final int VE1_CLOSE_STATUS_BIT = 18
static final int VE1_OPEN_STATUS_BIT = 17
static final int VE2_CLOSE_STATUS_BIT = 20
static final int VE2_OPEN_STATUS_BIT = 19
static final int VENT_CLOSE_CMD_BIT = 1
static final int VENT_CLOSE_STATUS_BIT = 3
static final int VENT_OPEN_CMD_BIT = 0
static final int VENT_OPEN_STATUS_BIT = 2
static final int VENTSOFT_CLOSE_CMD_BIT = 5
static final int VENTSOFT_OPEN_CMD_BIT = 4
static final int VP_CLOSE_CMD_BIT = 7
static final int VP_CLOSE_STATUS_BIT = 9
static final int VP_OPEN_CMD_BIT = 6
static final int VP_OPEN_STATUS_BIT = 8
static final int VSPARE_OFF_CMD_BIT = 15
static final int VSPARE_ON_CMD_BIT = 14
static final int VSPARE_STATUS_BIT = 16
Additional Inherited Members
Public Attributes inherited from Device
String aliasName
LinkedList< DataElement > commandSetQueue = new LinkedList<DataElement>()
int delay
final Lock modbusmutex = new ReentrantLock(true)
final Lock mutex = new ReentrantLock(true)
String name
Public Attributes inherited from DataManager
Hashtable< String, DataElement > dataList
ModbusHoldingRegisters holdingRegisters
int mbRegisterEnd
int mbRegisterStart
Static Public Attributes inherited from Device
static final Lock busmutex = new ReentrantLock(true)
Protected Attributes inherited from Device
boolean comErr = false
int comm_cnt_failure = 0
int comm_max_failure = 5
final GpioController gpio = initGpioController()
boolean hasWarned = false
GpioPinDigitalInput i2c_in
GpioPinDigitalOutput i2c_out
int pause = 1000
int sleep_period = 1000
int sleepPeriod = 1000
int sleepTime = 1000
boolean use_i2c_out = false
Static Protected Attributes inherited from Device
static final GpioController gpio = initGpioController()
Detailed Description
Definition at line 14 of file Controllino_2.java.
Constructor & Destructor Documentation
Controllino_2() [1/8]
Controllino_2.Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 37 of file Controllino_2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.TRIGGER.
Controllino_2() [2/8]
Controllino_2.Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_2() [3/8]
Controllino_2.Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_2() [4/8]
Controllino_2.Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_2() [5/8]
Controllino_2.Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_2() [6/8]
Controllino_2.Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 44 of file Controllino_2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, DataTypes.DataType.TRIGGER, and Device.use_i2c_out.
Controllino_2() [7/8]
Controllino_2.Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 43 of file Controllino_2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, DataTypes.DataType.READ_ONLY_VALUE, and DataTypes.DataType.TRIGGER.
Controllino_2() [8/8]
Controllino_2.Controllino_2 (String _name, int _mbRegisterStart, int i2c_addr)
Definition at line 32 of file Controllino_2.java.
References DataManager.addDataElement(), DataTypes.DataType.COM_STATUS, i2c, DataTypes.RegisterType.INT16, logger, DataManager.mbRegisterEnd, DataManager.mbRegisterStart, Device.name, DataTypes.DataType.READ_ONLY_STATUS, and DataTypes.DataType.TRIGGER.
Member Function Documentation
bitRead() [1/8]
int Controllino_2.bitRead (int target, int bit)
Definition at line 234 of file Controllino_2.java.
Referenced by updateDeviceData().
bitRead() [2/8]
int Controllino_2.bitRead (int target, int bit)
Definition at line 271 of file Controllino_2.java.
bitRead() [3/8]
int Controllino_2.bitRead (int target, int bit)
Definition at line 271 of file Controllino_2.java.
bitRead() [4/8]
int Controllino_2.bitRead (int target, int bit)
Definition at line 270 of file Controllino_2.java.
bitRead() [5/8]
int Controllino_2.bitRead (int target, int bit)
Definition at line 270 of file Controllino_2.java.
bitRead() [6/8]
int Controllino_2.bitRead (int target, int bit)
Definition at line 273 of file Controllino_2.java.
bitRead() [7/8]
int Controllino_2.bitRead (int target, int bit)
Definition at line 270 of file Controllino_2.java.
bitRead() [8/8]
int Controllino_2.bitRead (int target, int bit)
Definition at line 207 of file Controllino_2.java.
clearBit() [1/8]
int Controllino_2.clearBit (int target, int bit)
Definition at line 242 of file Controllino_2.java.
Referenced by executeCommand().
clearBit() [2/8]
int Controllino_2.clearBit (int target, int bit)
Definition at line 279 of file Controllino_2.java.
clearBit() [3/8]
int Controllino_2.clearBit (int target, int bit)
Definition at line 279 of file Controllino_2.java.
clearBit() [4/8]
int Controllino_2.clearBit (int target, int bit)
Definition at line 278 of file Controllino_2.java.
clearBit() [5/8]
int Controllino_2.clearBit (int target, int bit)
Definition at line 278 of file Controllino_2.java.
clearBit() [6/8]
int Controllino_2.clearBit (int target, int bit)
Definition at line 281 of file Controllino_2.java.
clearBit() [7/8]
int Controllino_2.clearBit (int target, int bit)
Definition at line 278 of file Controllino_2.java.
clearBit() [8/8]
int Controllino_2.clearBit (int target, int bit)
Definition at line 215 of file Controllino_2.java.
executeCommand() [1/8]
void Controllino_2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 167 of file Controllino_2.java.
References CHILLER_OFF_CMD_BIT, CHILLER_ON_CMD_BIT, clearBit(), CP800_OFF_CMD_BIT, CP800_ON_CMD_BIT, CP900_OFF_CMD_BIT, CP900_ON_CMD_BIT, DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, PUMP_OFF_CMD_BIT, PUMP_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [2/8]
void Controllino_2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_2.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [3/8]
void Controllino_2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 203 of file Controllino_2.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, P22_OFF_CMD_BIT, P22_ON_CMD_BIT, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), V1_CLOSE_CMD_BIT, V1_OPEN_CMD_BIT, V21_CLOSE_CMD_BIT, V21_OPEN_CMD_BIT, V22_CLOSE_CMD_BIT, V22_OPEN_CMD_BIT, DataElement.value, and I2C_Comm.WritePlusCRC32().
executeCommand() [4/8]
void Controllino_2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 202 of file Controllino_2.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.value, VENT_CLOSE_CMD_BIT, VENT_OPEN_CMD_BIT, VENTSOFT_CLOSE_CMD_BIT, VENTSOFT_OPEN_CMD_BIT, VP_CLOSE_CMD_BIT, VP_OPEN_CMD_BIT, VSPARE_OFF_CMD_BIT, VSPARE_ON_CMD_BIT, and I2C_Comm.WritePlusCRC32().
executeCommand() [5/8]
void Controllino_2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 202 of file Controllino_2.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.value, VENT_CLOSE_CMD_BIT, VENT_OPEN_CMD_BIT, VENTSOFT_CLOSE_CMD_BIT, VENTSOFT_OPEN_CMD_BIT, VP_CLOSE_CMD_BIT, VP_OPEN_CMD_BIT, VSPARE_OFF_CMD_BIT, VSPARE_ON_CMD_BIT, and I2C_Comm.WritePlusCRC32().
executeCommand() [6/8]
void Controllino_2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 210 of file Controllino_2.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, I2C_Comm.Read(), setBit(), Device.setErrorComStatus(), DataElement.value, VENT_CLOSE_CMD_BIT, VENT_OPEN_CMD_BIT, VENTSOFT_CLOSE_CMD_BIT, VENTSOFT_OPEN_CMD_BIT, VP_CLOSE_CMD_BIT, VP_OPEN_CMD_BIT, VSPARE_OFF_CMD_BIT, VSPARE_ON_CMD_BIT, and I2C_Comm.Write().
executeCommand() [7/8]
void Controllino_2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 202 of file Controllino_2.java.
References BYPASS_OFF_CMD_BIT, BYPASS_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, I2C_Comm.Read4bytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataElement.value, VENT_CLOSE_CMD_BIT, VENT_OPEN_CMD_BIT, VENTSOFT_CLOSE_CMD_BIT, VENTSOFT_OPEN_CMD_BIT, VP_CLOSE_CMD_BIT, VP_OPEN_CMD_BIT, VSPARE_OFF_CMD_BIT, VSPARE_ON_CMD_BIT, and I2C_Comm.WritePlusCRC32().
executeCommand() [8/8]
void Controllino_2.executeCommand (DataElement e)
Reimplemented from Device.
Definition at line 156 of file Controllino_2.java.
References CHANNEL_1_OFF_CMD_BIT, CHANNEL_1_ON_CMD_BIT, CHANNEL_2_OFF_CMD_BIT, CHANNEL_2_ON_CMD_BIT, clearBit(), DataManager.holdingRegisters, i2c, logger, DataElement.mbRegisterOffset, DataElement.name, Device.name, I2C_Comm.ReadbytesPlusCRC32(), setBit(), Device.setErrorComStatus(), DataTypes.DataType.TRIGGER, DataElement.type, DataElement.value, and I2C_Comm.WritePlusCRC32().
setBit() [1/8]
int Controllino_2.setBit (int target, int bit)
Definition at line 238 of file Controllino_2.java.
Referenced by executeCommand().
setBit() [2/8]
int Controllino_2.setBit (int target, int bit)
Definition at line 275 of file Controllino_2.java.
setBit() [3/8]
int Controllino_2.setBit (int target, int bit)
Definition at line 275 of file Controllino_2.java.
setBit() [4/8]
int Controllino_2.setBit (int target, int bit)
Definition at line 274 of file Controllino_2.java.
setBit() [5/8]
int Controllino_2.setBit (int target, int bit)
Definition at line 274 of file Controllino_2.java.
setBit() [6/8]
int Controllino_2.setBit (int target, int bit)
Definition at line 277 of file Controllino_2.java.
setBit() [7/8]
int Controllino_2.setBit (int target, int bit)
Definition at line 274 of file Controllino_2.java.
setBit() [8/8]
int Controllino_2.setBit (int target, int bit)
Definition at line 211 of file Controllino_2.java.
updateDeviceData() [1/8]
void Controllino_2.updateDeviceData ()
Reimplemented from Device.
Definition at line 78 of file Controllino_2.java.
References bitRead(), Device.busmutex, CHILLER_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, CP800_STATUS_BIT, CP900_STATUS_BIT, FLUX_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, LEVEL_STATUS_BIT, logger, Device.name, Device.popCommand(), PUMP_STATUS_BIT, I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), and DataElement.value.
updateDeviceData() [2/8]
void Controllino_2.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_2.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [3/8]
void Controllino_2.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_2.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, P22_STATUS_BIT, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), V1_CLOSE_STATUS_BIT, V1_OPEN_STATUS_BIT, V21_CLOSE_STATUS_BIT, V21_OPEN_STATUS_BIT, V22_CLOSE_STATUS_BIT, V22_OPEN_STATUS_BIT, V23_CLOSE_STATUS_BIT, V23_OPEN_STATUS_BIT, and DataElement.value.
updateDeviceData() [4/8]
void Controllino_2.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_2.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), DataElement.value, VE1_CLOSE_STATUS_BIT, VE1_OPEN_STATUS_BIT, VE2_CLOSE_STATUS_BIT, VE2_OPEN_STATUS_BIT, VENT_CLOSE_STATUS_BIT, VENT_OPEN_STATUS_BIT, VP_CLOSE_STATUS_BIT, VP_OPEN_STATUS_BIT, and VSPARE_STATUS_BIT.
updateDeviceData() [5/8]
void Controllino_2.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_2.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), DataElement.value, VE1_CLOSE_STATUS_BIT, VE1_OPEN_STATUS_BIT, VE2_CLOSE_STATUS_BIT, VE2_OPEN_STATUS_BIT, VENT_CLOSE_STATUS_BIT, VENT_OPEN_STATUS_BIT, VP_CLOSE_STATUS_BIT, VP_OPEN_STATUS_BIT, and VSPARE_STATUS_BIT.
updateDeviceData() [6/8]
void Controllino_2.updateDeviceData ()
Reimplemented from Device.
Definition at line 95 of file Controllino_2.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.gpio, Device.hasWarned, i2c, Device.i2c_in, Device.i2c_out, logger, Device.name, Device.popCommand(), I2C_Comm.Read(), Device.setErrorComStatus(), DataElement.value, VE1_CLOSE_STATUS_BIT, VE1_OPEN_STATUS_BIT, VE2_CLOSE_STATUS_BIT, VE2_OPEN_STATUS_BIT, VENT_CLOSE_STATUS_BIT, VENT_OPEN_STATUS_BIT, VP_CLOSE_STATUS_BIT, VP_OPEN_STATUS_BIT, and VSPARE_STATUS_BIT.
updateDeviceData() [7/8]
void Controllino_2.updateDeviceData ()
Reimplemented from Device.
Definition at line 92 of file Controllino_2.java.
References bitRead(), Device.busmutex, BYPASS_OFF_STATUS_BIT, BYPASS_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, COMPRESSAIR_STATUS_BIT, DataManager.getDataElement(), Device.hasWarned, i2c, logger, Device.name, Device.popCommand(), I2C_Comm.Read4bytesPlusCRC32(), Device.setErrorComStatus(), DataElement.value, VE1_CLOSE_STATUS_BIT, VE1_OPEN_STATUS_BIT, VE2_CLOSE_STATUS_BIT, VE2_OPEN_STATUS_BIT, VENT_CLOSE_STATUS_BIT, VENT_OPEN_STATUS_BIT, VP_CLOSE_STATUS_BIT, VP_OPEN_STATUS_BIT, and VSPARE_STATUS_BIT.
updateDeviceData() [8/8]
void Controllino_2.updateDeviceData ()
Reimplemented from Device.
Definition at line 69 of file Controllino_2.java.
References bitRead(), Device.busmutex, CHANNEL_1_OFF_STATUS_BIT, CHANNEL_1_ON_STATUS_BIT, CHANNEL_2_OFF_STATUS_BIT, CHANNEL_2_ON_STATUS_BIT, Device.comm_cnt_failure, Device.comm_max_failure, DataManager.getDataElement(), Device.hasWarned, i2c, logger, MUXSHIELD_COMERR_STATUS_BIT, Device.name, Device.popCommand(), I2C_Comm.ReadbytesPlusCRC32(), Device.setErrorComStatus(), SICEM_ALRM_STATUS_BIT, SICEM_COMERR_STATUS_BIT, and DataElement.value.
Member Data Documentation
ARD_RESET_BIT
static final int Controllino_2.ARD_RESET_BIT = 31 static private
Definition at line 34 of file Controllino_2.java.
BYPASS_OFF_CMD_BIT
static final int Controllino_2.BYPASS_OFF_CMD_BIT = 13 static private
Definition at line 32 of file Controllino_2.java.
Referenced by executeCommand().
BYPASS_OFF_STATUS_BIT
static final int Controllino_2.BYPASS_OFF_STATUS_BIT = 15 static private
Definition at line 34 of file Controllino_2.java.
Referenced by updateDeviceData().
BYPASS_ON_CMD_BIT
static final int Controllino_2.BYPASS_ON_CMD_BIT = 12 static private
Definition at line 31 of file Controllino_2.java.
Referenced by executeCommand().
BYPASS_ON_STATUS_BIT
static final int Controllino_2.BYPASS_ON_STATUS_BIT = 14 static private
Definition at line 33 of file Controllino_2.java.
Referenced by updateDeviceData().
CHANNEL_1_OFF_CMD_BIT
final int Controllino_2.CHANNEL_1_OFF_CMD_BIT = 5 static private
Definition at line 24 of file Controllino_2.java.
Referenced by executeCommand().
CHANNEL_1_OFF_STATUS_BIT
final int Controllino_2.CHANNEL_1_OFF_STATUS_BIT = 1 static private
Definition at line 20 of file Controllino_2.java.
Referenced by updateDeviceData().
CHANNEL_1_ON_CMD_BIT
final int Controllino_2.CHANNEL_1_ON_CMD_BIT = 4 static private
Definition at line 23 of file Controllino_2.java.
Referenced by executeCommand().
CHANNEL_1_ON_STATUS_BIT
final int Controllino_2.CHANNEL_1_ON_STATUS_BIT = 0 static private
Definition at line 19 of file Controllino_2.java.
Referenced by updateDeviceData().
CHANNEL_2_OFF_CMD_BIT
final int Controllino_2.CHANNEL_2_OFF_CMD_BIT = 7 static private
Definition at line 26 of file Controllino_2.java.
Referenced by executeCommand().
CHANNEL_2_OFF_STATUS_BIT
final int Controllino_2.CHANNEL_2_OFF_STATUS_BIT = 3 static private
Definition at line 22 of file Controllino_2.java.
Referenced by updateDeviceData().
CHANNEL_2_ON_CMD_BIT
final int Controllino_2.CHANNEL_2_ON_CMD_BIT = 6 static private
Definition at line 25 of file Controllino_2.java.
Referenced by executeCommand().
CHANNEL_2_ON_STATUS_BIT
final int Controllino_2.CHANNEL_2_ON_STATUS_BIT = 2 static private
Definition at line 21 of file Controllino_2.java.
Referenced by updateDeviceData().
CHILLER_OFF_CMD_BIT
final int Controllino_2.CHILLER_OFF_CMD_BIT = 11 static private
Definition at line 30 of file Controllino_2.java.
Referenced by executeCommand().
CHILLER_ON_CMD_BIT
final int Controllino_2.CHILLER_ON_CMD_BIT = 10 static private
Definition at line 29 of file Controllino_2.java.
Referenced by executeCommand().
CHILLER_STATUS_BIT
final int Controllino_2.CHILLER_STATUS_BIT = 4 static private
Definition at line 23 of file Controllino_2.java.
Referenced by updateDeviceData().
COMPRESSAIR_STATUS_BIT
static final int Controllino_2.COMPRESSAIR_STATUS_BIT = 21 static private
Definition at line 40 of file Controllino_2.java.
Referenced by updateDeviceData().
CP800_OFF_CMD_BIT
final int Controllino_2.CP800_OFF_CMD_BIT = 9 static private
Definition at line 28 of file Controllino_2.java.
Referenced by executeCommand().
CP800_ON_CMD_BIT
final int Controllino_2.CP800_ON_CMD_BIT = 8 static private
Definition at line 27 of file Controllino_2.java.
Referenced by executeCommand().
CP800_STATUS_BIT
final int Controllino_2.CP800_STATUS_BIT = 3 static private
Definition at line 22 of file Controllino_2.java.
Referenced by updateDeviceData().
CP900_OFF_CMD_BIT
final int Controllino_2.CP900_OFF_CMD_BIT = 7 static private
Definition at line 26 of file Controllino_2.java.
Referenced by executeCommand().
CP900_ON_CMD_BIT
final int Controllino_2.CP900_ON_CMD_BIT = 6 static private
Definition at line 25 of file Controllino_2.java.
Referenced by executeCommand().
CP900_STATUS_BIT
final int Controllino_2.CP900_STATUS_BIT = 2 static private
Definition at line 21 of file Controllino_2.java.
Referenced by updateDeviceData().
FLUX_STATUS_BIT
final int Controllino_2.FLUX_STATUS_BIT = 1 static private
Definition at line 20 of file Controllino_2.java.
Referenced by updateDeviceData().
i2c
I2C_Comm Controllino_2.i2c private
Definition at line 16 of file Controllino_2.java.
Referenced by Controllino_2(), executeCommand(), and updateDeviceData().
LEVEL_STATUS_BIT
final int Controllino_2.LEVEL_STATUS_BIT = 0 static private
Definition at line 19 of file Controllino_2.java.
Referenced by updateDeviceData().
logger
static final Logger Controllino_2.logger = Logger.getLogger("Main") static private
Definition at line 17 of file Controllino_2.java.
Referenced by Controllino_2(), executeCommand(), and updateDeviceData().
MUXSHIELD_COMERR_BIT
final int Controllino_2.MUXSHIELD_COMERR_BIT = 14 static private
Definition at line 33 of file Controllino_2.java.
MUXSHIELD_COMERR_STATUS_BIT
final int Controllino_2.MUXSHIELD_COMERR_STATUS_BIT = 10 static private
Definition at line 29 of file Controllino_2.java.
Referenced by updateDeviceData().
P22_OFF_CMD_BIT
static final int Controllino_2.P22_OFF_CMD_BIT = 17 static private
Definition at line 36 of file Controllino_2.java.
Referenced by executeCommand().
P22_ON_CMD_BIT
static final int Controllino_2.P22_ON_CMD_BIT = 16 static private
Definition at line 35 of file Controllino_2.java.
Referenced by executeCommand().
P22_STATUS_BIT
static final int Controllino_2.P22_STATUS_BIT = 18 static private
Definition at line 37 of file Controllino_2.java.
Referenced by updateDeviceData().
PUMP_OFF_CMD_BIT
final int Controllino_2.PUMP_OFF_CMD_BIT = 13 static private
Definition at line 32 of file Controllino_2.java.
Referenced by executeCommand().
PUMP_ON_CMD_BIT
final int Controllino_2.PUMP_ON_CMD_BIT = 12 static private
Definition at line 31 of file Controllino_2.java.
Referenced by executeCommand().
PUMP_STATUS_BIT
final int Controllino_2.PUMP_STATUS_BIT = 5 static private
Definition at line 24 of file Controllino_2.java.
Referenced by updateDeviceData().
SICEM_ALRM_STATUS_BIT
final int Controllino_2.SICEM_ALRM_STATUS_BIT = 8 static private
Definition at line 27 of file Controllino_2.java.
Referenced by updateDeviceData().
SICEM_COMERR_STATUS_BIT
final int Controllino_2.SICEM_COMERR_STATUS_BIT = 9 static private
Definition at line 28 of file Controllino_2.java.
Referenced by updateDeviceData().
V1_CLOSE_CMD_BIT
static final int Controllino_2.V1_CLOSE_CMD_BIT = 9 static private
Definition at line 28 of file Controllino_2.java.
Referenced by executeCommand().
V1_CLOSE_STATUS_BIT
static final int Controllino_2.V1_CLOSE_STATUS_BIT = 11 static private
Definition at line 30 of file Controllino_2.java.
Referenced by updateDeviceData().
V1_OPEN_CMD_BIT
static final int Controllino_2.V1_OPEN_CMD_BIT = 8 static private
Definition at line 27 of file Controllino_2.java.
Referenced by executeCommand().
V1_OPEN_STATUS_BIT
static final int Controllino_2.V1_OPEN_STATUS_BIT = 10 static private
Definition at line 29 of file Controllino_2.java.
Referenced by updateDeviceData().
V21_CLOSE_CMD_BIT
static final int Controllino_2.V21_CLOSE_CMD_BIT = 1 static private
Definition at line 20 of file Controllino_2.java.
Referenced by executeCommand().
V21_CLOSE_STATUS_BIT
static final int Controllino_2.V21_CLOSE_STATUS_BIT = 3 static private
Definition at line 22 of file Controllino_2.java.
Referenced by updateDeviceData().
V21_OPEN_CMD_BIT
static final int Controllino_2.V21_OPEN_CMD_BIT = 0 static private
Definition at line 19 of file Controllino_2.java.
Referenced by executeCommand().
V21_OPEN_STATUS_BIT
static final int Controllino_2.V21_OPEN_STATUS_BIT = 2 static private
Definition at line 21 of file Controllino_2.java.
Referenced by updateDeviceData().
V22_CLOSE_CMD_BIT
static final int Controllino_2.V22_CLOSE_CMD_BIT = 5 static private
Definition at line 24 of file Controllino_2.java.
Referenced by executeCommand().
V22_CLOSE_STATUS_BIT
static final int Controllino_2.V22_CLOSE_STATUS_BIT = 7 static private
Definition at line 26 of file Controllino_2.java.
Referenced by updateDeviceData().
V22_OPEN_CMD_BIT
static final int Controllino_2.V22_OPEN_CMD_BIT = 4 static private
Definition at line 23 of file Controllino_2.java.
Referenced by executeCommand().
V22_OPEN_STATUS_BIT
static final int Controllino_2.V22_OPEN_STATUS_BIT = 6 static private
Definition at line 25 of file Controllino_2.java.
Referenced by updateDeviceData().
V23_CLOSE_STATUS_BIT
static final int Controllino_2.V23_CLOSE_STATUS_BIT = 20 static private
Definition at line 39 of file Controllino_2.java.
Referenced by updateDeviceData().
V23_OPEN_STATUS_BIT
static final int Controllino_2.V23_OPEN_STATUS_BIT = 19 static private
Definition at line 38 of file Controllino_2.java.
Referenced by updateDeviceData().
VE1_CLOSE_STATUS_BIT
static final int Controllino_2.VE1_CLOSE_STATUS_BIT = 18 static private
Definition at line 37 of file Controllino_2.java.
Referenced by updateDeviceData().
VE1_OPEN_STATUS_BIT
static final int Controllino_2.VE1_OPEN_STATUS_BIT = 17 static private
Definition at line 36 of file Controllino_2.java.
Referenced by updateDeviceData().
VE2_CLOSE_STATUS_BIT
static final int Controllino_2.VE2_CLOSE_STATUS_BIT = 20 static private
Definition at line 39 of file Controllino_2.java.
Referenced by updateDeviceData().
VE2_OPEN_STATUS_BIT
static final int Controllino_2.VE2_OPEN_STATUS_BIT = 19 static private
Definition at line 38 of file Controllino_2.java.
Referenced by updateDeviceData().
VENT_CLOSE_CMD_BIT
static final int Controllino_2.VENT_CLOSE_CMD_BIT = 1 static private
Definition at line 20 of file Controllino_2.java.
Referenced by executeCommand().
VENT_CLOSE_STATUS_BIT
static final int Controllino_2.VENT_CLOSE_STATUS_BIT = 3 static private
Definition at line 22 of file Controllino_2.java.
Referenced by updateDeviceData().
VENT_OPEN_CMD_BIT
static final int Controllino_2.VENT_OPEN_CMD_BIT = 0 static private
Definition at line 19 of file Controllino_2.java.
Referenced by executeCommand().
VENT_OPEN_STATUS_BIT
static final int Controllino_2.VENT_OPEN_STATUS_BIT = 2 static private
Definition at line 21 of file Controllino_2.java.
Referenced by updateDeviceData().
VENTSOFT_CLOSE_CMD_BIT
static final int Controllino_2.VENTSOFT_CLOSE_CMD_BIT = 5 static private
Definition at line 24 of file Controllino_2.java.
Referenced by executeCommand().
VENTSOFT_OPEN_CMD_BIT
static final int Controllino_2.VENTSOFT_OPEN_CMD_BIT = 4 static private
Definition at line 23 of file Controllino_2.java.
Referenced by executeCommand().
VP_CLOSE_CMD_BIT
static final int Controllino_2.VP_CLOSE_CMD_BIT = 7 static private
Definition at line 26 of file Controllino_2.java.
Referenced by executeCommand().
VP_CLOSE_STATUS_BIT
static final int Controllino_2.VP_CLOSE_STATUS_BIT = 9 static private
Definition at line 28 of file Controllino_2.java.
Referenced by updateDeviceData().
VP_OPEN_CMD_BIT
static final int Controllino_2.VP_OPEN_CMD_BIT = 6 static private
Definition at line 25 of file Controllino_2.java.
Referenced by executeCommand().
VP_OPEN_STATUS_BIT
static final int Controllino_2.VP_OPEN_STATUS_BIT = 8 static private
Definition at line 27 of file Controllino_2.java.
Referenced by updateDeviceData().
VSPARE_OFF_CMD_BIT
static final int Controllino_2.VSPARE_OFF_CMD_BIT = 15 static private
Definition at line 34 of file Controllino_2.java.
Referenced by executeCommand().
VSPARE_ON_CMD_BIT
static final int Controllino_2.VSPARE_ON_CMD_BIT = 14 static private
Definition at line 33 of file Controllino_2.java.
Referenced by executeCommand().
VSPARE_STATUS_BIT
static final int Controllino_2.VSPARE_STATUS_BIT = 16 static private
Definition at line 35 of file Controllino_2.java.
Referenced by updateDeviceData().
The documentation for this class was generated from the following file:
work_cryo1500w/Controllino_2.java